### ISSUE TITLE
SNP that looks real through IGV is not called

### ISSUE THREAD

**Issue by hongssy** [google/deepvariant#366] opened 2020-10-23 01:37 UTC
**Describe the issue:**
hi 
I used deepvariant version 1.0.0 to analyze the ccs data of mitochondria, but a snp was not called. The details are as follows：

![image](https://user-images.githubusercontent.com/25741799/96946498-20930500-1513-11eb-988c-d308fe52db80.png)
![image](https://user-images.githubusercontent.com/25741799/96946551-44eee180-1513-11eb-8d3a-c57b532cef58.png)

**Comment by akolesnikov** [comment] 2020-10-25 19:15
Hi,

Couple of points:
* DeepVariant model is created specifically for a human genome. It may not perform optimally on a non-human data. 
* It looks like candidate was not created at all so this is not a model issue. I cannot say exactly why candidate was not created but having the exact command line may help. 
* By default DeepVariant performs a local realignment when creating candidates. With this coverage it may not work as intended.

**Comment by hongssy** [comment] 2020-10-26 02:49
thanks for your responses

command line：
docker run  \
  -v /sfs-grand-med-research/:/sfs-grand-med-research/ \
  swr.cn-north-1.myhuaweicloud.com/grand-med-clinical/deepvariant:"1.0.0" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=PACBIO \
  --ref=human_g1k_v37.main_chrom.fasta \
  --reads=202022.hg19.pbmm2.sort.MT.bam \
  --output_vcf=202022.MT.vcf.gz \
  --num_shards=16 \
  --intermediate_results_dir=/tmp/

logfile：
[hg19_MT_deepvariant.log](https://github.com/google/deepvariant/files/5436542/hg19_MT_deepvariant.log)

**Comment by AndrewCarroll** [comment] 2020-10-27 06:43
Hi @hongssy 

I think I may know why this variant isn't being called. To call variants, Deepvariant constructs a pileup image of a 221 bp region of the genome (110 bp to the left and right of the candidate position). If the start or end of the contig falls within this window, DeepVariant will fail, and as a result we do not generate candidates when this is the case.

Normally, the ends of a contig are telomeric or scaffold sequence, so variants can't meaningfully be called there anyway. 

However, the mitochondrial genome is circular, so all of the sequence will have valid mappings (especially with HiFi data, where a read can span the entire genome). This means that DeepVariant will not be able to call the final ~110 bp and the first ~110 bp of the genome. In your IGV image, I think you can see this artifact as the softclip sequence before the first position. 

I had not appreciated that this limitation existed until now, and will need to think about the best way to address it. I am sorry that I do not have a fast fix to this issue.

Thank you,
Andrew

**Comment by gunjanbaid** [comment] 2020-10-30 22:19
I'll close this issue now, but feel free to reopen if you have any other questions @hongssy.

**Closed by gunjanbaid** 2020-10-30 22:19 UTC
