### ISSUE TITLE
Returns error while evaluating the model on Arabidopsis Thailand Sample

### ISSUE THREAD

**Issue by sivianil** [google/deepvariant#606] opened 2023-01-25 11:42 UTC
I tried to run the model on one of the Arabidopsis thaliana sample from 1001 genomes website. Without reporting any errors, the model ran perfectly fine (make_examples, call_variants, postprocess_variants). But when evaluating the results against the ground truth on all chromosomes, it returns error stating that records at specific positions disagree on what the reference bases should be. I attached the screenshot for reference to give you an idea. 
<img width="1499" alt="Screenshot 2023-01-25 at 12 32 33" src="https://user-images.githubusercontent.com/75676816/214554128-84fd25af-90b4-4110-be27-c2344a840bc4.png">

**Comment by AndrewCarroll** [comment] 2023-01-26 00:01
Hi @sivianil 

Are you able to get the VCF lines from DeepVariant and from the truth VCF for this coordinate position? If there is a line from DeepVariant, does the line have a G or a C there?

If there is a variant entry from the Truth set, does the line have a G or a C there.

If there isn't an entry at this position from DeepVariant which differs from the reference, then the issue is likely in the agreement with the truth set and the reference.

**Comment by sivianil** [comment] 2023-01-26 09:54
Hello Andrew,
 
I got the VCF line from only DeepVariant generated file for this specific position. From the DeepVariant REF column have G and the ALT column have GCTCT,GCTCTCT. Two different alternate alleles of both insertion types. So I can say this comes under Multiallelic Insertion category. 

From the truth VCF file, there is no line for this coordinate position. When I evaluated using hap.py, it returns error as I commented earlier in the above post. 

Does the model consider both Multiallelic variant type and Biallelic or only Biallelic during evaluation? Is there any way I can filter the VCF lines having Multiallelic variant types?

**Comment by AndrewCarroll** [comment] 2023-01-27 00:37
Hi @sivianil 

That is interesting. I don't think that this error message has something to do with the allele being multiallelic. We generate multiallelic outputs for human samples and hap.py works for those. 

If you want to filter to only bi-allelic calls, you can post-process the VCF with bcftools 

`bcftools view -m2 -M2`

From reading the error, it seems that the most likely explanation is that the reference genome used in the hap.py evaluation does not exactly match the sequence of the reference genome used to map the reads in the BAM file used in DeepVariant. Are you certain those two files are exactly the same?

Thanks,
Andrew

**Comment by sivianil** [comment] 2023-01-27 10:59
Hi Andrew,

Yes, I'm sure the same reference fasta file used for both mapping the reads in the BAM file and during the hap.py evaluation. 

From the result I got when evaluated for chr1:8700-20000, there are no true positives at all. The positions at which DeepVariant model generated in output.vcf are not at all existed in Gold Standard Truth set variant file. I'm not sure the reason behind this. Is it becoz, the model trained on human data? I attached both DeepVariant model generated vcf file and GS vcf file. Have a look at it! 
[output.vcf.gz](https://github.com/google/deepvariant/files/10518129/output.vcf.gz)
[intersection-801.vcf.gz](https://github.com/google/deepvariant/files/10518132/intersection-801.vcf.gz)


Did anyone tried to run previously on Arabidopsis Thalia samples and encountered the same issue I'm facing?

**Comment by sivianil** [comment] 2023-01-27 14:36
Well, I generated the BAM file using bam and samtools from fastq files. The file is too large to share. I'll add the one drive link to access the file.
[https://1001genomes.org/data/GMI-MPI/releases/v3.1/pseudogenomes/fasta/pseudo801.fasta.gz](url)
[https://unipotsdamde-my.sharepoint.com/:u:/g/personal/anil_kumar_boddapati_uni-potsdam_de/EYyX5a4xEqBBrH4aXAID8KcB9__Q3s34vU3cTfav0J-VrA?e=owCGZI](url)

Best,
Anil

**Comment by AndrewCarroll** [comment] 2023-01-28 00:49
Hi @sivianil 

Thank you for the files. With them, I was able to get a better idea of the problem.

The problem is that the file that you are providing as your truth set file (801_snp_short_indel_with_quality_reference.vcf.gz) has an entry on chr1 position 8669 which disagrees in the REF field with the file that you are providing as your reference (pseudo801.fasta.gz).

According to *pseudo801.fasta.gz* the reference base is *G*.

The line in *801_snp_short_indel_with_quality_reference.vcf.gz* has an entry on this field as:

```
1       8669    .       C       .       38      PASS    DP=16   GT:GQ:DP        0|0:38:16
```

According to this VCF, the reference base listed at this position is *C*.

You will get this error with hap.py regardless the content of the DeepVariant file. This error does not relate to DeepVariant at all. If you want to do any comparison with 801_snp_short_indel_with_quality_reference.vcf.gz you will need to reconcile the difference between the reference and the contents of the VCF. 

Does it really make sense to apply hap.py to this dataset? Hap.py was developed for comparison with highly curated truth datasets made with multiple technologies and/or corroborated by extensive pedigree information (e.g. as is available in Genome in a Bottle or Platinum Genomes). I'm not sure that the data present in the 1001 Arabidopsis Genomes projects would sufficiently allow such a comparison.

**Comment by sivianil** [comment] 2023-01-30 14:04
Hi Andrew,

The Gold standard vcf file you mentioned above is only based on SHORE pipeline. Yes, you were absolutely correct! The reference bases acc to fasta file and VCF file doesn't match.

Excluding that, when I tried to run the model on subset of positions for chr1, I can't get any true positives in the result. The result contains only FN, so the model didn't make call for single variant position which are present in Truth VCF file. Please look at the screenshot I attached


I will ask my supervisor, if there is any possibility to reconcile the difference b/w the reference and bases of the VCF. Thanks for finding the actual error. 

Best,
Anil

<img width="1505" alt="Screenshot 2023-01-30 at 15 04 23" src="https://user-images.githubusercontent.com/75676816/215498753-e4340ba2-0573-4b13-a10d-33fb593cfd9f.png">

**Comment by AndrewCarroll** [comment] 2023-02-03 22:09
Hi @sivianil 

I don't think that the comparison you posted is working. I note that your Truth file lists the contig names as "1, 2, 3,..." while the DeepVariant VCF and Reference genome name the chromosomes as "chr1, chr2, chr3, ...".

It seems almost certain that your hap.py comparison doesn't see any overlap in the contigs present in your truth set and the contigs present in the Reference genome.

**Comment by pichuan** [comment] 2023-02-10 17:08
@sivianil Feel free to re-open if you want to follow up. I'll close this issue for now.

**Closed by pichuan** 2023-02-10 17:08 UTC
