### ISSUE TITLE
Feedback on poor results in family variation detection and GIAB dataset evaluation

### ISSUE THREAD

**Issue by linlin-coder** [google/deepvariant#689] opened 2023-08-01 10:11 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**:
yes，i have checked this FAQ document. 
**Describe the issue:**
I used Deeprio v1.4.0 version to perform family analysis on three samples, HG002, HG003, and HG004, and evaluated the accuracy of mutation detection using the GIAB database (NISTv4.2.1). I found that the evaluation results through GIAB were particularly unsatisfactory, but I used the same data and Deepvariant v1.5.0 for single sample analysis, and the evaluation results were very ideal, I don't quite understand why the analysis results of a single sample perform so well at the evaluation level compared to the results of family analysis, and why the results of family analysis are relatively poor. The following is my family analysis and analysis code for individual samples, as well as the evaluation results of the GIAB database, for developers to review:
Data comparison to reference genome:
```
echo HG002.merged.fastq.gz > HG002.fofn 
pbmm2 align \
 --preset HIFI \
 genome/hg38.fa.mmi \
 HG002.fofn \
 --sample HG002 \
 -j 10 \
 HG002.aligned.tmp.bam 
samtools sort -@ 10 HG002.aligned.tmp.bam -O BAM -o HG002.aligned.tmp.sort.bam 
samtools index -@ 10 HG002.aligned.tmp.sort.bam 
chromosomes=(chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM) 
for chromosome in "${chromosomes[@]}"; \
 do \
 samtools view -@ 2 -b -h HG002.aligned.tmp.sort.bam "$chromosome" --output HG002.aligned.$chromosome.tmp.bam & 
done 
wait 
samtools merge HG002.aligned.bam HG002.aligned.chr*.tmp.bam 
samtools sort -@ 10 HG002.aligned.bam -O BAM -o HG002.sort.bam 
samtools index -@ 10 HG002.sort.bam 
```
Family analysis code:
```
rm -rf chr20_GLnexus.DB tmp_ramdom_TrioDemo_chr20 
samtools view --write-index --threads 10 -h -b -S HG002.sort.bam chr20 -O BAM -o HG002.chr20.sort.bam 
samtools view --write-index --threads 10 -h -b -S HG003.sort.bam chr20 -O BAM -o HG003.chr20.sort.bam 
samtools view --write-index --threads 10 -h -b -S HG004.sort.bam chr20 -O BAM -o HG004.chr20.sort.bam 
/usr/bin/singularity exec --cleanenv  -B /share/:/share/ Singularity/deepvariant.deeptrio-1.4.0.sif /opt/deepvariant/bin/deeptrio/run_deeptrio \
 --model_type PACBIO \
 --ref=genome/hg38.fa \
 --reads_child HG002.chr20.sort.bam \
 --reads_parent1 HG003.chr20.sort.bam \
 --reads_parent2 HG004.chr20.sort.bam \
 --output_vcf_child HG002.chr20.output.vcf.gz \
 --output_vcf_parent1 HG003.chr20.output.vcf.gz \
 --output_vcf_parent2 HG004.chr20.output.vcf.gz \
 --sample_name_child 'HG002' \
 --sample_name_parent1 'HG003' \
 --sample_name_parent2 'HG004' \
 --num_shards 10 \
 --intermediate_results_dir tmp_ramdom_TrioDemo_chr20 \
 --output_gvcf_child HG002.chr20.g.vcf.gz \
 --output_gvcf_parent1 HG003.chr20.g.vcf.gz \
 --output_gvcf_parent2 HG004.chr20.g.vcf.gz 
glnexus_cli_v1.4.1 \
 --config DeepVariant_unfiltered \
 --squeeze \
 --dir chr20_GLnexus.DB \
 HG002.chr20.g.vcf.gz HG003.chr20.g.vcf.gz HG004.chr20.g.vcf.gz \
 --threads 10 | \
 /opt/conda/envs/bio/bin/bcftools view \
 --threads 10 -O z \
 -o TrioDemo_chr20.trio_merged.vcf.gz - 
```
The following is the code for single sample mutation detection:
```
samtools view --threads 10 -h -b -S HG002.sort.bam chr20 > HG002/HG002.chr20.sort.bam 
samtools index -@ 10 HG002/HG002.chr20.sort.bam 
singularity run /share:/share Singularity/google-deepvariant.1.5.0.sif \
 /opt/deepvariant/bin/run_deepvariant \
 --model_type PACBIO \
 --ref genome/hg38.fa \
 --intermediate_results_dir HG002/tmp_ramdom_HG002_chr20 \
 --reads HG002/HG002.chr20.sort.bam \
 --output_vcf HG002/HG002.chr20.vcf.gz \
 --num_shards 10 
rm -fr HG002/tmp_ramdom_HG002_chr20
```

The evaluation results of the trio family sample are as follows:

| HG002 | INDEL | PASS | 525469  | 190669  | 334800  | 361066  | 7821  | 151401 | 4826  | 2317 | 0.362855 | 0.962698 | 0.419317 | 0.527055 |             |            | 1.528275734 | 1.988539738 |
|-------|-------|------|---------|---------|---------|---------|-------|--------|-------|------|----------|----------|----------|----------|-------------|------------|-------------|-------------|
| HG002 | SNP   | PASS | 3365127 | 1236543 | 2128584 | 1466059 | 19913 | 209456 | 19190 | 463  | 0.367458 | 0.984153 | 0.14287  | 0.535117 | 2.100128487 | 1.97508094 | 1.581195853 | 1.464696928 |
| HG003 | INDEL | PASS | 504501  | 208450  | 296051  | 405929  | 3464  | 179579 | 1622  | 1671 | 0.413181 | 0.984696 | 0.44239  | 0.582108 |             |            | 1.489759281 | 2.088373264 |
| HG003 | SNP   | PASS | 3327495 | 1382128 | 1945367 | 1624627 | 4896  | 237970 | 4040  | 418  | 0.415366 | 0.996469 | 0.146477 | 0.586328 | 2.102574954 | 1.97169418 | 1.535137772 | 1.544597915 |
| HG004 | INDEL | PASS | 510519  | 201567  | 308952  | 391501  | 3657  | 171779 | 1906  | 1591 | 0.394828 | 0.983356 | 0.43877  | 0.563432 |             |            | 1.516130736 | 2.119421815 |
| HG004 | SNP   | PASS | 3346610 | 1327354 | 2019256 | 1571257 | 6926  | 237287 | 6170  | 372  | 0.396626 | 0.994808 | 0.151017 | 0.567137 | 2.100774713 | 1.97061742 | 1.586871602 | 1.557512324 |

The evaluation results of a single sample are as follows：
| HG002 | INDEL | PASS | 525469  | 517775  | 7694 | 1008549 | 9950 | 448712 | 4791 | 3342 | 0.985358 | 0.982227 | 0.444908 | 0.98379  |             |             | 1.528275734 | 2.114606634 |
|-------|-------|------|---------|---------|------|---------|------|--------|------|------|----------|----------|----------|----------|-------------|-------------|-------------|-------------|
| HG002 | SNP   | PASS | 3365127 | 3361925 | 3202 | 4312006 | 7891 | 942045 | 1197 | 719  | 0.999048 | 0.997658 | 0.21847  | 0.998353 | 2.100128487 | 1.823839956 | 1.581195853 | 1.50423718  |
| HG003 | INDEL | PASS | 504501  | 501414  | 3087 | 1009147 | 3989 | 471526 | 1814 | 1831 | 0.993881 | 0.99258  | 0.467252 | 0.99323  |             |             | 1.489759281 | 2.02565724  |
| HG003 | SNP   | PASS | 3327495 | 3323623 | 3872 | 4265460 | 4910 | 936912 | 1118 | 617  | 0.998836 | 0.998525 | 0.219651 | 0.998681 | 2.102574954 | 1.831128594 | 1.535137772 | 1.484295493 |
| HG004 | INDEL | PASS | 510519  | 507376  | 3143 | 1013737 | 4102 | 469356 | 1887 | 1729 | 0.993844 | 0.992465 | 0.462996 | 0.993154 |             |             | 1.516130736 | 2.075927402 |

analysising result：Using the same test data as the scattered samples, it can be found that the variation detection results of the HG002/3/4 family sample are relatively poor when tested using the GIAB standard set，but I don't understand the reason for this difference.

**Setup**
  - Operating system: image of singularity, transforming from docker image of deeptrio-1.4.0
  - DeepVariant version:deeptrio-1.4.0
  - Installation method (Docker, built from source, etc.):Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
    HiFi data,those data download links follows:
    * HG002:https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/PacBio_HiFi/15kb/;https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/PacBio_HiFi/20kb/
    * HG003:https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG003/PacBio_HiFi/Google_15kb;https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG003/PacBio_HiFi/HudsonAlpha_15kb
    * HG004:https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG004/PacBio_HiFi/Google_15kb/;https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG004/PacBio_HiFi/HudsonAlpha_15kb/PBmixSequel733_2_B01_PBSU_30hours_15kbV2PD_70pM_HumanHG004_CCS/
**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by pgrosu** [comment] 2023-08-01 12:14
Hi @linlin-coder,

I noticed that you were using 1.4.0 of DeepTrio, and there are Docker containers for DeepTrio 1.5.0:

[deeptrio-1.5.0](https://hub.docker.com/layers/google/deepvariant/deeptrio-1.5.0/images/sha256-82759ab1e1289b4ebcf5af8760a1446013ceb8e538aa1ffbf6bea5402012960c?context=explore)

[deeptrio-1.5.0-gpu](https://hub.docker.com/layers/google/deepvariant/deeptrio-1.5.0-gpu/images/sha256-6876344f0cbc235909326fd7757129ed80cd9cfc6ef04251bd9d330c4301ad84?context=explore)

So DeepTrio has its own models, as does DeepVariant, both of which are version-specific.  Regarding DeepVariant specifically I know that the variant call probabilities are well-calibrated within each model individually, so that GLnexus can operate on them -- something that Andrew confirmed previously.

Hope it helps,
Paul

**Comment by pichuan** [comment] 2023-08-01 17:02
Hi @linlin-coder ,
Thank you for bringing up this issue.

I noticed that you're working on PacBio data.

The reason why this is happening is:

In v1.3.0 or older, DeepVariant didn't have the read haplotagging functionality built in. If you see https://github.com/google/deepvariant/blob/r1.3/docs/deepvariant-pacbio-model-case-study.md , you'll see that we asked our users to run DeepVariant --> WhatsHap --> DeepVariant with HP information to get the best accuracy.

Starting from v1.4.0, **DeepVariant** has the read haplotagging functionality built in. However, **DeepTrio** doesn't have this yet, even in the latest version. That's why in https://github.com/google/deepvariant/blob/r1.5/docs/deeptrio-pacbio-case-study.md , you'll see this sentence

> The `--use_hp_information` arg makes use of a phased reads, thus allowing a further improvement of the accuracy. You can use tools like whatshap to phase.

So, for now, if you want to get the best accuracy using DeepTrio, our suggestion will be:
Run DeepVariant first --> Use WhatsHap to get HP tags for your read --> Run DeepTrio with the `--use_hp_information` tag.

I'm sorry that we were not being a lot more clear in our documentation. In our next release (plan to be out before the end of this year), we will have the read haplotagging feature directly built in in DeepTrio as well, so that you don't have to worry about having to run WhatsHap in between, starting from our next release.

@linlin-coder Let me know if you have more questions that I can help clarify. Thanks!

**Comment by linlin-coder** [comment] 2023-08-02 02:39
> Hi @linlin-coder,
> 
> I noticed that you were using 1.4.0 of DeepTrio, and there are Docker containers for DeepTrio 1.5.0:
> 
> [deeptrio-1.5.0](https://hub.docker.com/layers/google/deepvariant/deeptrio-1.5.0/images/sha256-82759ab1e1289b4ebcf5af8760a1446013ceb8e538aa1ffbf6bea5402012960c?context=explore)
> 
> [deeptrio-1.5.0-gpu](https://hub.docker.com/layers/google/deepvariant/deeptrio-1.5.0-gpu/images/sha256-6876344f0cbc235909326fd7757129ed80cd9cfc6ef04251bd9d330c4301ad84?context=explore)
> 
> So DeepTrio has its own models, as does DeepVariant, both of which are version-specific. Regarding DeepVariant specifically I know that the variant call probabilities are well-calibrated within each model individually, so that GLnexus can operate on them -- something that Andrew confirmed previously.
> 
> Hope it helps, Paul

thanks for your suggestion, meanwhile i installed deeptrio-1.5.0 in my computer, but the analysising result of deeptrio-1.5.0 display run failed, error information is 
```
2023-08-02 10:09:51.033332: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
To run DeepTrio PACBIO, please use version v1.4.0. See https://github.com/google/deepvariant/blob/r1.4/docs/deeptrio-pacbio-case-study.md
``` 
cause of this cause of this error information, i use deeptrio v1.4.0  to call variation.

**Comment by linlin-coder** [comment] 2023-08-02 02:43
> Hi @linlin-coder , Thank you for bringing up this issue.
> 
> I noticed that you're working on PacBio data.
> 
> The reason why this is happening is:
> 
> In v1.3.0 or older, DeepVariant didn't have the read haplotagging functionality built in. If you see https://github.com/google/deepvariant/blob/r1.3/docs/deepvariant-pacbio-model-case-study.md , you'll see that we asked our users to run DeepVariant --> WhatsHap --> DeepVariant with HP information to get the best accuracy.
> 
> Starting from v1.4.0, **DeepVariant** has the read haplotagging functionality built in. However, **DeepTrio** doesn't have this yet, even in the latest version. That's why in https://github.com/google/deepvariant/blob/r1.5/docs/deeptrio-pacbio-case-study.md , you'll see this sentence
> 
> > The `--use_hp_information` arg makes use of a phased reads, thus allowing a further improvement of the accuracy. You can use tools like whatshap to phase.
> 
> So, for now, if you want to get the best accuracy using DeepTrio, our suggestion will be: Run DeepVariant first --> Use WhatsHap to get HP tags for your read --> Run DeepTrio with the `--use_hp_information` tag.
> 
> I'm sorry that we were not being a lot more clear in our documentation. In our next release (plan to be out before the end of this year), we will have the read haplotagging feature directly built in in DeepTrio as well, so that you won't have to worry about having to run WhatsHap in between, starting from our next release.
> 
> @linlin-coder Let me know if you have more questions that I can help clarify. Thanks!

Thank you very much for your description of all the details of Deeptrio in the mutation detection environment. In the future, I will follow the process you suggested to redo the mutation detection. If there are no accidents, I will reply to you in the next two days. Thank you again

**Comment by pichuan** [comment] 2023-08-02 02:43
Hi @linlin-coder , 
Right, because in v1.5.0 we didn't really update DeepTrio PacBio, we decided to just point our users to v1.4.0, which was the version without the direct read haplotagging built in.

Like I mention, we expect v1.6.0 (coming out before end of this year) to have a new version of DeepTrio PacBio which won't require an extra step of WhatsHap in between.

**Comment by linlin-coder** [comment] 2023-08-02 03:06
> Hi @linlin-coder , Right, because in v1.5.0 we didn't really update DeepTrio PacBio, we decided to just point our users to v1.4.0, which was the version without the direct read haplotagging built in.
> 
> Like I mention, we expect v1.6.0 (coming out before end of this year) to have a new version of DeepTrio PacBio which won't require an extra step of WhatsHap in between.

Thank you to the author and the software developer for their continuous maintenance of open-source tools. As a software user, I will also continue to pay attention to the subsequent updates and article publications of this software. I look forward to more exchanges in the future

**Comment by pichuan** [comment] 2023-08-02 17:47
Thanks @linlin-coder . I'll close this issue now. If you have more questions or observations, feel free to let us know!

**Closed by pichuan** 2023-08-02 17:47 UTC
