### ISSUE TITLE
NoCall with missing PL value

### ISSUE THREAD

**Issue by GuillaumeHolley** [google/deepvariant#521] opened 2022-03-01 13:53 UTC
Hi,

I am using [Pepper-MARGIN-DeepVariant r0.7](https://github.com/kishwarshafin/pepper) with custom made models for Pepper-SNP, Pepper-HP and DeepVariant. As far as I know, this release uses DeepVariant 1.2.

I have run this pipeline successfully for a small cohort of about 100 genomes but when merging the GVCF files, [GLnexus 1.4.1](https://github.com/dnanexus-rnd/GLnexus) (with config `DeepVariant`) complains that at least one variant is missing PL values. I tracked down the issue to one GVCF were the record is:
```
CHR	POS	.	A	G,<*>	9.9	NoCall	.	GT:GQ:DP:AD:VAF:PL	./.:0:5:0,0,0:0,0:0,0,990,990,990
```
We can see that this GVCF record has 5 PL values where there should be 6. The corresponding record in the VCF file is:
```
CHR POS .	A	G	9.9	refCall	.	GT:GQ:DP:AD:VAF:C	./.:0:5:0:0:DV
```
The VCF record indicates that the variant call was issued by DeepVariant. 

Any ideas what could be the issue here?

Thank you for your help,
Guillaume

**Comment by kishwarshafin** [comment] 2022-03-02 17:02
@GuillaumeHolley ,

In the `intermediate_files` directory of PEPPER's output, you'll find a file named `DEEPVARIANT_OUTPUT.vcf.gz`. Can you please do a `bcftools view DEEPVARIANT_OUTPUT.vcf.gz CHR POS` to see if you have the associated PL values there?

**Comment by GuillaumeHolley** [comment] 2022-03-04 08:18
Hi @kishwarshafin,

Sorry for the delay. I checked the corresponding file:
```
CHR POS .	A	G	9.9	NoCall .	GT:GQ:DP:AD:VAF:PL	./.:0:5:0,0:0:0,0
```
So 2 PL values as it should be.

Thanks,
Guillaume

**Comment by kishwarshafin** [comment] 2022-03-04 19:15
@GuillaumeHolley , 

Thank you, then the issue is in the GVCF reporting I think.

**Comment by GuillaumeHolley** [comment] 2022-03-04 19:56
@kishwarshafin

Is it a DeepVariant issue then or a Pepper-Margin issue?

Thanks,
Guillaume

**Comment by cmclean** [comment] 2022-03-04 21:56
@GuillaumeHolley responding to your comment 2 above, I believe the corresponding DEEPVARIANT_OUTPUT.vcf.gz is malformatted -- it should have 3 PL values (corresponding to Phred-scaled likelihoods of 0/0, 0/1, 1/1 genotypes).

**Comment by GuillaumeHolley** [comment] 2022-03-06 22:39
@cmclean, you are absolutely right, it should have been 3 PL values and not 2 as I initially wrote. So it is a DeepVariant issue and not a Pepper-MARGIN one.

**Comment by pichuan** [comment] 2022-03-07 19:06
Hi @GuillaumeHolley , thanks for reporting this.
We'll need to look into our data and see if we can find an example like this as well.
If it possible for to you to share a small, reproducible setting (with commands), that will also help us a lot in debugging.

**Comment by pichuan** [comment] 2022-03-16 03:24
Hi @GuillaumeHolley , checking again:
If you have an easy example to share for reproducing this, that will be great. 
If not, I can also go through some of our existing VCF files and look for this pattern. It might take me a while to get to this. I can keep this open until when we have time to take a look.

**Comment by pichuan** [comment] 2022-03-21 16:21
Hi @GuillaumeHolley ,
to give you an update, I haven't had time to go search for an example. But I'll keep this open in case you want to share an example (or when I have a chance to find one). Thanks!

**Comment by GuillaumeHolley** [comment] 2022-03-21 16:26
Hi @pichuan,

I apologize for the delay. I'll try to get a small BAM with which the issue can be reproduced. I would rather not share the BAM file here, is there an email address I can use to share the information?

Thanks,
Guillaume

**Comment by pichuan** [comment] 2022-03-21 16:28
Hi @GuillaumeHolley ,
yes! Please email me at pichuan@google.com

**Comment by kishwarshafin** [comment] 2022-04-11 17:39
Hi @GuillaumeHolley ,

This issue needs to be taken care of from PEPPER's side. I'll close this issue from here and open up on PEPPER's github. Sorry that it's taking a bit longer than expected, PEPPER is going through a transition but someone is actively looking into this issue to fix it.

**Closed by kishwarshafin** 2022-04-11 17:39 UTC

**Comment by GuillaumeHolley** [comment] 2022-04-12 15:00
Hi @kishwarshafin,

No worries, thanks for looking into this :)

**Comment by kishwarshafin** [comment] 2022-04-15 19:38
@GuillaumeHolley ,

After working on this for a while, it looks like the solution isn't that easy. On your end, can you please try filtering all the `NoCall` variants from the gvcf file as a post-processing and see if that helps? I was able to get rid of the GLNexus error by filtering `NoCall` variants with `bcftools`.

**Comment by GuillaumeHolley** [comment] 2022-04-19 10:39
Hi @kishwarshafin,

Thanks for the feedback, I actually forgot to get back to you about this but I have indeed filtered out the `NoCall` for the small cohort I have after your early feedback and it indeed solved this issue.

Good luck with solving this!

Guillaume
