### ISSUE TITLE
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed

### ISSUE THREAD

**Issue by Sami-St** [google/deepvariant#677] opened 2023-07-13 11:31 UTC
**Describe the issue:**
Hello everyone, i am trying to run a Pacbio Workflow with deepvariant in it but i get an error in the make example step ( Rule and log below) i allready have an open Issue on the Workflow but we are at the Point that we think its ether Nucleus or Tensorflow that produces the error PacificBiosciences/HiFiTargetEnrichment#4 , since i cant find what the error is and how to fix it i opend the Issue

Many thanks in advance

**Setup**
  - Operating system: Ubuntu 20.04.6 LTS
  - DeepVariant version: 1.5.0
  - Tensorflow 2.11.0
  - Installation method (Docker, built from source, etc.): singularity
  - Type of data: PacBio HIFI reads

**Steps to reproduce:**
```
rule deepvariant_make_examples:
    input:
        bam=f"batches/{batch}/{{sample}}/aligned/{{sample}}.{ref}.bam",
        bai=f"batches/{batch}/{{sample}}/aligned/{{sample}}.{ref}.bam.bai",
        reference=config["ref"]["fasta"],
    output:
        tfrecord=temp(
            f"batches/{batch}/{{sample}}/deepvariant/examples/examples.tfrecord-{{shard}}-of-{config['N_SHARDS']:05}.gz"
        ),
        nonvariant_site_tfrecord=f"batches/{batch}/{{sample}}/deepvariant/examples/gvcf.tfrecord-{{shard}}-of-{config['N_SHARDS']:0>
    log:
        f"batches/{batch}/logs/deepvariant/make_examples/{{sample}}.{ref}.{{shard}}-of-{config['N_SHARDS']:05}.log",
    benchmark:
        f"batches/{batch}/benchmarks/deepvariant/{{sample}}.{{shard}}.dv_make_examples.tsv"
    container:
        f"docker://google/deepvariant:{config['DEEPVARIANT_VERSION']}"
    params:
        vsc_min_fraction_indels="0.12",
        pileup_image_width=199,
        shard='{shard}',
        examples=f"batches/{batch}/{{sample}}/deepvariant/examples/examples.tfrecord@{config['N_SHARDS']}.gz",
        gvcf=f"batches/{batch}/{{sample}}/deepvariant/examples/gvcf.tfrecord@{config['N_SHARDS']}.gz",
    message:
        "DeepVariant make_examples {wildcards.shard} for {input.bam}."
    shell:
        """
        sleep 180; (/opt/deepvariant/bin/make_examples \
            --add_hp_channel \
            --alt_aligned_pileup=diff_channels \
            --min_mapping_quality=1 \
            --parse_sam_aux_fields \
            --partition_size=25000 \
            --max_reads_per_partition=600 \
            --phase_reads \
            --pileup_image_width {params.pileup_image_width} \
            --norealign_reads \
            --sort_by_haplotypes \
            --track_ref_reads \
            --vsc_min_fraction_indels {params.vsc_min_fraction_indels} \
            --mode calling \
            --ref {input.reference} \
            --reads {input.bam} \
            --examples {params.examples} \
            --gvcf {params.gvcf} \
            --task {params.shard}) > {log} 2>&1
        """

```
Error:

```
2023-07-12 15:19:55.926661: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI De>
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-12 15:19:59.038994: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.6  SO:>
2023-07-12 15:19:59.039047: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag BC: in RG line, ignoring: @RG       ID:d98f52ac>
2023-07-12 15:19:59.039065: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag CM: in RG line, ignoring: @RG       ID:d98f52ac>
I0712 15:19:59.039340 140472429422400 genomics_reader.py:222] Reading batches/Test349/D18757/aligned/D18757.hs37d5.bam with NativeS>
I0712 15:19:59.044630 140472429422400 make_examples_core.py:257] Task 32/96: Preparing inputs
2023-07-12 15:19:59.049074: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.6  SO:>
2023-07-12 15:19:59.049123: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag BC: in RG line, ignoring: @RG       ID:d98f52ac>
2023-07-12 15:19:59.049140: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag CM: in RG line, ignoring: @RG       ID:d98f52ac>
I0712 15:19:59.049325 140472429422400 genomics_reader.py:222] Reading batches/Test349/D18757/aligned/D18757.hs37d5.bam with NativeS>
I0712 15:19:59.059888 140472429422400 make_examples_core.py:257] Task 32/96: Common contigs are ['1', '2', '3', '4', '5', '6', '7',>
I0712 15:19:59.247122 140472429422400 make_examples_core.py:257] Task 32/96: Starting from v0.9.0, --use_ref_for_cram is default to>
2023-07-12 15:19:59.247444: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
2023-07-12 15:19:59.364871: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.6  SO:>
2023-07-12 15:19:59.364924: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag BC: in RG line, ignoring: @RG       ID:d98f52ac>
2023-07-12 15:19:59.364944: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag CM: in RG line, ignoring: @RG       ID:d98f52ac>
I0712 15:19:59.365195 140472429422400 genomics_reader.py:222] Reading batches/Test349/D18757/aligned/D18757.hs37d5.bam with NativeS>
2023-07-12 15:19:59.535088: W third_party/nucleus/io/sam_reader.cc:131] Unknown tag pb: in header line, ignoring: @HD   VN:1.6  SO:>
2023-07-12 15:19:59.535146: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag BC: in RG line, ignoring: @RG       ID:d98f52ac>
2023-07-12 15:19:59.535166: W third_party/nucleus/io/sam_reader.cc:174] Unknown tag CM: in RG line, ignoring: @RG       ID:d98f52ac>
I0712 15:19:59.535452 140472429422400 genomics_reader.py:222] Reading batches/Test349/D18757/aligned/D18757.hs37d5.bam with NativeS>
I0712 15:19:59.536432 140472429422400 make_examples_core.py:257] Task 32/96: Writing gvcf records to batches/Test349/D18757/deepvar>
I0712 15:19:59.536834 140472429422400 make_examples_core.py:257] Task 32/96: Writing examples to batches/Test349/D18757/deepvariant>
I0712 15:19:59.536924 140472429422400 make_examples_core.py:257] Task 32/96: Overhead for preparing inputs: 0 seconds
2023-07-12 15:19:59.545470: W ./third_party/nucleus/util/proto_clif_converter.h:75] Failed to cast type N6google8protobuf14DynamicM>
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 186, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2183, in make_example>
    runtimes) = region_processor.process(region)
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1285, in process
    sample_reads = self.region_reads_norealign(
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1381, in region_reads>
    reads = utils.reservoir_sample(reads,
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/third_party/nucleus/util/utils.py", line 117, in reservoir_sam>
    for i, item in enumerate(iterable):
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 82, in __next__
    record, not_done = self._raw_next()
  File "/tmp/Bazel.runfiles_ch76vyw0/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 141, in _raw_ne>
    not_done = self._cc_iterable.PythonNext(record)
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed
```

**Comment by pichuan** [comment] 2023-07-13 16:06
Hi @Sami-St ,
This is usually something to do with some underlying software version not matching. 

A few suggestions you can try:
* https://github.com/google/deepvariant/issues/580#issuecomment-1304902858
* https://github.com/google/deepvariant/issues/559#issuecomment-1230609842

And, Docker would be usually easier than Singularity. But if you can't use Docker, maybe consider trying udocker. I haven't personally tried it, but here is some information:
https://github.com/google/deepvariant/issues/669#issuecomment-1603444351

If none of these work, let us know and we can ask a few questions to check your environment a bit more (and see how we can reproduce the issue to debug)

**Comment by pgrosu** [comment] 2023-07-13 16:07
Hi @Sami-St,

It works for me if I replace the beginning of the `shell` field of the Snakemake file with the following -- the input and output mapping would need to be updated based on your directory setup:

```
docker run \
            -v "/input_files/input":"/input" \
            -v "/output_files/output":"/output" \
            google/deepvariant:1.5.0 \
            /opt/deepvariant/bin/make_examples \
            ...
```

This would be a first step to test before generalizing the file.

Does this also work for you?

Thanks,
Paul

**Comment by pgrosu** [comment] 2023-07-13 23:18
Hi @Sami-St,

If you're really keen on using Singularity, then you can add the following two lines to your `Snakefile`:
```
    threads: 1
    singularity: "/location_of_your_sif_file/deepvariant_1.5.0.sif"
```

And then launch it from the command-line with the following to ensure that you map (bind) shared folders within the container:

```
snakemake -c 1 --use-singularity --singularity-args "--bind /folder_to_share_with_singularity"
```

It might be better if you use `/opt/deepvariant/bin/run_deepvariant` instead of `make_examples` $`-`$ unless you really know what your are doing $`-`$ as it performs the proper setup for you.

Hope it helps,
~p

**Comment by Sami-St** [comment] 2023-07-14 10:37
Hey @pichuan, @pgrosu 
thx for the quick reply's :)  i tested your first idea paul still had the same issue sadly, but the solution from issue 559 seems to be working (i dont understand why so but thats another problem) since the workflow is still running so i cant say for sure but it makes the tfrecords what didnt happend the last few time
![image](https://github.com/google/deepvariant/assets/138118818/14c3b254-ec78-468c-9a2f-301443bc3a5b)

I will update when the Workflow is done 

Best regards 
Sami

**Comment by pgrosu** [comment] 2023-07-14 15:31
Hi Sami,

That's great news!  Yes, example tfrecords is what you want -- this creates the variant candidates with the accompanying images.  Whatever gets you to the right result is a good solution, and it's a team effort to quickly get you there.  Understanding what exactly is being -- or not being created -- and why is just as important, so you have full insight of the steps of the experiment.  Just from your setup I can infer you are probably running data from a PacBio sequencer.  You can go really go down some nice rabbit holes with DeepVariant, if you really want to understand the process.  The models for different types of sequencers where optimized with specific parameters in mind -- some more flexible than others.  The `make_examples` step generates the right image configurations for those, or you can rely on `run_deepvariant` to do that for you -- ideally all your parameters were properly interpreted in Python.  Though the models can at times be resilient under some data conditions, you want to provide the right data to the correct model to be sure your results are correctly interpreted as they were naturally optimized under those conditions :)

Hope it helps,
Paul

**Comment by pichuan** [comment] 2023-07-15 05:54
Glad to hear the problem was solved. I'll close this issue now. Thanks!

**Closed by pichuan** 2023-07-15 05:54 UTC
