### ISSUE TITLE
Homozygous GT value while IGV shows otherwise

### ISSUE THREAD

**Issue by asalimih** [google/deepvariant#824] opened 2024-05-24 16:54 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:
Yes
**Describe the issue:**
Although some variants are clearly heterozygous in IGV, deepvariant GT shows a homozygous genotype.

**Setup**
  - Operating system: linux
  - DeepVariant version: 1.6.1
  - Installation method : Docker
  - Type of data: illumina, WES, hg38

**Steps to reproduce:**
```
docker run --rm -i \
        -v ${ref_dir}:/opt/ref \
        -v ${kit_dir}:/opt/kit \
        -v ${input_dir}:/opt/sample \
        ${deepvariant_docker} \
                /opt/deepvariant/bin/run_deepvariant \
                        --model_type=WES \
                        --ref="/opt/ref/${ref_fasta}" \
                        --reads="/opt/sample/${input_bam_file}" \
                        --regions="/opt/kit/${kit_bed_file}" \
                        --output_vcf="/opt/sample/${input_bam_file/.bam/.dv.vcf}" \
                        --num_shards="${threads}"
```

Here are 5 selected variants called by 5 different versions of deepvariant:
```
v0.10.0 chr12   11353713        .       T       C       57.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:54:43:27,15:0.348837:57,0,55
v1.1.0  chr12   11353713        .       T       C       36.6    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:34:44:28,15:0.340909:36,0,38
v1.4.0  chr12   11353713        .       T       C       23.3    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:21:44:28,15:0.340909:23,0,25
v1.5.0  chr12   11353713        .       T       C       24.3    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:17:44:28,15:0.340909:24,0,17
v1.6.1  chr12   11353713        .       T       C       24.6    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:5:44:28,15:0.340909:22,3,0
-----------------------------
v0.10.0 chr3    195779035       .       G       A       3.9     PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:4:33:24,8:0.242424:1,0,38
v1.1.0  chr3    195779035       .       G       A       0       RefCall .       GT:GQ:DP:AD:VAF:PL      0/0:41:33:24,8:0.242424:0,43,45
v1.4.0  chr3    195779035       .       G       A       0       RefCall .       GT:GQ:DP:AD:VAF:PL      0/0:23:33:24,8:0.242424:0,32,22
v1.5.0  chr3    195779035       .       G       A       0.1     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:16:33:24,8:0.242424:0,26,16
v1.6.1  chr3    195779035       .       G       A       13.7    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:14:33:24,8:0.242424:13,28,0
-----------------------------
v0.10.0 chr6    159711482       .       C       T       46.5    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:36:70:38,32:0.457143:46,0,36
v1.1.0  chr6    159711482       .       C       T       6.9     PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:7:80:46,34:0.425:5,0,20
v1.4.0  chr6    159711482       .       C       T       1.8     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:5:80:46,34:0.425:0,3,9
v1.5.0  chr6    159711482       .       C       T       2.3     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:4:80:46,34:0.425:0,2,8
v1.6.1  chr6    159711482       .       C       T       9.9     PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:3:80:46,34:0.425:6,0,0
-----------------------------
v0.10.0 chr14   106592660       .       G       A       64.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:59:93:38,55:0.591398:64,0,60
v1.1.0  chr14   106592660       .       G       A       30.5    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:8:95:38,57:0.6:29,6,0
v1.4.0  chr14   106592660       .       G       A       4.6     PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:3:95:38,57:0.6:1,0,5
v1.5.0  chr14   106592660       .       G       A       0       RefCall .       GT:GQ:DP:AD:VAF:PL      0/0:43:95:38,57:0.6:0,44,48
v1.6.1  chr14   106592660       .       G       A       23.7    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:5:95:38,57:0.6:22,3,0
-----------------------------
v0.10.0 chr1    1668449 .       A       G       47.2    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:45:158:71,87:0.550633:47,0,49
v1.1.0  chr1    1668449 .       A       G       23.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:7:164:75,89:0.542683:22,0,5
v1.4.0  chr1    1668449 .       A       G       40      PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:32:164:75,89:0.542683:40,32,0
v1.5.0  chr1    1668449 .       A       G       41.9    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:31:164:75,89:0.542683:41,31,0
v1.6.1  chr1    1668449 .       A       G       43.7    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:29:164:75,89:0.542683:43,28,0
```
As you can see specially in 1.6.1 the genotype is GT:1/1 while earlier versions were GT:0/1

**Comment by asalimih** [comment] 2024-05-24 17:43
![chr1-1668449-A-G](https://github.com/google/deepvariant/assets/10653739/fe1c3aa0-7094-4280-aa83-27d7e64d9af6)
![chr3-195779035-G-A](https://github.com/google/deepvariant/assets/10653739/ed6748a0-a11d-4136-b882-b88feaebcf15)
![chr6-159711482-C-T](https://github.com/google/deepvariant/assets/10653739/d7303506-dfec-4d4c-9882-ecadd4e80df9)
![chr12-11353713-T-C](https://github.com/google/deepvariant/assets/10653739/2d096c58-9f4b-4c88-bbc2-9274fe299b80)
![chr14-106592660-G-A](https://github.com/google/deepvariant/assets/10653739/999189a1-5099-4f9e-844d-0856558a0c50)

**Comment by pichuan** [comment] 2024-05-24 21:24
Hi @asalimih ,
For WES, DeepVariant runs a realignment step.

You can read this section about how realignment works: https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work

To understand your cases better, it'll be useful to generate the realigned reads in the region, which might explain why DeepVariant makes the call differently.

You can take a look at https://github.com/google/deepvariant/issues/691#issuecomment-2014404465 for a more detailed example.

Once you generate an example, please share the realigned reads in an IGV and we can check what it looks like? Thank you!

**Comment by asalimih** [comment] 2024-05-24 22:53
> Hi @asalimih , For WES, DeepVariant runs a realignment step.
> 
> You can read this section about how realignment works: https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work
> 
> To understand your cases better, it'll be useful to generate the realigned reads in the region, which might explain why DeepVariant makes the call differently.
> 
> You can take a look at [#691 (comment)](https://github.com/google/deepvariant/issues/691#issuecomment-2014404465) for a more detailed example.
> 
> Once you generate an example, please share the realigned reads in an IGV and we can check what it looks like? Thank you!

@pichuan 
Thanks for the reply. here is the realigned bam in IGV for chr1-1668449-A-G:
![realigned-chr1-1668449-A-G](https://github.com/google/deepvariant/assets/10653739/f0ec5545-43f8-4d79-bea9-bfccb2576569)
The read counts matches what the AD field says in the vcf. however the GT value is 1/1 !

**Comment by kishwarshafin** [comment] 2024-05-24 23:12
Hi @asalimih ,

can you downsample your bam for this specific variant and run it again?

```bash
samtools view -s 0.5 -b -@16 YOU_BAM.bam > YOUR_BAM.downsampled.bam
```
And run it one more time to see if this specifically has a different genotype?

**Comment by asalimih** [comment] 2024-05-24 23:22
> Hi @asalimih ,
> 
> can you downsample your bam for this specific variant and run it again?
> 
> ```shell
> samtools view -s 0.5 -b -@16 YOU_BAM.bam > YOUR_BAM.downsampled.bam
> ```
> 
> And run it one more time to see if this specifically has a different genotype?

sure, no change in GT (using v1.6.1):
```
chr1    1668449 .       A       G       42.1    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:27:77:36,41:0.532468:42,26,0
```
I tried with `samtools view -s 0.25` too:
```
chr1    1668449 .       A       G       35.5    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:16:44:22,22:0.5:35,16,0
```

**Comment by asalimih** [comment] 2024-05-26 10:58
@kishwarshafin @pichuan 
I can provide the bam file for some of the variants if you give me an email. I would really appreciate any help

**Comment by pichuan** [comment] 2024-05-26 16:11
Hi @asalimih ,
You can send to pichuan@google.com. Please start with a small BAM file and the command where you can reproduce the call on that BAM file.

**Comment by asalimih** [comment] 2024-05-26 17:33
Thank you @pichuan, I sent the bam file and commands to your email.

**Comment by pichuan** [comment] 2024-07-18 05:42
I'll close this bug for now. Later on I can plan to post a summarized update.

**Closed by pichuan** 2024-07-18 05:42 UTC
