### ISSUE TITLE
Compatibility of DeepSomatic Tumor-Only Mode for Short-Read RNA-Seq without Control Sample

### ISSUE THREAD

**Issue by Yousuk-Song** [google/deepvariant#884] opened 2024-09-13 04:50 UTC
Hello,

Thank you for developing those fancy variant callers.

We conducted short-read RNA sequencing, and since we do not have a control sample, we are planning to call variants using the DeepSomatic tumor-only mode. However, the tumor-only mode is only supported for Illumina WGS, PacBio, and ONT, and not for WES. Would it be acceptable to apply the WGS mode to our sample? Additionally, are there any significant differences in the algorithms or methods between WGS and WES for variant calling, and would this lead to meaningful differences in the results?

Also, does setting variant call region (chr2:????-???) makes change in mutation call result?

Many thanks,
Song

**Comment by kishwarshafin** [comment] 2024-09-13 21:18
Hi, 

This is duplicate of https://github.com/google/deepsomatic/issues/22. I will give an update there and close this issue as this is unrelated to DeepVariant.

**Closed by kishwarshafin** 2024-09-13 21:18 UTC
