### ISSUE TITLE
can't open bam file

### ISSUE THREAD

**Issue by BIjoy92** [google/deepvariant#337] opened 2020-08-24 08:27 UTC
Hi I want to run DeepVariant but i faced an error 

**Describe the issue:**
`#!/bin/bash
BIN_VERSION="0.10.0"
N_SHARDS="4"
BASE="/tera/home/phswin92/WGS/Variant_Call/DeepVariant"
INPUT_DIR="$BASE/input"
mkdir $BASE/output
OUTPUT_DIR="$BASE/output"

docker run \
-v "${INPUT_DIR}":"/input" \
-v "${OUTPUT_DIR}:/output" \
gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=$INPUT_DIR/GRCh38_full_analysis_set_plus_decoy_hla.fa \
--reads=$INPUT_DIR/$2_Markdup_sort.bam \
--output_vcf=$OUTPUT_DIR/$1_$2_Deepvariant.output.vcf.gz \
--output_gvcf=$OUTPUT_DIR/$1_$2_Deepvariant.output.g.vcf.gz \
--num_shards=$N_SHARDS
`
this is my code

![image](https://user-images.githubusercontent.com/68986997/91021146-4f355200-e62e-11ea-96bd-40bbe6a53c94.png)
and this is my file in 'input' folder

error
`***** Running the command:*****
time seq 0 3 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/GRCh38_full_analysis_set_plus_decoy_hla.fa" --reads "/tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam" --examples "/tmp/tmpwgmyf_jr/make_examples.tfrecord@4.gz" --gvcf "/tmp/tmpwgmyf_jr/gvcf.tfrecord@4.gz" --task {}

I0824 08:09:22.428504 140501281453824 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1510, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1437, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 397, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_ujzt8s5j/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
I0824 08:09:22.445197 140710897501952 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1510, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1437, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 397, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_lqn1zdad/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
I0824 08:09:22.428504 139901934769920 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1510, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1437, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 397, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_x_9sixwe/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
I0824 08:09:22.445198 139768452732672 make_examples.py:386] ReadRequirements are: min_mapping_quality: 10
min_base_quality: 10
min_base_quality_mode: ENFORCED_BY_CLIENT

[E::hts_open_format] Failed to open file /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1510, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1437, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 397, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_paxqrw22/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/GRCh38_full_analysis_set_plus_decoy_hla.fa --reads /tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam --examples /tmp/tmpwgmyf_jr/make_examples.tfrecord@4.gz --gvcf /tmp/tmpwgmyf_jr/gvcf.tfrecord@4.gz --task 3

real	0m2.438s
user	0m2.289s
sys	0m3.833s
I0824 08:09:22.720529 140047104423680 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 3 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/GRCh38_full_analysis_set_plus_decoy_hla.fa" --reads "/tera/home/phswin92/WGS/Variant_Call/DeepVariant/input/BWA_Markdup_sort.bam" --examples "/tmp/tmpwgmyf_jr/make_examples.tfrecord@4.gz" --gvcf "/tmp/tmpwgmyf_jr/gvcf.tfrecord@4.gz" --task {}' returned non-zero exit status 1.
Done...
`
this is my error when I run deepvariant script

  - Operating system: CentOS
  - DeepVariant version: 0.10.0
  - Installation method (Docker, built from source, etc.): Docker

how can I solve this problem

**Comment by MariaNattestad** [comment] 2020-08-24 15:56
Hi @BIjoy92 

The problem is that the paths are different inside the docker container than outside. The part of the command that says `-v "${INPUT_DIR}":"/input"` mounts the outside $INPUT_DIR/ to the inside /input/, which means the reads can be accessed at the following path: `--reads=/input/BWA_Markdup_sort.bam`.

The same change is needed for all your inputs and outputs, e.g.  `/output/`.

See the Quick Start for an example: https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
I also noticed you're using the gcr.io docker version, which works fine, but all our newer documentation uses `google/deepvariant:"${BIN_VERSION}"`, so I just want to check: what documentation were you using for reference?

Thanks!
Maria

**Comment by BIjoy92** [comment] 2020-08-25 01:16
Hi Maria

Thank you for your help.
I appreciate your prompt reply.

Thanks
BIjoy92

**Comment by MariaNattestad** [comment] 2020-08-25 18:28
You're very welcome! I'll close this issue.

**Closed by MariaNattestad** 2020-08-25 18:28 UTC
