### ISSUE TITLE
failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. 

### ISSUE THREAD

**Issue by wenweiliang** [google/deepvariant#70] opened 2018-05-04 16:24 UTC
Hi, 
I have no problem with running deepvariant on example BAM on google cloud, but the following error pops out when I switch to my BAM.

```
[05/03/2018 23:30:18 INFO discovery.py] URL being requested: GET https://genomics.googleapis.com/v1alpha2/operations?filter=projectId+%3D+isb-cgc-06-0004+AND+labels.job-id+%3D+call-varia--root--180503-233007-45&alt=json&pageSize=256
  call-varia--root--180503-233007-45: FAILURE
[u"Error in job call-varia--root--180503-233007-45 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]
[05/03/2018 23:30:18 ERROR gcp_deepvariant_runner.py] Job failed with error [[u"Error in job call-varia--root--180503-233007-45 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]]. Job args: ['--project', 'isb-cgc-XX-XXXX', '--logging', 'gs://XXXXX/wliang_deepvariant/XXXXX.stage/logs', '--boot-disk-size', '50', '--zones', 'us-west1-b', 'us-east1-d', '--wait', '--name', 'call_variants', '--image', 'gcr.io/deepvariant-docker/deepvariant_gpu:0.6.0', '--input-recursive', 'EXAMPLES=gs://XXXXX/wliang_deepvariant/XXXXX.stage/examples/15', 'MODEL=gs://deepvariant/models/DeepVariant/0.6.0/DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard', '--output-recursive', 'CALLED_VARIANTS=gs://XXXXX/wliang_deepvariant/XXXXX.stage/called_variants', '--min-cores', '8', '--min-ram', '60', '--disk-size', '50', '--env', 'SHARDS=512', '--env', 'SHARD_START_INDEX=480', '--env', 'SHARD_END_INDEX=511', '--env', 'CONCURRENT_JOBS=1', '--command', '\ncd /opt/deepvariant/bin/ && \\\nseq -f "%05g" "${SHARD_START_INDEX}" "${SHARD_END_INDEX}" | \\\nparallel --jobs "${CONCURRENT_JOBS}" --halt 2 \\\n./call_variants \\\n  --examples "${EXAMPLES}"/examples_output.tfrecord-{}-of-"$(printf "%05d" "${SHARDS}")".gz \\\n  --outfile "${CALLED_VARIANTS}"/call_variants_output.tfrecord-{}-of-"$(printf "%05d" "${SHARDS}")".gz \\\n  --checkpoint "${MODEL}"/model.ckpt\n', '--accelerator-type', 'nvidia-tesla-k80', '--accelerator-count', '1']
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 655, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 642, in run
    _run_call_variants(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 322, in _run_call_variants
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
RuntimeError: Job failed with error [[u"Error in job call-varia--root--180503-232937-37 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]].
 (exit status 1)
```

It seems like google api can't insert instance in the make example steps. 
Any helps would be appreciated. Thanks.

**Comment by pichuan** [comment] 2018-05-04 20:52
Hi, thanks for reporting. We're aware of this issue and a fix on the Cloud side will soon be out.
We'll let you know when the fix is out. Meanwhile, a workaround is to explicitly set "--call_variants_cores_per_worker 8".

**Comment by wenweiliang** [comment] 2018-05-05 22:13
Hi Pi-Chuan,
Thanks. I set `--call_variants_cores_per_worker 8` and new error pops out. It would be great if guys can take a look of it as well.
```
make-examp--root--180505-205721-02: FAILURE
[u'Error in job make-examp--root--180505-205721-02 - code 5: 9: Failed to localize files: failed to make local directory for /mnt/datadisk/input/gs/xxxxx/reference/Homo_sapiens_assembly19.fasta: mkdir /mnt/datadisk/input/gs/xxxxx: no space left on device']
[05/05/2018 21:27:38 ERROR gcp_deepvariant_runner.py] Job failed with error [[u'Error in job make-examp--root--180505-205721-02 - code 5: 9: Failed to localize files: failed to make local directory for /mnt/datadisk/input/gs/xxxxx/reference/Homo_sapiens_assembly19.fasta: mkdir /mnt/datadisk/input/gs/xxxxx: no space left on device']]. Job args: ['--project', 'isb-cgc-06-0004', '--logging', 'gs://xxxxx/wliang_deepvariant/ooooo.stage/logs', '--boot-disk-size', '50', '--zones', 'us-west1-b', 'us-east1-d', '--wait', '--name', 'make_examples', '--image', 'gcr.io/deepvariant-docker/deepvariant:0.6.0', '--input', 'INPUT_BAM=gs://yyyyy.bam', 'INPUT_BAI=gs://yyyyy.bam.bai', 'INPUT_REF=gs://xxxxx/reference/Homo_sapiens_assembly19.fasta', 'INPUT_REF_FAI=gs://xxxxx/reference/Homo_sapiens_assembly19.fasta.fai', '--output-recursive', 'EXAMPLES=gs://xxxxx/wliang_deepvariant/ooooo.stage/examples/0', '--min-cores', '8', '--min-ram', '30', '--disk-size', '50', '--env', 'SHARDS=512', '--env', 'SHARD_START_INDEX=0', '--env', 'SHARD_END_INDEX=511', '--command', '\ncd /opt/deepvariant/bin/ && \\\nseq "${SHARD_START_INDEX}" "${SHARD_END_INDEX}" | parallel --halt 2 \\\n  ./make_examples \\\n    --mode calling \\\n    --examples "${EXAMPLES}"/examples_output.tfrecord@"${SHARDS}".gz \\\n    --reads "${INPUT_BAM}" \\\n    --ref "${INPUT_REF}" \\\n    --task {} \\\n    \n']
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 655, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 638, in run
    _run_make_examples(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 266, in _run_make_examples
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
RuntimeError: Job failed with error [[u'Error in job make-examp--root--180505-205721-02 - code 5: 9: Failed to localize files: failed to make local directory for /mnt/datadisk/input/gs/xxxxx/reference/Homo_sapiens_assembly19.fasta: mkdir /mnt/datadisk/input/gs/xxxxxx: no space left on device']].
 (exit status 1)
```

**Comment by nmousavi** [comment] 2018-05-07 19:33
The issue is fixed with 0.6.1 release of docker images. Please update image version to

`IMAGE_VERSION=0.6.1`

See https://cloud.google.com/genomics/deepvariant for more info.

**Closed** 2018-05-07 19:35 UTC

**Comment by wenweiliang** [comment] 2018-05-08 22:35
Hi Pi-Chuan, 
I used 0.6.1 docker images and also set `--call_variants_cores_per_worker 8`, but same error pops out.

```
  call-varia--root--180508-211940-52: FAILURE
[u"Error in job call-varia--root--180508-211940-52 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]
[05/08/2018 21:19:51 ERROR gcp_deepvariant_runner.py] Job failed with error [[u"Error in job call-varia--root--180508-211940-52 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]]. Job args: ['--project', 'isb-cgc-06-0004', '--logging', 'gs://WWWWW/wliang_deepvariant/XXXXX.stage/logs', '--boot-disk-size', '50', '--zones', 'us-west1-b', 'us-east1-d', '--wait', '--name', 'call_variants', '--image', 'gcr.io/deepvariant-docker/deepvariant_gpu:0.6.1', '--input-recursive', 'EXAMPLES=gs://WWWWW/wliang_deepvariant/XXXXX.stage/examples/15', 'MODEL=gs://deepvariant/models/DeepVariant/0.6.0/DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard', '--output-recursive', 'CALLED_VARIANTS=gs://WWWWW/wliang_deepvariant/XXXXX.stage/called_variants', '--min-cores', '8', '--min-ram', '60', '--disk-size', '50', '--env', 'SHARDS=512', '--env', 'SHARD_START_INDEX=480', '--env', 'SHARD_END_INDEX=511', '--env', 'CONCURRENT_JOBS=1', '--command', '\ncd /opt/deepvariant/bin/ && \\\nseq -f "%05g" "${SHARD_START_INDEX}" "${SHARD_END_INDEX}" | \\\nparallel --jobs "${CONCURRENT_JOBS}" --halt 2 \\\n./call_variants \\\n  --examples "${EXAMPLES}"/examples_output.tfrecord-{}-of-"$(printf "%05d" "${SHARDS}")".gz \\\n  --outfile "${CALLED_VARIANTS}"/call_variants_output.tfrecord-{}-of-"$(printf "%05d" "${SHARDS}")".gz \\\n  --checkpoint "${MODEL}"/model.ckpt\n', '--accelerator-type', 'nvidia-tesla-k80', '--accelerator-count', '1']
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 655, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 642, in run
    _run_call_variants(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 322, in _run_call_variants
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
RuntimeError: Job failed with error [[u"Error in job call-varia--root--180508-211910-49 - code 2: failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.guestAccelerators[0].acceleratorCount': '1'. At most 8 vCPUs can be used along with 1 accelerator cards in an instance., invalid"]].
 (exit status 1)
```

Would you mind taking a look of this? Thanks!

**Comment by nmousavi** [comment] 2018-05-08 23:18
Please share the full runner log, as well as config (YAML) file used.

**Comment by wenweiliang** [comment] 2018-05-09 02:57
The following are full runner log. 
[ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stderr.log](https://github.com/google/deepvariant/files/1986206/ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stderr.log)
[ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stdout.log](https://github.com/google/deepvariant/files/1986207/ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stdout.log)
[ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl.log](https://github.com/google/deepvariant/files/1986208/ENHvj4m0LBjriPO-qfLP3oABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl.log)

Please find the yaml file and the runner bash script here: https://github.com/ding-lab/RegulatoryGermline/tree/master/deepvariant.

**Comment by nmousavi** [comment] 2018-05-09 14:03
Could you verify setting call_variants_ram_per_worker_gb to 30 solves the issue?

**Comment by wenweiliang** [comment] 2018-05-10 20:57
Hi Nima, 
I set the `--call_variants_ram_per_worker_gb 30`, and it seems like resource is not available. 
```
  call-varia--root--180510-193828-03: SUCCESS
Traceback (most recent call last):
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 655, in <module>
    run()
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 642, in run
    _run_call_variants(pipeline_args)
  File "/opt/deepvariant_runner/src/gcp_deepvariant_runner.py", line 322, in _run_call_variants
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
RuntimeError: Job failed with error [[u"Error in job call-varia--root--180510-193818-02 - code 2: failed to insert instance: googleapi: Error 404: The resource 'projects/isb-cgc-06-0004/zones/us-west1-a/acceleratorTypes/nvidia-tesla-k80' was not found, notFound"]].
 (exit status 1)
```

Here are the full runner log. You can find out the yam file in the same repo.
[ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stderr.log](https://github.com/google/deepvariant/files/1993190/ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stderr.log)
[ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stdout.log](https://github.com/google/deepvariant/files/1993191/ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl-stdout.log)
[ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl.log](https://github.com/google/deepvariant/files/1993192/ELj2mta0LBjZy6CkirjPx8ABIOjMyffEGCoPcHJvZHVjdGlvblF1ZXVl.log)

**Comment by nmousavi** [comment] 2018-05-10 21:02
`us-west1-a` doesn't have GPU VM. Try `us-west1-b` (this is what we recoomended in the [documentation](https://cloud.google.com/genomics/deepvariant)). See following page for the list of zones with GPU

https://cloud.google.com/compute/docs/regions-zones/

**Comment by wenweiliang** [comment] 2018-05-10 21:03
I also try the us-west1-b but the quota is not enough. How can I appropriately request the data?

**Comment by nmousavi** [comment] 2018-05-10 21:10
Here https://cloud.google.com/compute/quotas#request_quotas
