### ISSUE TITLE
Call variants from RNAseq data

### ISSUE THREAD

**Issue by FarmOmics** [google/deepvariant#572] opened 2022-10-11 18:14 UTC
I am wondering if deepvariant can be applied in RNAseq SNP calling?

**Comment by danielecook** [comment] 2022-10-11 18:29
@FarmOmics we are planning on a release very soon that will enable RNA-seq variant calling. I can ping you on this issue once that release is out.

**Comment by danielecook** [comment] 2022-10-17 02:08
@FarmOmics we have released an RNA-seq model and case study. Let me know if you have any questions.

https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-rnaseq-case-study.md

**Comment by FarmOmics** [comment] 2022-10-17 18:41
In your documentation, the model option "--model_type=WES" is WES. Whether this means RNASeq SNP calling uses same model with WES data? What preprocessing of RNASeq data should be done? In GATK best practice, SplitNCigarReads is required, should it also be done?

**Comment by pichuan** [comment] 2022-10-17 19:01
Hi @FarmOmics ,

The `--model_type=WES` is a shorthand specifically for the wrapper script "run_deepvariant.py". Specifically here
https://github.com/google/deepvariant/blob/r1.4/scripts/run_deepvariant.py#L236-L239

In https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-rnaseq-case-study.md , you'll see that the RNAseq run actually overwrites these arguments:
with:
```
    --make_examples_extra_args="split_skip_reads=true,channels=''" \
```

which basically means: If you run `make_examples` on your own (without using the wrapper script "run_deepvariant.py"), you'll want to provide `--split_skip_reads=true`, but not providing `channels`.

And we also provided RNAseq model with:
```
    --customized_model=model/model.ckpt \
```

So, https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-rnaseq-case-study.md isn't actually using WES model at all. (In the future we'll think about how to make this less confusing.)

In terms of preprocessing for RNAseq data, the important flag to add is `--split_skip_reads` to make_examples.

Let me know if I can help clarifying with anything else.

**Comment by pichuan** [comment] 2022-10-20 00:48
Hi @FarmOmics ,
I'll close this issue. We would love to hear your feedback about the RNAseq caller. Please don't hesitate to reach out again if you have more questions or feedback.

**Closed by pichuan** 2022-10-20 00:48 UTC

**Comment by ne1al** [comment] 2022-11-07 19:35
@FarmOmics did you manage to run the case study here? Because my team is having problems that seem unresolved. Kindly share your experience in running it

**Comment by pichuan** [comment] 2022-11-07 22:32
@ne1al Can you share what issues your team is having? Feel free to open another issue. Or, if the issue is the same as here, we can reopen this one too.

**Comment by ne1al** [comment] 2022-11-09 07:11
@pichuan sure. We opened a new issue and we are trying to follow up here
[https://github.com/google/deepvariant/issues/581](url)
