### ISSUE TITLE
AttributeError: 'IntervalTree' object has no attribute 'merge_overlaps'

### ISSUE THREAD

**Issue by internalsensor** [google/deepvariant#155] opened 2019-02-17 20:27 UTC
Hi Deepvariant developer:

I paste the error report when I run "make_examples" for testing dataset:

python /opt/deepvariant/bin/make_examples.zip \
 --mode calling \
 --ref /usit/abel/u1/senz/DeepVariant0.7.2/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta \
 --reads /usit/abel/u1/senz/DeepVariant0.7.2/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam \
 --examples /usit/abel/u1/senz/DeepVariant0.7.2/quickstart_output/examples.tfrecord.gz

2019-02-17 16:15:42.409205: W third_party/nucleus/io/sam_reader.cc:525] Unrecognized SAM header type, ignoring: 
I0217 16:15:42.409567 139914391602944 genomics_reader.py:213] Reading /usit/abel/u1/senz/DeepVariant0.7.2/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0217 16:15:42.417557 139914391602944 make_examples.py:1080] Preparing inputs
2019-02-17 16:15:42.422480: W third_party/nucleus/io/sam_reader.cc:525] Unrecognized SAM header type, ignoring: 
I0217 16:15:42.422776 139914391602944 genomics_reader.py:213] Reading /usit/abel/u1/senz/DeepVariant0.7.2/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0217 16:15:42.424446 139914391602944 make_examples.py:996] Common contigs are [u'chr20']
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1205, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1195, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1081, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 998, in processing_regions_from_options
    options.exclude_calling_regions)
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 583, in build_calling_regions
    regions = ranges.RangeSet.from_contigs(contigs)
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 168, in from_contigs
    contigs)
  File "/tmp/Bazel.runfiles_DVDplM/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 125, in __init__
    tree.merge_overlaps()
AttributeError: 'IntervalTree' object has no attribute 'merge_overlaps'

I attempted to change the python package intervaltree as v2.1.0, but still received such report. Does anybody can help me?

**Comment by pichuan** [comment] 2019-02-17 21:02
Hi @internalsensor ,
can you tell us how you're running DeepVariant?
Is this binaries you built on your own, or pre-built binaries you copied from us, or Docker image?
If it's the first or second, you need to change run-prereq.sh to
```
pip install --user 'intervaltree==2.1.0'
```

This is because intervaltree got upgraded during this time, and we didn't pin it in the last version. We'll plan to fix it in the next release.

**Comment by internalsensor** [comment] 2019-02-17 21:12
I downloaded and ran the pre-built binaries *.zip (DeepVariant v 7.0.2) from GitHub. In fact, I have installed 'intervaltree==2.1.0', but it does not works? Strange.....

**Comment by pgrosu** [comment] 2019-02-18 00:13
My spidey sense is telling me that you have two versions installed.  If you run the following Python commands you can see the search-order of paths to determine if you have another `intervaltree` module installed system-wide, and it prioritizes that one before yours:

```Python
import sys
print(sys.path)
```

The easiest thing is to set the `PYTHONPATH`, or just download the package and untar it in the local deepvariant directory.  Here's more info on the Python's search-order of modules:

https://leemendelowitz.github.io/blog/how-does-python-find-packages.html

Hope it helps,
~p

**Comment by pichuan** [comment] 2019-02-18 00:33
Hi @internalsensor , please see my answer below.
(And, can you give us some feedback on why you don't use the Docker version, but decided to use the prebuilt binaries instead? Thank you!)

===
Hi @internalsensor , 
I think it's likely what @pgrosu said about multiple versions installed. It'll be useful to figure out what actually got used.

I was not able to reproduce the error you found.
In case it's useful, here is what I did to try to reproduce. I used a modified version of the WES script, in which I made sure I pip install a pinned version of intervaltree, and I downloaded the prebuilt binaries instead of rebuilding on my own:

```
git clone https://github.com/google/deepvariant.git
cd deepvariant
wget https://gist.githubusercontent.com/pichuan/5a1216e080ccaf286810af062d6cb7a2/raw/20f6b3e9473b8f2e7d520edace1f2bb7a7231f06/run_wes_case_study_prebuilt_binaries.sh
bash -x run_wes_case_study_prebuilt_binaries.sh
```

This worked with the prebuilt binaries v0.7.2. So I wasn't able to reproduce your error.
You can also use `pip show intervaltree` to double check what pip package you have.

**Comment by pichuan** [comment] 2019-02-25 16:33
Hi @internalsensor,
I am going to close this issue. If you have more questions, please let us know.
In the next version, we'll make sure the pin intervaltree to the right version that goes with the code.

**Closed by pichuan** 2019-02-25 16:33 UTC
