### ISSUE TITLE
Can't run the test data and get `subprocess.CalledProcessError` with status 252

### ISSUE THREAD

**Issue by sh940202123** [google/deepvariant#345] opened 2020-09-09 08:51 UTC
Hi~
I tried to run Deepvariant v1.0.0 by docker image.
But it returned error message when I run test dataset.

Here is the code:

```sh
# BIN_VERSION="1.0.0"
# INPUT_DIR="${PWD}/quickstart-testdata"
# OUTPUT_DIR="${PWD}/quickstart-output"

# ls quickstart-testdata
NA12878_S1.chr20.10_10p1mb.bam                 
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi  
ucsc.hg19.chr20.unittest.fasta.gz.fai
NA12878_S1.chr20.10_10p1mb.bam.bai             
ucsc.hg19.chr20.unittest.fasta                 
ucsc.hg19.chr20.unittest.fasta.gz.gzi
test_nist.b37_chr20_100kbp_at_10mb.bed         
ucsc.hg19.chr20.unittest.fasta.fai
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz      
ucsc.hg19.chr20.unittest.fasta.gz

# /home/d008/data/covid19/deepvarient/test# sudo docker run \
   -v "${INPUT_DIR}":"/input" \
   -v "${OUTPUT_DIR}":"/output" \
   google/deepvariant:"${BIN_VERSION}" \
   /opt/deepvariant/bin/run_deepvariant \
   --model_type=WGS \
   --ref=/input/ucsc.hg19.chr20.unittest.fasta \
   --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
   --regions "chr20:10,000,000-10,010,000" \
   --output_vcf=/output/output.vcf.gz \
   --output_gvcf=/output/output.g.vcf.gz \
   --intermediate_results_dir /output/intermediate_results_dir \
   --num_shards=1 \
```

And here is the error message from docker

```sh
***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

I0907 09:04:08.296450 140053878712064 run_deepvariant.py:273] Re-using the directory for intermediate results in /output/intermediate_results_dir
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real    0m1.182s
user    0m1.087s
sys     0m0.642s
I0907 09:04:09.482760 140053878712064 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}' returned non-zero exit status 252.

```

Here is the supported CPU instructions of host:

```sh
# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 30
model name      : Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
stepping        : 5
microcode       : 0xa
cpu MHz         : 1197.018
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 5851.92
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

I also tried create a env & install on host by `conda install -c bioconda deepvariant`, but it pop-up the same error.
And Deepvariant v0.10.0 also have the same error.

Please kindly give me some advice about this thank you.

Best,
Jerry

**Comment by pichuan** [comment] 2020-09-10 00:14
Hi @sh940202123 ,
Sorry that our error messages are still quite cryptic at this time.

The last traceback is actually not quite as useful. You're seeing it because we uses Python's subprocess.check_call to call each of the commands:
https://github.com/google/deepvariant/blob/7ed651ed54d8563530d58ba80187121337fd10f2/scripts/run_deepvariant.py#L362

Usually, I hope that whatever appeared right before that is useful, though.

For example, if I deliberately deleted the bam file, I got:

```
***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

[E::hts_open_format] Failed to open file "/input/NA12878_S1.chr20.10_10p1mb.bam" : No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2136, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2063, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 427, in default_options
    with sam.SamReader(flags_obj.reads.split(',')[0]) as sam_reader:
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 255, in _native_reader
    return NativeSamReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_1ip32q9b/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 232, in __init__
    use_original_base_quality_scores=use_original_base_quality_scores)
ValueError: Not found: Could not open /input/NA12878_S1.chr20.10_10p1mb.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real    0m3.261s
user    0m5.770s
sys     0m5.974s
I0910 00:06:33.584306 140309422569216 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}' returned non-zero exit status 1.
```

However, in your case, it seems like there's nothing useful in the log.

I think I've heard about similar cases before (where there was no useful error message showing up). I previously wondered if it's possible that `parallel` somehow hid away some message. But I can't immediately think of a reproducible setting that I can debug.

But speaking of "returned non-zero exit status 252", I did a quick search in our GitHub issues and found: https://github.com/google/deepvariant/issues/325
Can you see if this might be relevant to your issue?

If so, I'd still like to find a way to reproduce on my side, so I can see if we can make a more meaningful error message... 🤔

**Comment by sh940202123** [comment] 2020-09-10 02:18
Hi @pichuan ~

Thank you for this quickly reply~

I tried to add `--user root` into docker command like the solved issue #325 
But it still didn't show any additional error message like the issue 
I also check the disk and it is still have about 9 Gb free space.

Here is the code and message output.

```sh
$ BIN_VERSION="1.0.0"
$ sudo docker pull google/deepvariant:"${BIN_VERSION}"
Digest: sha256:6ef8f3b4c4465e41ee7597cd2351a7c44dd8b62a849a47766316507a6234f5f8
Status: Downloaded newer image for google/deepvariant:1.0.0
docker.io/google/deepvariant:1.0.0

$ INPUT_DIR="${PWD}/quickstart-testdata"
$ ls -1 ${INPUT_DIR}
NA12878_S1.chr20.10_10p1mb.bam
NA12878_S1.chr20.10_10p1mb.bam.bai
test_nist.b37_chr20_100kbp_at_10mb.bed
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi
ucsc.hg19.chr20.unittest.fasta
ucsc.hg19.chr20.unittest.fasta.fai
ucsc.hg19.chr20.unittest.fasta.gz
ucsc.hg19.chr20.unittest.fasta.gz.fai
ucsc.hg19.chr20.unittest.fasta.gz.gzi

$ OUTPUT_DIR="${PWD}/quickstart-output"
$ ls ${OUTPUT_DIR}
intermediate_results_dir

$ df -h
檔案系統        容量  已用  可用 已用% 掛載點
udev            7.8G     0  7.8G    0% /dev
tmpfs           1.6G   11M  1.6G    1% /run
/dev/sda1       109G   95G  8.9G   92% /
tmpfs           7.9G  200K  7.9G    1% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
tmpfs           7.9G     0  7.9G    0% /sys/fs/cgroup
/dev/loop1       56M   56M     0  100% /snap/core18/1885
/dev/loop3       55M   55M     0  100% /snap/gtk-common-themes/1502
/dev/loop2      162M  162M     0  100% /snap/gnome-3-28-1804/128
/dev/loop4      161M  161M     0  100% /snap/gnome-3-28-1804/116
/dev/loop0       30M   30M     0  100% /snap/snapd/8790
/dev/loop5       63M   63M     0  100% /snap/gtk-common-themes/1506
/dev/loop6       55M   55M     0  100% /snap/core18/1880
/dev/loop7       30M   30M     0  100% /snap/snapd/8542
/dev/loop8       39M   39M     0  100% /snap/remmina/4309
/dev/loop9       40M   40M     0  100% /snap/remmina/4324
tmpfs           1.6G   40K  1.6G    1% /run/user/108
tmpfs           1.6G   12K  1.6G    1% /run/user/1000

$ sudo docker run \
>   --user root \
>   -v "${INPUT_DIR}":"/input" \
>   -v "${OUTPUT_DIR}":"/output" \
>   google/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \
>   --ref=/input/ucsc.hg19.chr20.unittest.fasta \
>   --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf=/output/output.vcf.gz \
>   --output_gvcf=/output/output.g.vcf.gz \
>   --intermediate_results_dir /output/intermediate_results_dir \
>   --num_shards=1 \
>
I0910 01:14:38.364422 139749579556608 run_deepvariant.py:273] Re-using the directory for intermediate results in /output/intermediate_results_dir

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real    0m1.293s
user    0m1.033s
sys     0m0.705s
I0910 01:14:39.661637 139749579556608 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}' returned non-zero exit status 252.

```

I wonder is there any way to let me get the hidden parallel error message?

Best,
Jerry

**Comment by pichuan** [comment] 2020-09-10 03:02
Can you try running:

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/make_examples \
  --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta \
  --reads /input/NA12878_S1.chr20.10_10p1mb.bam \
  --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz \
  --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz \
  --regions chr20:10,000,000-10,010,000 \
  --task 0
```
directly?

**Comment by sh940202123** [comment] 2020-09-10 03:40
Hi @pichuan ~

I tried the code you provided but it print nothing error.
There is also nothing output file in the output folder.

Here is the code:

```sh
$ sudo docker run \
>   -v "${INPUT_DIR}":"/input" \
>   -v "${OUTPUT_DIR}":"/output" \
>   google/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/make_examples \
>   --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta \
>   --reads /input/NA12878_S1.chr20.10_10p1mb.bam \
>   --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz \
>   --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz \
>   --regions chr20:10,000,000-10,010,000 \
>   --task 0

$ ls
quickstart-output  quickstart-testdata

$ ls quickstart-output/
intermediate_results_dir

```

Best,
Jerry

**Comment by pichuan** [comment] 2020-09-10 03:53
What OS system are you using?
Can you run `uname -a` and let me know what you see?

**Comment by sh940202123** [comment] 2020-09-10 08:38
Hi @pichuan ~

Here is my OS and the kernel info~

```sh
$ uname -a
Linux d008-OptiPlex-980 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by pichuan** [comment] 2020-09-11 00:45
Hi @sh940202123 , it's not obvious to me why this might be the case. It's strange that no error message comes out at all.

Can you try something even simpler, like:
```
sudo docker run google/deepvariant:1.0.0 /opt/deepvariant/bin/make_examples --help
```
And see if the information comes out correctly?

I'll also check with my team member tomorrow to see if anyone has other suggestions.

**Comment by tedyun** [comment] 2020-09-11 01:35
Hi @sh940202123 it seems the CPU on the host `Intel(R) Core(TM) i7 CPU  870  @ 2.93GHz` doesn't support AVX instruction ( https://en.wikipedia.org/wiki/List_of_Intel_Core_i7_microprocessors#%22Lynnfield%22_(45_nm) ), which is required for the TensorFlow release version we use in the docker image. Please see this previous comment https://github.com/google/deepvariant/issues/217#issuecomment-530580878 for more details.

That being said, I do find it strange that it's silently not producing outputs, instead of showing an error message about the unsupported instruction.. Is it possible for you to try the same command in a machine with newer CPU? For Intel CPUs, _Sandy Bridge_  (released in 2011) or later architectures should support AVX. https://en.wikipedia.org/wiki/List_of_Intel_Core_i7_microprocessors#Sandy_Bridge_microarchitecture_(2nd_generation)

**Comment by sh940202123** [comment] 2020-09-11 02:53
Hi @pichuan and @tedyun ~

I run the command which @pichuan provided but it still print nothing on terminal. 
And the docker version of this machine is `Docker version 19.03.3, build a872fc2`.

So I switch to another machine which supported AVX instruction and run the test again by @tedyun 's advice.
Then it run normally and output the files as same as the tutorial.

Here is the environment & the command:

- Host CPU info
```text
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
stepping        : 2
microcode       : 0x43
cpu MHz         : 1199.975
cache size      : 25600 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
bogomips        : 4595.05
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
- OS ,kernel & docker version
```sh
# uname -a
Linux CoreS 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

# docker -v
Docker version 19.03.12, build 48a66213fe
```

- Test run command
```sh
# BIN_VERSION="1.0.0"
# ls -1 ${INPUT_DIR}
NA12878_S1.chr20.10_10p1mb.bam
NA12878_S1.chr20.10_10p1mb.bam.bai
test_nist.b37_chr20_100kbp_at_10mb.bed
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz
test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi
ucsc.hg19.chr20.unittest.fasta
ucsc.hg19.chr20.unittest.fasta.fai
ucsc.hg19.chr20.unittest.fasta.gz
ucsc.hg19.chr20.unittest.fasta.gz.fai
ucsc.hg19.chr20.unittest.fasta.gz.gzi

# docker run \
>   -v "${INPUT_DIR}":"/input" \
>   -v "${OUTPUT_DIR}":"/output" \
>   google/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \
>   --ref=/input/ucsc.hg19.chr20.unittest.fasta \
>   --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf=/output/output.vcf.gz \
>   --output_gvcf=/output/output.g.vcf.gz \
>   --intermediate_results_dir /output/intermediate_results_dir \
>   --num_shards=1 \
>

Status: Downloaded newer image for google/deepvariant:1.0.0
I0911 02:28:36.697342 140021722134272 run_deepvariant.py:269] Creating a directory for intermediate results in /output/intermediate_results_dir

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

I0911 02:28:39.900765 140366075229952 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0911 02:28:39.914417 140366075229952 make_examples.py:587] Preparing inputs
I0911 02:28:39.915202 140366075229952 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0911 02:28:39.916366 140366075229952 make_examples.py:587] Common contigs are ['chr20']
I0911 02:28:39.917786 140366075229952 make_examples.py:587] Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00000-of-00001.gz
I0911 02:28:39.917969 140366075229952 make_examples.py:587] Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00000-of-00001.gz
I0911 02:28:39.918812 140366075229952 make_examples.py:587] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-09-11 02:28:39.919135: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0911 02:28:39.922723 140366075229952 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0911 02:28:39.923217 140366075229952 genomics_reader.py:223] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0911 02:28:40.247040 140366075229952 make_examples.py:587] 6 candidates (6 examples) [0.33s elapsed]
I0911 02:28:41.745102 140366075229952 make_examples.py:587] Found 78 candidate variants
I0911 02:28:41.745359 140366075229952 make_examples.py:587] Created 86 examples

real    0m5.273s
user    0m5.898s
sys     0m3.792s

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --checkpoint "/opt/models/wgs/model.ckpt"

I0911 02:28:44.682443 139937686464256 call_variants.py:335] Shape of input examples: [100, 221, 6]
2020-09-11 02:28:44.695721: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-11 02:28:44.721599: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2297525000 Hz
2020-09-11 02:28:44.724518: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5886480 executing computations on platform Host. Devices:
2020-09-11 02:28:44.724555: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-09-11 02:28:44.727738: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
W0911 02:28:44.755701 139937686464256 estimator.py:1821] Using temporary folder as model directory: /tmp/tmp8bwus8dp
I0911 02:28:44.756375 139937686464256 estimator.py:212] Using config: {'_model_dir': '/tmp/tmp8bwus8dp', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': , '_keep_checkpoint_max': 100000, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4549cfe518>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
I0911 02:28:44.756798 139937686464256 call_variants.py:426] Writing calls to /output/intermediate_results_dir/call_variants_output.tfrecord.gz
W0911 02:28:44.767428 139937686464256 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0911 02:28:44.788271 139937686464256 deprecation.py:323] From /tmp/Bazel.runfiles_z274deps/runfiles/com_google_deepvariant/deepvariant/data_providers.py:375: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
W0911 02:28:44.973487 139937686464256 deprecation.py:323] From /tmp/Bazel.runfiles_z274deps/runfiles/com_google_deepvariant/deepvariant/data_providers.py:381: map_and_batch (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.batch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of using the fused implementation.
I0911 02:28:45.531516 139937686464256 estimator.py:1147] Calling model_fn.
W0911 02:28:45.537137 139937686464256 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
I0911 02:28:50.978360 139937686464256 estimator.py:1149] Done calling model_fn.
I0911 02:28:52.395916 139937686464256 monitored_session.py:240] Graph was finalized.
I0911 02:28:52.397383 139937686464256 saver.py:1284] Restoring parameters from /opt/models/wgs/model.ckpt
I0911 02:28:53.423366 139937686464256 session_manager.py:500] Running local_init_op.
I0911 02:28:53.495537 139937686464256 session_manager.py:502] Done running local_init_op.
I0911 02:28:54.010662 139937686464256 modeling.py:415] Reloading EMA...
I0911 02:28:54.011811 139937686464256 saver.py:1284] Restoring parameters from /opt/models/wgs/model.ckpt
I0911 02:28:56.213706 139937686464256 call_variants.py:444] Processed 1 examples in 1 batches [1145.647 sec per 100]
I0911 02:28:56.265293 139937686464256 call_variants.py:447] Processed 86 examples in 1 batches [13.334 sec per 100]
I0911 02:28:56.265480 139937686464256 call_variants.py:450] Done calling variants from a total of 86 examples.

real    0m14.761s
user    0m20.588s
sys     0m5.092s

***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/input/ucsc.hg19.chr20.unittest.fasta" --infile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" --outfile "/output/output.vcf.gz" --nonvariant_site_tfrecord_path "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --gvcf_outfile "/output/output.g.vcf.gz"

2020-09-11 02:28:59.543794: I deepvariant/postprocess_variants.cc:88] Read from: /output/intermediate_results_dir/call_variants_output.tfrecord.gz
2020-09-11 02:28:59.544704: I deepvariant/postprocess_variants.cc:103] Total #entries in single_site_calls = 86
I0911 02:28:59.545160 140173302474496 postprocess_variants.py:1079] CVO sorting took 2.2590160369873047e-05 minutes
I0911 02:28:59.545950 140173302474496 postprocess_variants.py:1081] Transforming call_variants_output to variants.
I0911 02:28:59.546221 140173302474496 postprocess_variants.py:1108] Merging and writing variants to VCF and gVCF.
I0911 02:28:59.547042 140173302474496 genomics_writer.py:172] Writing /output/output.vcf.gz with NativeVcfWriter
I0911 02:28:59.547737 140173302474496 genomics_writer.py:172] Writing /output/output.g.vcf.gz with NativeVcfWriter
I0911 02:29:00.128752 140173302474496 postprocess_variants.py:1128] Finished writing VCF and gVCF in 0.00970850388209025 minutes.
I0911 02:29:00.129857 140173302474496 genomics_reader.py:223] Reading /output/output.vcf.gz with NativeVcfReader

real    0m3.961s
user    0m4.633s
sys     0m3.567s


# ls -1 ${OUTPUT_DIR}
intermediate_results_dir
output.g.vcf.gz
output.g.vcf.gz.tbi
output.vcf.gz
output.vcf.gz.tbi
output.visual_report.html

```

I think it works and thanks for your rapidly help about this~ @pichuan @tedyun 

Best,
Jerry

**Closed** 2020-09-11 02:55 UTC
