### ISSUE TITLE
DeepVariant in Docker on CentOS 7

### ISSUE THREAD

**Issue by AlfWa** [google/deepvariant#104] opened 2018-10-12 10:00 UTC
Hi,

I am trying to get the Docker image of DeepVariant to work on CentOS 7.
The same image works just fine on Ubuntu.

Many thanks, Alf.

$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
$ docker --version
Docker version 1.13.1, build 6e3bb8e/1.13.1

$ docker run -it gcr.io/deepvariant-docker/deepvariant:0.7.0

root@dade8141a904:/# /opt/deepvariant/bin/make_examples \
>     --mode calling \
>     --ref /dv2/input/ucsc.hg19.chr20.unittest.fasta.gz \
>     --reads /dv2/input/NA12878_S1.chr20.10_10p1mb.bam \
>     --examples output.examples.tfrecord \
>     --regions "chr20:10,000,000-10,010,000"
[W::hts_idx_load2] The index file is older than the data file: /dv2/input/NA12878_S1.chr20.10_10p1mb.bam.bai
2018-10-12 09:57:22.558003: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring:
I1012 09:57:22.558365 139655512114944 genomics_reader.py:213] Reading /dv2/input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1074, in make_examples_runner
    resource_monitor = resources.ResourceMonitor().start()
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/resources.py", line 59, in __init__
    self.metrics_pb = self._initial_metrics_protobuf()
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/resources.py", line 72, in _initial_metrics_protobuf
    cpu_frequency_mhz=_get_cpu_frequency(),
  File "/tmp/Bazel.runfiles_dIz6Sx/runfiles/com_google_deepvariant/deepvariant/resources.py", line 158, in _get_cpu_frequency
    freq = psutil.cpu_freq()
AttributeError: 'module' object has no attribute 'cpu_freq'

**Comment by obigbando** [comment] 2018-10-15 03:54
Error was raised by the function call of psutil.cpu_freq()
https://github.com/google/deepvariant/blob/r0.7/deepvariant/resources.py#L158  

psutil.cpu_freq function is only defined under the condition 
os.path.exists("/sys/devices/system/cpu/cpufreq") or os.path.exists("/sys/devices/system/cpu/cpu0/cpufreq")
https://github.com/giampaolo/psutil/blob/release-5.4.2/psutil/_pslinux.py#L656-L657

So the issue is that the required paths do not exist in the CentOS 7 release.

existence check of the paths before calling psutil.cpu_freq() should solve the issue.

**Comment by pgrosu** [comment] 2018-10-15 05:34
Unbelievable!  Thanks for the pointing this out @obigbando!  

@AlfWa you probably would need to set `intel_pstate=disable` at boot time as a kernel argument, and then `cpupower` - or if really necessary `modprobe` - according to what is listed in the directory using this command:

```
ls /lib/modules/`uname -r`/kernel/drivers/cpufreq/
```

You'll probably see the following see something like this, or close to it which might include `acpi-cpufreq`:

```
$ ls /lib/modules/`uname -r`/kernel/drivers/cpufreq/
cpufreq_conservative.ko  cpufreq_powersave.ko  freq_table.ko
cpufreq_ondemand.ko      cpufreq_stats.ko
$
```
Try reading the following version 7 documentation carefully:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/power_management_guide/cpufreq_governors

I included also the version 6 with `modprobe` just in case:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/power_management_guide/cpufreq_setup

Let us know if you run into any issues.

~p

**Comment by AlfWa** [comment] 2018-10-15 05:46
Thanks @pgrosu! I will try this once I am back in the office later this week.

Regards, Alf.

**Comment by dylex** [comment] 2018-10-16 21:17
We're seeing this same problem on centos7 on new processors for which there is no working cpufreq support. Why not just wrap the call to `psutil.cpu_freq` in a `try`? I'm happy to provide a PR for that. (cc: @njcarriero @chris-sf)

**Comment by pgrosu** [comment] 2018-10-16 21:35
All it seems to be doing is be fed to `cpu_frequency_mhz` in `_initial_metrics_protobuf()` for building the `resource_metrics` in `make_examples` via a `ResourceMonitor` class instantiation.  It does not seem to be used in any calculations other than keeping track of that.  I guess `freq` could even be set to 0.

**Comment by ksw9** [comment] 2018-11-10 17:11
Hi,
Is there a fix for this? I am getting the same error: AttributeError: 'module' object has no attribute 'cpu_freq'
This error persists even when I include intel_pstate=disable .
Thank you!

**Comment by pichuan** [comment] 2018-11-11 06:38
Hi,
can you try the 0.7.1 image? It seems to work for me on CentOS7 now.

I was able to run the Exome case study with the following steps:

I used a GCE instance for testing:

```
gcloud beta compute instances create "${USER}-centos-test"  \
--scopes "compute-rw,storage-full,cloud-platform" \
--image "centos-7-v20181011" \
--image-project centos-cloud \
--machine-type "custom-64-131072" \
--boot-disk-size "300" \
--boot-disk-type "pd-ssd" \
--zone "us-west1-b"
```

I sshed into the machine, and checked the OS version:

```
[pichuan@pichuan-centos-test ~]$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core) 
```

Then:

```
[pichuan@pichuan-centos-test ~]$ sudo yum install -y docker
[pichuan@pichuan-centos-test ~]$ sudo service docker start
Redirecting to /bin/systemctl start docker.service
[pichuan@pichuan-centos-test ~]$ sudo docker run -it gcr.io/deepvariant-docker/deepvariant:0.7.1
```

Then, I use a modified script to run WES case study:

```
root@5189b7fba95b:/# curl https://gist.githubusercontent.com/pichuan/7916a5574c47fd7a2422bad4e5f73860/raw/44fb4377c9ad8b54e195fdb31489d8e9fbc459e2/inside_docker.sh | bash
```

You can see:
https://gist.githubusercontent.com/pichuan/7916a5574c47fd7a2422bad4e5f73860/raw/44fb4377c9ad8b54e195fdb31489d8e9fbc459e2/inside_docker.sh
for the script that I ran inside the docker.

If the 0.7.1 version still doesn't work, feel free to reopen. Thanks!

**Closed by pichuan** 2018-11-11 06:38 UTC

**Comment by ksw9** [comment] 2018-11-13 23:58
Thank you - yes, I just tried in 0.7.1 and now am running into a new error. I have python and numpy installed and I am wondering how to make this accessible or if this is a Docker issue?
Thank you in advance,
Best,
```
  File "/tmp/Bazel.runfiles_uDUZWS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 37, in <module>
    import numpy as np
ImportError: No module named numpy
```

**Comment by pichuan** [comment] 2018-11-14 05:43
@ksw9 can you post the full sequence of commands? I tried inside the docker, and it seems to be fine:

```
[pichuan@pichuan-centos-test ~]$ sudo docker run -it gcr.io/deepvariant-docker/deepvariant:0.7.1
Unable to find image 'gcr.io/deepvariant-docker/deepvariant:0.7.1' locally
Trying to pull repository gcr.io/deepvariant-docker/deepvariant ... 
0.7.1: Pulling from gcr.io/deepvariant-docker/deepvariant
18d680d61657: Pull complete 
0addb6fece63: Pull complete 
78e58219b215: Pull complete 
eb6959a66df2: Pull complete 
54de1d38bbd7: Pull complete 
d17c3563217d: Pull complete 
ba1bdbdefce9: Pull complete 
94eba53c4ad9: Pull complete 
413f494b0501: Pull complete 
4d89363e7fb4: Pull complete 
e9213d1ccf36: Pull complete 
fb6121657d6b: Pull complete 
Digest: sha256:705523e7bc241e0d3e1e57d4d338c83e289d51a8231c09b0d2dee03c015cee0f
Status: Downloaded newer image for gcr.io/deepvariant-docker/deepvariant:0.7.1
root@e2fb03e85f9e:/# python -c "import numpy"
root@e2fb03e85f9e:/# python -c "import numpy as np"
root@e2fb03e85f9e:/# 
```

**Comment by ksw9** [comment] 2018-11-16 21:52
Hi, 
I am now testing the quickstart with the test data (https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-quick-start.md)  inside of docker and I get the error ValueError: Not found: Could not open quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam. I followed the instructions and 
`
OUTPUT_DIR=quickstart-testdata/
REF=quickstart-testdata/ucsc.hg19.chr20.unittest.fasta
BAM=quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam

## test deepvariant
docker run \
-v /home/${USER}:/home/${USER} \
gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/make_examples \
--mode calling   \
--ref "${REF}"   \
--reads "${BAM}" \
--regions "chr20:10,000,000-10,010,000" \
--examples "${OUTPUT_DIR}/examples.tfrecord.gz"

`

The BAM file is there, when I try ls  $BAM, I get: quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam.

Any suggestions would be great, thank you!

**Comment by pichuan** [comment] 2018-11-17 03:56
@ksw9 
Hi, the current quickstart needs a small fix:
`/home/${USER}` should be `${HOME}` to be more general.
And, note that in order for docker to access your file system, you do need the `-v` path.
So you probably want something like:
OUTPUT_DIR=${HOME}/quickstart-output
mkdir -p "${OUTPUT_DIR}"
REF=${HOME}/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta
BAM=${HOME}/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam

and 
`-v ${HOME}:${HOME} `
in the docker command

**Comment by ksw9** [comment] 2018-11-19 05:40
Fantastic, this works. Thanks for the help!
Best,

**Comment by pichuan** [comment] 2018-12-03 16:49
@patrickbryant1 Did you try the suggestion in https://github.com/google/deepvariant/issues/104#issuecomment-439585565 ?

Docker needs to be able to see the directory by passing in the right `-v`

**Comment by pichuan** [comment] 2018-12-03 19:10
Do you mean you're still getting the errors after that? Can you post your commands?
