### ISSUE TITLE
CLIF for Ubuntu 18 missing

### ISSUE THREAD

**Issue by Stikus** [google/deepvariant#289] opened 2020-03-27 15:39 UTC
Hello. 
Thanks for long awaited update to Python3.
I'm trying to update our pipeline and getting error when installing CLIF.
Looks like https://storage.googleapis.com/deepvariant/packages/oss_clif_py3/oss_clif.ubuntu-18.latest.tgz is missing while https://storage.googleapis.com/deepvariant/packages/oss_clif_py3/oss_clif.ubuntu-16.latest.tgz exists.
Can you fix this please?

**Comment by pichuan** [comment] 2020-03-27 19:55
Hi @Stikus 

You're right that we haven't rebuild the corresponding Ubuntu 18 version like the one in gs://deepvariant/packages/oss_clif/oss_clif.ubuntu-18.latest.tgz

I'll file an internal bug and get to this when I can. I think I probably have time in the next week. Feel free to ping in another week if I don't reply.

**Comment by pichuan** [comment] 2020-03-27 20:04
@Stikus 
Update: @gunjanbaid will start woking on this, and we'll get back to you soon.

**Comment by gunjanbaid** [comment] 2020-03-28 22:25
Hi @Stikus, the Ubuntu 18 CLIF binary has now been uploaded, so scripts should work as intended. We are working on adding other CLIF binaries soon. Thanks for pointing this out. I'll close this issue, but feel free to reopen if you have any other questions!

**Closed by gunjanbaid** 2020-03-28 22:25 UTC
