### ISSUE TITLE
any idea how to estimate run time and compute resources required

### ISSUE THREAD

**Issue by aedavids** [google/deepvariant#260] opened 2020-01-13 00:04 UTC
Hi 

I am a Newbie/Student with some "best practices" questions

I am using the docker version 0.9.0 and following the script in the quick start example. I have two data sets of Illumina reads one was from a control group, the other from a treatment group. I think the number of reads is comparable. One batch has been generating examples for over 3.5 days. The other batch is running on 32 vCPU machine. It is still generating images after 1.5 days.

I checked the OS level stats, the machines are not swapping. all cpu's are at 100%. Still alot of unused memory and disk.

1)  Any idea how I might estimate the expected run time? 

2) Any idea of how I do a better job sizing compute resources?

3) How do I know if docker is making progress or not?
I did a run a couple of weeks ago. I think it took a total of 66 CPU hrs. It seemed like after all the examples where constructed the docker did not produce log message for a long time. Eventually, the docker completed. The results were really good!

4) I run on ubuntu and use nohub. I want to run time, my script, report 'data up' on completions. I always put nohub job in the background. It seems like after examples have been constructed I will not see my nohub in the jobs list, however, if I use top I see all my cpu's are running python and are at 100%. Is there a better way to run my script

thanks

Andy

p.s. I am running in AWS . not sure if that makes a difference or not

p.p.s. Is there a better place to ask questions like this?

**Comment by pichuan** [comment] 2020-01-13 02:22
> 1. Any idea how I might estimate the expected run time?

The run time of `make_examples` step can be affected by many factors, such as the coverage(depth) of the input. One component in make_examples is local realignment, which can be affected by things like depth, read length, etc. Currently I think that might be causing the biggest variance of the runtime of make_examples. This makes it hard for me to give general estimation guidelines.
Can you give us a bit more information on your BAM? Is it WGS or WES? Which Illumina sequencing machine is it from?
If you are okay with sharing the BAM header, it'll help too. If it's easier to share via email, you can email pichuan@google.com

> 2. Any idea of how I do a better job sizing compute resources?

On the GCP DeepVariant tutorial page:
https://cloud.google.com/life-sciences/docs/tutorials/deepvariant
You can see some numbers of runtime and cost estimates on GCP. This might help give you some sense of what type of machine you can choose. Since you're running on AWS, the cost might change based on pricing.


> 3. How do I know if docker is making progress or not?


Currently, our one-step script should be outputting some logs as it goes. If make_examples is still running, you should see lines of logs coming out, showing there's progress. There's likely room for improvement on how we show this progress. If you have suggestions or bug reports, please let us know.

>    I did a run a couple of weeks ago. I think it took a total of 66 CPU hrs. It seemed like after all the examples where constructed the docker did not produce log message for a long time. Eventually, the docker completed. The results were really good!

Sorry to hear that the logs are not coming out promptly. If it's possible, can you tell us where did the log get stuck?

> 4. I run on ubuntu and use nohub. I want to run time, my script, report 'data up' on completions. I always put nohub job in the background. It seems like after examples have been constructed I will not see my nohub in the jobs list, however, if I use top I see all my cpu's are running python and are at 100%. Is there a better way to run my script

I haven't tried using nohub. I'll have to try and respond to this later.
> 
> thanks
> 
> Andy
> 
> p.s. I am running in AWS . not sure if that makes a difference or not

I don't expect it to make a difference. But if you do observe any issues, feel free to let us know what kind of AWS instances you're running on, and what's the unexpected behavior, so we can reproduce the issue.
> 
> p.p.s. Is there a better place to ask questions like this?

This is a good place to ask :)
It's a public forum, so our team and everyone in the community can see and help.

**Comment by aedavids** [comment] 2020-01-13 19:55
Hi Pichuan


> Can you give us a bit more information on your BAM? Is it WGS or WES? Which Illumina sequencing machine is it from?

The am using WES. We assumed this would run faster

> If you are okay with sharing the BAM header, it'll help too. If it's easier to share via email, you can email [pichuan@google.com](mailto:pichuan@google.com)
> 

I sent the headers to you in email.


> > I did a run a couple of weeks ago. I think it took a total of 66 CPU hrs. It seemed like after all the examples where constructed the docker did not produce log message for a long time. Eventually, the docker completed. The results were really good!
> 

The run that worked well used WGS. The library was created by a different Lab

Not sure if this is relevant or not. We are running on RNA. We got really good F-scores on our "gold standard" data set.


> > p.s. I am running in AWS . not sure if that makes a difference or not
> 
> I don't expect it to make a difference. But if you do observe any issues, feel free to let us know what kind of AWS instances you're running on, and what's the unexpected behavior, so we can reproduce the issue.
> 

region: oregen
m5dn.8xlarge
32 CPU
2 x 600GB SSD
Deep Learning AMI (Ubuntu 16.04) Version 26.0 (ami-07728e9e2742b0662)

**Comment by aedavids** [comment] 2020-01-13 23:15
I am trying to figure out how long my batch might take to run. 

1) any idea how I can estimate the number of examples that will be created?

2) I notices some examples can be created in a min or two, others take almost an hour. any ideas? .
Here is a small sample output. From a batch job running on a 4 cpu machine

```
I0113 21:56:11.182070 139690792257280 make_examples.py:1363] Task 0: 36301 candidates (37329 examples) [1962.23s elapsed]
I0113 21:57:44.984076 139690792257280 make_examples.py:1363] Task 0: 36412 candidates (37442 examples) [93.80s elapsed]
I0113 21:58:41.721879 139690792257280 make_examples.py:1363] Task 0: 36500 candidates (37536 examples) [56.74s elapsed]
I0113 22:54:35.368127 139690792257280 make_examples.py:1363] Task 0: 36601 candidates (37641 examples) [3353.65s elapsed]
I0113 22:58:18.541445 139690792257280 make_examples.py:1363] Task 0: 36715 candidates (37762 examples) [223.17s elapsed]
```

the sample output below is from a run on a 32 core machine

```
I0113 19:45:44.880142 140004561770240 make_examples.py:1363] Task 0: 5011 candidates (5121 examples) [3922.37s elapsed]
I0113 19:50:11.671694 140004561770240 make_examples.py:1363] Task 0: 5100 candidates (5210 examples) [266.79s elapsed]
I0113 20:45:11.229505 140004561770240 make_examples.py:1363] Task 0: 5202 candidates (5321 examples) [3299.56s elapsed]
```

**Comment by pichuan** [comment] 2020-01-14 13:49
Hi @aedavids ,
since you're running on WES, can you confirm you're using the `--regions` flag to specify a target capture BED?

For example, in our WES case study:
https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-exome-case-study.md

You can see that we specified a `--regions="/input/${CAPTURE_BED}"` flag.

The reason why WES runs are faster than WGS runs is because WES only target about 1-2% of the whole genome. If you don't specify that flag, it will be noticeably slower.

Please let me know whether you're already using `--regions`. If not, please let me know if adding that solves your problem.

That being said, the numbers you reported (with a few thousands seconds elapsed) seem on the higher side. I'll think about how to report and maybe limit the runtime if possible.

**Comment by pichuan** [comment] 2020-02-04 03:33
Update: we discussed offline. Using `--regions` helped.
I'll close this bug.

**Closed by pichuan** 2020-02-04 03:33 UTC
