### ISSUE TITLE
`model_eval` ignores pre-existing, not-yet-evaluated checkpoints, and nothing else seems to exist to evaluate them

### ISSUE THREAD

**Issue by adamnovak** [google/deepvariant#611] opened 2023-02-10 18:03 UTC
**Describe the issue:**

The `model_eval` command can't catch up and evaluate checkpoints in a directory other than the latest one. If it ever crashes or isn't started in time to actually witness training create a checkpoint, there's no way for the user to evaluate the checkpoints it missed, and the "best" checkpoint it finds won't actually necessarily be the best out of all the checkpoints in the directory.  

**Setup**
  - Operating system: Ubuntu 22.04
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: case study data

**Steps to reproduce:**

Loosely following https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-training-case-study.md#start-model_train-and-model_eval, I started the training Docker container using GPU 0:

```
time docker run --rm --gpus 1 \
  -v "${DATA_DIR}:${DATA_DIR}" \
  -v "${OUTPUT_DIR}:${OUTPUT_DIR}" \
  -u $(id -u):$(id -g) \
  google/deepvariant:1.4.0-gpu \
  /opt/deepvariant/bin/model_train \
  --dataset_config_pbtxt="${OUTPUT_DIR}/training_set.dataset_config.pbtxt" \
  --train_dir="${TRAINING_DIR}" \
  --model_name="inception_v3" \
  --number_of_steps=50000 \
  --save_interval_secs=300 \
  --batch_size=32 \
  --learning_rate=0.0005 \
  --start_from_checkpoint="gs://deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-wgs_standard/model.ckpt"
```

Then I tried to start the `model_eval` evaluator in GPU mode with 1 GPU, but Docker was just giving it the *same* GPU as training was using, so it kept immediately running out of GPU memory. After about half an hour I hit on the right syntax to give it a distinct GPU, and managed to actually start `model_eval`:

```
docker run --rm --gpus '"device=1"' \
  -v "${DATA_DIR}:${DATA_DIR}" \
  -v "${OUTPUT_DIR}:${OUTPUT_DIR}" \
  -u $(id -u):$(id -g) \
  google/deepvariant:1.4.0-gpu \
  /opt/deepvariant/bin/model_eval \
  --dataset_config_pbtxt="${OUTPUT_DIR}/validation_set.dataset_config.pbtxt" \
  --checkpoint_dir="${TRAINING_DIR}" \
  --batch_size=512 \
  --min_eval_interval_s=1 \
  --eval_timeout=1000
```

It evaluated the most recent checkpoint saves as of when it started up, and it is evaluating new checkpoints as they are created. But it doesn't seem interested in going back and evaluating all the checkpoints, other than the initial-latest one, that were created before it started.

The directory in question looks like this:
```
(dv_venv) [anovak@phoenix-01 trash]$ ls output/models/*meta
output/models/model.ckpt-0.meta      output/models/model.ckpt-19459.meta  output/models/model.ckpt-31078.meta
output/models/model.ckpt-1000.meta   output/models/model.ckpt-2000.meta   output/models/model.ckpt-34008.meta
output/models/model.ckpt-10674.meta  output/models/model.ckpt-22355.meta  output/models/model.ckpt-4814.meta
output/models/model.ckpt-13613.meta  output/models/model.ckpt-25257.meta  output/models/model.ckpt-7724.meta
output/models/model.ckpt-16546.meta  output/models/model.ckpt-28168.meta
(dv_venv) [anovak@phoenix-01 trash]$ ls output/models/*metrics
output/models/best_checkpoint.metrics  output/models/model.ckpt-28168.metrics  output/models/model.ckpt-34008.metrics
output/models/current.metrics          output/models/model.ckpt-31078.metrics
```

But `model_eval` just sits there like this (until a new checkpoint appears):
```
I0210 17:42:06.700287 139846137329472 checkpoint_utils.py:140] Waiting for new checkpoint at /public/groups/cgl/graph-genomes/anovak/trash/output/models
```

How do I get the missing `*metrics` files and determine if any of the checkpoints that were missed is actually the best one? Do I need to `touch` some particular files in the directory to get `model_eval` to be interested in them? Is there some other command besides `model_eval` that can process a single particular checkpoint at a time?

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

It doesn't look like model training is part of the quick start.

**Any additional context:**

Eventually I might want a WDL workflow for training DeepVariant, and I'm not sure that managing two simultaneous DV processes in there is going to be worth the engineering required; they'd have to be lumped together into one WDL task and they'd have to always fit simultaneously on one machine. It would be much simpler for me to be able to run the training to the end, and then run all the evaluations afterward to select the best model. But it looks like if I tried that right now `model_eval` would just only evaluate the last checkpoint and always confidently declare it to be the best.

**Comment by pichuan** [comment] 2023-02-13 17:17
Hi, sorry this is taking a while. I should have handled this last week but got too busy. I'll try to reply today or tomorrow.

**Comment by pichuan** [comment] 2023-02-15 17:14
Hi @adamnovak , 
I can confirm that our current code is designed to wait for new checkpoints, and only evaluate new ones. I understand that it'll be great retrospectively evaluate older checkpoints too. But we haven't experimented with that.

I haven't got time to do so; but in the next few weeks (to a month) I'll likely need to re-run the training tutorial anyway. I'll try to find a time to see if it could be easy to tweak that behavior (but I don't know for sure).

I'll keep this issue open and assigned to me for now.

**Comment by pichuan** [comment] 2023-04-18 16:33
Hi @adamnovak ,
given that we're planning on a migration for the modeling framework, we won't spend too much time on this.
I'll close the issue. Feel free to reach out if there's anything you want to discuss.

**Closed by pichuan** 2023-04-18 16:33 UTC

**Comment by pgrosu** [comment] 2023-04-18 19:52
@adamnovak,

Just try to copy an old checkpoint file as a new file so it gets an updated timestamp, since just quickly looking at the tensorflow source code it seems to just look for the latest file:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/checkpoint_utils.py#L150-L178

https://github.com/tensorflow/tensorflow/blob/55d62330dd9197e69ff8f1f03981784184706b2a/tensorflow/python/checkpoint/checkpoint_management.py#L326-L363

It if complains then it would be easy to tweak the checkpoints for what tensorflow is looking for in that directory.

Hope it helps,
~p
