### ISSUE TITLE
postprocess_variants hangs with 0 CPU usage

### ISSUE THREAD

**Issue by zyxue** [google/deepvariant#103] opened 2018-10-11 18:53 UTC
I am running 

```
sudo docker run -v ${HOME}:${HOME} gcr.io/deepvariant-docker/deepvariant:0.7.0 /opt/deepvariant/bin/postprocess_variants \
     --ref ${OUTDIR}/data/hg19.fa \
     --infile ${OUTDIR}/output/cvo.tfrecord.gz \
     --outfile ${OUTDIR}/output/output.vcf.gz \
     --nonvariant_site_tfrecord_path ${OUTDIR}/output/gvcf.tfrecord@8.gz \
     --gvcf_outfile ${OUTDIR}/output/output.gvcf.gz
```

and it seems to just hang there after running for about 15min. CPU usage is 0 based on htop, and no output has been written. What could be a possible reason, please?

BTW, is this step parallelizable?

**Comment by pgrosu** [comment] 2018-10-11 23:12
@zyxue Before we get to parallelizable, we need to be a bit invasive to determine what's happening.  A caution, this will get complex and a bit extensive, so don't get scared.

1) First start your session interactive like this - notice the `-it` option:

` sudo docker run -it -v ${HOME}:${HOME} gcr.io/deepvariant-docker/deepvariant:0.7.0 /bin/bash`

Then go to your deepvariant directory and unzip, as the compiled version is just a call to that:

```
paul:~$ sudo docker run -it -v ${HOME}:${HOME} gcr.io/deepvariant-docker/deepvariant:0.7.0 /bin/bash
root@c2b850869dc6:/# cd /opt/deepvariant/bin/
root@c2b850869dc6:/opt/deepvariant/bin# mkdir unzip-post
root@c2b850869dc6:/opt/deepvariant/bin# cd unzip-post/
root@c2b850869dc6:/opt/deepvariant/bin/unzip-post# unzip ../postprocess_variants.zip
Archive:  ../postprocess_variants.zip
  inflating: __main__.py
 extracting: __init__.py
...
root@c2b850869dc6:/opt/deepvariant/bin/unzip-post#
```

2) Next switch to the location of the Python file and run it with a trace as follows - I removed the prompt entry and left a `#` so that you see the commands:

```
# cd runfiles/com_google_deepvariant/deepvariant/
# python -mtrace --trackcalls postprocess_variants.py YOUR_ARGUMENTS_WITH_FULL_PATHS
```
The `YOUR_ARGUMENTS_WITH_FULL_PATHS` is the arguments with absolute paths.  Then just print out the output of the trace here, in order to see where it might be getting stuck.

Thanks,
Paul

**Comment by zyxue** [comment] 2018-10-12 21:08
The start seems to be quite slow, after about 27s it exits, here is the output
```
root@52e2e7bb0093:/opt/deepvariant/bin/unzip-post/runfiles/com_google_deepvariant/deepvariant# time python -mtrace --trackcalls postprocess_variants.py --ref /home/zxue/deepvariant_exp/tcga-data/hg19.fa       --infile /home/zxue/deepvariant_exp/output/cvo.tfrecord.gz     
  --outfile /home/zxue/deepvariant_exp/output/output.vcf.gz       --nonvariant_site_tfrecord_path /home/zxue/deepvariant_exp/output/gvcf.tfrecord@8.gz                                                                                                                          
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/trace.py", line 819, in <module>
    main()
  File "/usr/lib/python2.7/trace.py", line 807, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python2.7/trace.py", line 513, in runctx
    exec cmd in globals, locals
  File "postprocess_variants.py", line 46, in <module>
    from third_party.nucleus.io import fasta
ImportError: No module named third_party.nucleus.io

real    0m27.273s
user    0m27.133s
sys     0m0.904s
```

**Comment by pgrosu** [comment] 2018-10-12 22:23
Yes unfortunately it will be temporarily slower since we're in interactive mode, which we want in order to control our debug session to discover what is happening in your session.  Once we identify the root cause, then we will have a path to some solution that our empirical approach will uncover.  So what you are seeing is that it needs a module, for which we need to go and launch from the parent directory (`runfiles/com_google_deepvariant`) and specify the `PYTHONPATH` as follows - notice the second `ls` command below shows the presence of `fasta.py` in `third_party/nucleus/io`:

```Bash
root@d80a33474273:/opt/deepvariant/bin/unzip-post/# cd runfiles/com_google_deepvariant/
root@d80a33474273:/opt/deepvariant/bin/unzip-post/runfiles/com_google_deepvariant#
root@d80a33474273:/opt/deepvariant/bin/unzip-post/runfiles/com_google_deepvariant# ls third_party/nucleus/io
__init__.py  bed.py  clif_postproc.py  fasta.py  genomics_reader.py  genomics_writer.py  python  vcf.py

# PYTHONPATH=. /usr/bin/python -mtrace --trackcalls deepvariant/postprocess_variants.py --ref /home/zxue/deepvariant_exp/tcga-data/hg19.fa --infile /home/zxue/deepvariant_exp/output/cvo.tfrecord.gz --outfile /home/zxue/deepvariant_exp/output/output.vcf.gz --nonvariant_site_tfrecord_path /home/zxue/deepvariant_exp/output/gvcf.tfrecord@8.gz
```

For clarity, I left the prompt out on the last line that you would launch.  You would need to launch it as is written starting with `PYTHONPATH` in order to set the search-order of modules.

Let's see what this uncovers.

Thanks,
Paul

**Comment by pichuan** [comment] 2018-11-06 05:52
@zyxue  curious whether you're able to resolve this?
I'm going to close this since the last update was a while ago. If you have more information, feel free to update and re-open.

**Closed by pichuan** 2018-11-06 05:52 UTC
