### ISSUE TITLE
Cannot identify error cause in make_examples stage

### ISSUE THREAD

**Issue by obsh** [google/deepvariant#207] opened 2019-08-20 08:19 UTC
Hi

I'm running a pipeline but get an error on "make_examples" stage. Could you help me to debug possible cause, please?

Here is a log:
```
[W::hts_idx_load2] The index file is older than the data file: /mnt/google/.google/input/cannabis-3k-results/manual/merged_bam/SRS1107973_LKUA01.sorted.merged.bam.bai
2019-08-14 12:36:51.456603: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
WARNING: Logging before flag parsing goes to stderr.
I0814 12:36:53.581777 140158089049856 genomics_reader.py:174] Reading /mnt/google/.google/input/cannabis-3k-results/manual/merged_bam/SRS1107973_LKUA01.sorted.merged.bam with NativeSamReader
I0814 12:36:54.201131 140158089049856 make_examples.py:1024] Preparing inputs
[W::hts_idx_load2] The index file is older than the data file: /mnt/google/.google/input/cannabis-3k-results/manual/merged_bam/SRS1107973_LKUA01.sorted.merged.bam.bai
2019-08-14 12:36:58.286794: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I0814 12:36:59.914532 140158089049856 genomics_reader.py:174] Reading /mnt/google/.google/input/cannabis-3k-results/manual/merged_bam/SRS1107973_LKUA01.sorted.merged.bam with NativeSamReader
I0814 12:45:36.568115 140158089049856 make_examples.py:946] Common contigs are [u'LKUA01000001.1', u'LKUA01000002.1', ...<ANOTHER 300k NAMES>..., u'LKUA01311038.1', u'LKUA01311039.1']
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --examples /mnt/google/.google/output/cannabis-3k-vcf/staging/SRS1107973_LKUA01/staging/examples/0/examples_output.tfrecord@512.gz --reads /mnt/google/.google/input/cannabis-3k-results/manual/merged_bam/SRS1107973_LKUA01.sorted.merged.bam --ref /mnt/google/.google/input/cannabis-3k/reference/LKUA01/LKUA01.fa --task 8
```

For me it looks that the error message is `parallel: This job failed:` and failure doesn't relate to the warnings at the beginning of the file?

Regards,

**Comment by gunjanbaid** [comment] 2019-08-20 18:49
@obsh regenerating the `.bai` index file should fix the first warning. The `Unrecognized SAM header type` warning should not cause the job to fail. 

Some questions for you:
* What is the command you used to run `make_examples`? Any additional output would also be helpful.
* Is task 8 the only one that failed?
* (Unrelated to this error) Which model do you plan to use for this data?

**Comment by obsh** [comment] 2019-08-21 09:37
Hi @gunjanbaid,
I'm starting pipeline with a GCP runner like this:
```
MODEL=gs://deepvariant/models/DeepVariant/0.6.0/DeepVariant-inception_v3-0.6.0+cl-191676894.data-wgs_standard
IMAGE_VERSION=0.6.1
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
DOCKER_IMAGE_GPU=gcr.io/deepvariant-docker/deepvariant_gpu:"${IMAGE_VERSION}"

./opt/deepvariant_runner/bin/gcp_deepvariant_runner \
    --project "${PROJECT_ID}" \
    --zones "${ZONES}" \
    --docker_image "${DOCKER_IMAGE}" \
    --docker_image_gpu "${DOCKER_IMAGE_GPU}" \
    --gpu \
    --outfile "${OUTPUT_BUCKET}"/"${OUTPUT_FILE_NAME}" \
    --staging "${OUTPUT_BUCKET}"/"${STAGING_FOLDER_NAME}" \
    --model "${MODEL}" \
    --ref "${INPUT_REF}" \
    --bam "${INPUT_BAM}" \
    --shards 512 \
    --make_examples_workers 16 \
    --make_examples_cores_per_worker 10 \
    --make_examples_ram_per_worker_gb 60 \
    --make_examples_disk_per_worker_gb 200 \
    --call_variants_workers 16 \
    --call_variants_cores_per_worker 8 \
    --call_variants_ram_per_worker_gb 30 \
    --call_variants_disk_per_worker_gb 50
```
I've checked logs - a bunch of tasks failed (8, 32, 67, 105, 192, 231, 261, 293, 358).

**Comment by gunjanbaid** [comment] 2019-08-26 01:50
Hi @obsh, I am still not sure what is causing the failure. I noticed that you are using an older release (v0.6.1), so I would suggest switching to the latest v0.8.0 release. I'm not sure that this will address the failures, but I would recommend it regardless since we have updated the code and models. 

As a sanity check, you could try running the command above with different data. [This page](https://cloud.google.com/genomics/docs/tutorials/deepvariant#calling_exome_regions_configuration) contains an example using Whole Exome Sequencing (WES) data. If the problem is fixed, perhaps there is something unexpected about your data, and we can further investigate.

We also recommend that you try directly running DeepVariant through the Docker image, which may provide additional error messages that are helpful for debugging. You can refer to [this document](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md) for an example. Please let us know if you run into the issue through this setup.

One thing to note: our models have been trained using human data, and may not necessarily generalize well across species. We have trained a model for mosquito data, and while doing so, we noticed that retraining using data from this species significantly improved performance (more details in [this post](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/). The mosquito model is not public, but we are happy to share it with you. Feel free to email me at gunjanbaid@google.com for more information.

**Comment by obsh** [comment] 2019-09-03 06:27
Hi @gunjanbaid, thank you! I'll try the v0.8.0 release and other recommendations.

I’m working on a cannabis variants project with a Googler @allenday.
We consulted @AndrewCarroll previously, from his preliminary analysis - seems that default DeepVariant model should work fine with our data.

**Comment by gunjanbaid** [comment] 2019-09-04 17:10
@obsh sounds good. I'll close this issue for now, but feel free to reopen if you run into any other errors.

**Closed by gunjanbaid** 2019-09-04 17:10 UTC
