### ISSUE TITLE
ValueError: Data loss: Expected mtid >= 0 as mate is supposedly mapped

### ISSUE THREAD

**Issue by zyxue** [google/deepvariant#99] opened 2018-10-03 21:09 UTC
I've successfully run deepvariant with test data. But I keep getting the following error when extracting pileup images from my own provided BAM file. What could be the problem, please?

```
I1003 20:27:32.183320 140083390310144 make_examples.py:825] Found 0 candidates in chr1:1-1000 [1000 bp] [1.62s elapsed]
I1003 20:27:32.185085 140083390310144 make_examples.py:825] Found 0 candidates in chr1:1001-2000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.186733 140083390310144 make_examples.py:825] Found 0 candidates in chr1:2001-3000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.188343 140083390310144 make_examples.py:825] Found 0 candidates in chr1:3001-4000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.189908 140083390310144 make_examples.py:825] Found 0 candidates in chr1:4001-5000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.191494 140083390310144 make_examples.py:825] Found 0 candidates in chr1:5001-6000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.193065 140083390310144 make_examples.py:825] Found 0 candidates in chr1:6001-7000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.194626 140083390310144 make_examples.py:825] Found 0 candidates in chr1:7001-8000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.196187 140083390310144 make_examples.py:825] Found 0 candidates in chr1:8001-9000 [1000 bp] [0.00s elapsed]
I1003 20:27:32.197738 140083390310144 make_examples.py:825] Found 0 candidates in chr1:9001-10000 [1000 bp] [0.00s elapsed]
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1090, in make_examples_runner
    candidates, examples, gvcfs = region_processor.process(region)
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 808, in process
    self.in_memory_sam_reader.replace_reads(self.region_reads(region))
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 844, in region_reads
    reads, self.options.max_reads_per_partition, self.random)
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/third_party/nucleus/util/utils.py", line 92, in reservoir_sample
    for i, item in enumerate(iterable):
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/six_archive/six.py", line 558, in next
    return type(self).__next__(self)
  File "/tmp/Bazel.runfiles_8StCi1/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 67, in __next__
    not_done, record = self._cc_iterable.Next()
ValueError: Data loss: Expected mtid >= 0 as mate is supposedly mapped: fragment_name:ValueError: Data loss: Expected mtid >= 0 as mate is supposedly mapped: fragment_name: "XXX00-XX000_000:0:0000:0000:000000/0" read_number: 1 number_reads: 2 alignment { position { reference_name: "chr1" position: 10540 reverse_strand: true } mapping_quality: 60 cigar { operation: ALIGNMENT_MATCH operation_length: 50 } } aligned_sequence: "ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGAT" aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 35 aligned_quality: 36 aligned_quality: 36 aligned_quality: 36 aligned_quality: 36 aligned_quality: 35 aligned_quality: 35 aligned_quality: 37 aligned_quality: 37 aligned_quality: 37 aligned_quality: 39 aligned_quality: 39 aligned_quality: 39 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 41 aligned_quality: 39 aligned_quality: 39 aligned_quality: 39 aligned_quality: 39 aligned_quality: 39 aligned_quality: 37 aligned_quality: 37 aligned_quality: 37 aligned_quality: 37 aligned_quality: 37 aligned_quality: 34 aligned_quality: 34 aligned_quality: 34 next_mate_position { }

```

**Comment by pichuan** [comment] 2018-10-03 21:31
Hi,
this error corresponding to this line in the Nucleus codebase:
https://github.com/google/nucleus/blob/master/nucleus/io/sam_reader.cc#L409

which I think is indicating your BAM file actually isn't quite we're expecting. One qustion for you:
Is there anything after `fragment_name`? If so, it's useful to find out the read in your BAM file so we can understand it better. 
samtools view YOUR_BAM | grep FRAGMENT_NAME
might give you more information about the read that our SamReader is complaining.

Thanks!

**Comment by depristo** [comment] 2018-10-03 21:31
Hi Zhuyi,

DeepVariant is complaining here because your BAM has a record that says it has a mapped mate but mtid, which is the htslib variable holding the offset into the chromosome array, isn't set so its actual mapped location isn't present. This would normally indicate that's something corrupted with your BAM. Where did you get? How was it aligned? I'd recommend running ValidateSamFile to see if it complains.

It could be we've being overly strict in Nucleus for parsing our BAMs. It'd be great if you can determine if your BAM is considered valid or not, and let us know if we need to be more permissive in our parsing or if the BAM needs to be fixed up.

All the best,

Mark

**Comment by zyxue** [comment] 2018-10-03 21:41
It is the bam file of a TCGA sample. I didn't align it myself, it's downloaded directly from a TCGA host. I will check and see it's validity, thank you for the information.

**Comment by zyxue** [comment] 2018-10-03 21:45
Yes, there is fragment name after that, and some quality related info. The sample is sensitive, so I was being careful. It's actually right the first read in the sorted bam

**Comment by zyxue** [comment] 2018-10-03 22:44
I identified the read pairs that are causing the problem:

```
[read_id]/2  145  chr1   10535     59  50M          *  0  0  [read_seq]  CC?DD@DDDDDEEEEEFFFFFFHHHHJIJJJJJIIJJGHHHHFFFFFCCC ...
[read_id]/1  81   chr10  38696640  69  29M1062N21M  *  0  0  [read_seq]  JJJJJJJJJJJJJJJJJJJJIJIFIGIJJIJJIGHGJHHFHHFFFFFCCB ...
```
These are the primary alignments, `[read_id]/2` also has a few non-primary alignments.

Hmm... the pair of reads are aligned to two chromosomes, is that why `make_examples` is raising the error? Could those reads just be ignored? I tried `make_examples` with one other bam, and see the same error.

Also, wondering how `make_examples` deals with non-primary alignments?

**Comment by pgrosu** [comment] 2018-10-04 03:02
Maybe it's the following scenario:

So the flags indicate these are paired-end reads:

```
81  -> (read paired [0x1 (hex) = 1 (dec)], read reverse strand [0x10 = 16], first in pair  [0x40 = 64] )
145 -> (read paired [0x1 = 1], read reverse strand [0x10 = 16], second in pair [0x80 = 128])
```

But the mate chromosome is * instead of =, which sets the `mtid` to -1 in [sam.c at the following lines](https://github.com/samtools/htslib/blob/master/sam.c#L1278-L1287):

```C
   // mate chr
    q = _read_token(p);
    if (strcmp(q, "=") == 0) {
        c->mtid = c->tid;
    } else if (strcmp(q, "*") == 0) {
        c->mtid = -1;
    } else {
        c->mtid = bam_name2id(h, q);
        _parse_warn(c->mtid < 0, "urecognized mate reference name; treated as unmapped");
    }
```

Notice the assignment to `-1`, which might be because these reside on different chromosomes (`chr1` and `chr10`), which can happen in cancer through translocation.

Hope it helps,
~p

**Comment by zyxue** [comment] 2018-10-04 17:32
So it's not a problem of the bam file?

**Comment by pichuan** [comment] 2018-10-04 18:12
Hi @zyxue , we'll look into this a bit more. Might be something we can improve on the Nucleus codebase. Feel free to ping again if we don't give another updates in a few days.

**Comment by zyxue** [comment] 2018-10-05 18:36
Any update on this, please? Is there a quick way that I could do to work around this, maybe even temporarily? By the way, I am using the docker image of DeepVariant.

**Comment by depristo** [comment] 2018-10-05 18:43
@zyxue I believe a proper bugfix is going in soon and will be available when we release an updated version of 0.7. Since the ETA for that isn't *right now* you can fix this in a local build yourself by:

changing:
https://github.com/google/deepvariant/blob/3c43de4541c45673e30d14daef742fca68fdf69b/third_party/nucleus/io/sam_reader.cc#L448

so that you have:

```
    if (c->mtid < -1)
      return tf::errors::DataLoss(
          "Expected mtid >= 0 as mate is supposedly mapped: ",
          read_message->ShortDebugString());
    else if (c->mtid == -1) {
      mate_position->set_reference_name("*");
     } else {
      mate_position->set_reference_name(h->target_name[c->mtid]);
    }
    mate_position->set_position(c->mpos);
    mate_position->set_reverse_strand(bam_is_mrev(b));
```

which I believe should get your running again. You'll need to build DV from sources though.

**Comment by pgrosu** [comment] 2018-10-05 19:19
@depristo Out of curiosity under what conditions would `c->mtid < -1`?

**Comment by zyxue** [comment] 2018-10-09 21:20
I've made the suggested changes at https://github.com/zyxue/deepvariant/commit/cc09d6da17dcb700144cb3cd8dd2b7ece2c3ad86

```diff
diff --git a/third_party/nucleus/io/sam_reader.cc b/third_party/nucleus/io/sam_reader.cc
index d8c7cae..1b020be 100644
--- a/third_party/nucleus/io/sam_reader.cc
+++ b/third_party/nucleus/io/sam_reader.cc
@@ -445,11 +445,15 @@ tf::Status ConvertToPb(const bam_hdr_t* h, const bam1_t* b,
   // Set the mates map position if the mate is not unmapped.
   if (paired && !(c->flag & BAM_FMUNMAP)) {
     Position* mate_position = read_message->mutable_next_mate_position();
-    if (c->mtid < 0)
+    if (c->mtid < -1)
       return tf::errors::DataLoss(
           "Expected mtid >= 0 as mate is supposedly mapped: ",
           read_message->ShortDebugString());
-    mate_position->set_reference_name(h->target_name[c->mtid]);
+    else if (c->mtid == -1) {
+      mate_position->set_reference_name("*");
+    } else {
+      mate_position->set_reference_name(h->target_name[c->mtid]);
+    }
     mate_position->set_position(c->mpos);
     mate_position->set_reverse_strand(bam_is_mrev(b));
   }
```

What command do you use to build the docker image, please?

**Comment by akolesnikov** [comment] 2018-10-09 21:56
Use could build docker image with this command. It needs to be run from 'deepvariant' directory.
I used arbitrary values for PROJECT_ID and VERSION_NUMBER, you may replace them. 

PROJECT_ID=my-deepvariant-docker
VERSION_NUMBER=0.7.2  
gcloud builds submit   --project "${PROJECT_ID}"   --config cloudbuild.yaml   --substitutions TAG_NAME="${VERSION_NUMBER}"   --timeout 2h   .

**Comment by zyxue** [comment] 2018-10-09 22:05
Thanks for your command @akolesnikov, I've made it running. Also, I wonder how to build it locally, please?

**Comment by pgrosu** [comment] 2018-10-09 22:32
@zyxue Via `cloud-build-local`, below is a link to more information about it: 

https://cloud.google.com/cloud-build/docs/build-debug-locally

You will need to run the following command to install it:

`gcloud components install cloud-build-local`

**Comment by zyxue** [comment] 2018-10-09 22:58
Thanks for the info about cloud-build-local, @pgrosu.

FYI, my rebuilt image seems to be running properly now. Thank you for all your help!

**Comment by pgrosu** [comment] 2018-10-09 23:03
@zyxue Fantastic!  Feel free to ping us if you run into any other issues :)

Thanks,
~p

**Comment by zyxue** [comment] 2018-10-10 15:20
`make_example.py` seems to stuck after a long time of running at chr14,
```
I1010 11:12:31.993017 140686008715008 make_examples.py:825] Found 0 candidates in chr14:106812001-106813000 [1000 bp] [0.08s elapsed]
I1010 11:12:32.117227 140686008715008 make_examples.py:825] Found 1 candidates in chr14:106813001-106814000 [1000 bp] [0.12s elapsed]
I1010 11:12:32.204456 140686008715008 make_examples.py:825] Found 0 candidates in chr14:106814001-106815000 [1000 bp] [0.09s elapsed]
I1010 11:12:32.953804 140686008715008 make_examples.py:825] Found 12 candidates in chr14:106815001-106816000 [1000 bp] [0.75s elapsed]
```
The current timestamp is Oct 10 15:18:07 UTC 2018, so it's been over four hours, the cpu is still full, showing some computation is still going on. What could be possible reason please?

BTW, is it possible to parallelize make_example? It seems to only use one cpu at a time at the moment.

The command I used
```
sudo docker run \
  -v /home/${USER}:/home/${USER} \
  gcr.io/${PROJECT_NAME}/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/make_examples \
  --mode calling   \
  --ref "${REF}"   \
  --reads "${BAM}" \
  --examples "${OUTPUT_DIR}/examples.tfrecord.gz"
```

**Comment by pichuan** [comment] 2018-10-10 15:39
Hi @zyxue ,
in our case study example we used GPU parallel to run make_examples. You can see here for an example:
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-exome-case-study.md#run-make_examples

**Comment by zyxue** [comment] 2018-10-10 15:42
Thanks, @pichuan. Any suggestion about the long hangs, please? My BAM size is 8.5G.

**Comment by zyxue** [comment] 2018-10-10 16:21
Hi @pichuan, are you sure that doc uses GPU?

>For this case study, we used a 64-core non-preemptible instance with 128GiB and no GPU.

and I didn't see GPU configuration in the link to the command you posted?

**Comment by pichuan** [comment] 2018-10-10 16:48
Hi @zyxue 
since your questions seem to be no longer relevant to the original question, I'll close this comment. Internally we've made the code updates to address the original issue, and will come out in a next release. It also seems like the local changes that @depristo suggested works for you now.

Regarding your latest questions:
(1) There are areas in the genome that do take longer to run. This is usually areas where more reads piled up. We've made a lot of speed optimization over time, but it's still certainly true that will be regions that seem to run for much longer.
(2) Case study says "no GPU" in the sentence you quoted. Currently the case studies (WGS and WES) were both CPU only.
(3) For how to run with GPU, see this previous issue: https://github.com/google/deepvariant/issues/81

**Closed by pichuan** 2018-10-10 16:48 UTC

**Comment by zyxue** [comment] 2018-10-10 16:56
OK, thanks, you could close the ticket now.

I meant to ask whether `make_examples` could be parallelized with or without GPU. Your previous link and #81 only show GPU use `call_variants`. From my understanding call_variant loads the Inception model and do NN forward computation to do prediction, so it makes sense it leverages the parallel power from GPU. But make_examples just convert BAM into images.

Also, hanging for > 4hr doesn't seem to be caused only by deep pileup. I am currently rerunning make_examples, and will report in a new issue if it hangs again.

**Comment by pichuan** [comment] 2018-10-10 17:12
Ah I see.
The answer to your question: `make_examples` does not utilize GPUs. So it won't be faster if you run with GPUs.

And - if you have a region that hangs for a suspiciously long time, and if it's possible to share a reproducible setting that we can try, we'll be happy to use it to improve DeepVariant. Thank you!!

**Comment by zyxue** [comment] 2018-10-10 17:18
Thanks. I see what you mean, but it may be hard to have a reproducible example as the data is sensitive. I will certainly let you know if I have one in the future. I thought you might have some guesses, >4hrs to me looks like an infinite loop.

**Comment by akolesnikov** [comment] 2018-10-10 17:35
One possibility make_examples could take long time is if reads are too long. If your reads are greater than 250 there will be a slow down.

**Comment by zyxue** [comment] 2018-10-10 17:36
Thanks @akolesnikov, but read is only 50bp long in my example.

**Comment by akolesnikov** [comment] 2018-10-10 17:49
The other possibility as Pichuan mentioned could be that there are too many reads mapped to a window.

**Comment by pichuan** [comment] 2018-10-10 18:14
Hi @zyxue ,
my teammate @cmclean  pointed out that I might have confused you in my earlier comment ( https://github.com/google/deepvariant/issues/99#issuecomment-428622073 ) because I typed "GPU" parallel instead of "GNU" parallel. Sorry about that. :-/ I corrected it.

**Comment by zyxue** [comment] 2018-10-10 18:19
Ahh, I see. Thank you @pichuan, now it makes total sense! I will rerun, adapting the command from https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-exome-case-study.md#run-make_examples

**Comment by pgrosu** [comment] 2018-10-10 18:43
@zyxue I did an analysis a while ago, that posted at the following link:

[Generalized performance analysis between the versions](https://github.com/google/deepvariant/issues/50)

The thing that dominated the processing at that time was the aligner, and would require more surgery to determine possibilities for optimization even though it got recently updated with the [FastPassAligner](https://github.com/google/deepvariant/blob/r0.7/deepvariant/realigner/fast_pass_aligner.cc) - which would require re-profiling.  Basically a bunch of profiling tools would need to be built for you to then run, in order to determine for your scenario what the best optimization path would be.  You probably noticed the following lines in [make_examples.py](https://github.com/google/deepvariant/blob/r0.7/deepvariant/make_examples.py#L1150-L1153) regarding the core restriction:

```Python
    if options.n_cores != 1:
      errors.log_and_raise(
          'Currently only supports n_cores == 1 but got {}.'.format(
              options.n_cores), errors.CommandLineError)
```

Though there are possibilities around that like @pichuan mentioned.

~p

**Comment by zyxue** [comment] 2018-10-10 19:02
I have a couple of questions about https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-exome-case-study.md#run-make_examples,

1. how is `examples.tfrecord@${N_SHARDS}.gz` evaluated to become `examples.tfrecord-00006-of-00008.gz`
1. what does `--task {}` mean?

Could you please explain briefly how this command parallelize the processing? Is it done by scanning the bam serially and send each record to one of the ${N_SHARDS} processors?

**Comment by zyxue** [comment] 2018-10-10 19:19
Got it, seems `--task {}` gets the number from `seq`.

**Comment by pgrosu** [comment] 2018-10-10 19:37
@zyxue Regarding question 1, that is done in Nucleus in the following file (`io_utils.py`) in the `GenerateShardedFilenames()` function:

https://github.com/google/nucleus/blob/master/nucleus/util/io_utils.py#L80-L100

The specific lines are the following:

```Python
basename, num_shards, suffix = ParseShardedFileSpec(spec)
  files = []
  width = _ShardWidth(num_shards)
  format_str = '{{0}}-{{1:0{0}}}-of-{{2:0{0}}}{{3}}'.format(width)
  for i in range(num_shards):
    files.append(format_str.format(basename, i, num_shards, suffix))

  return files
```
Basically `ParseShardedFileSpec()` function uses the `SHARD_SPEC_PATTERN` to pattern-match against the following:

```Python
SHARD_SPEC_PATTERN = re.compile(R'((.*)\@(\d*[1-9]\d*)(?:\.(.+))?)')
```

Notice the @ symbol in the middle :)

Hope it helps,
~p

**Comment by pgrosu** [comment] 2018-10-10 23:11
@zyxue  Regarding how it knows about each region, I'm not sure how much do you want to know, since we can go into great detail here.  So the big picture of the control flow of the program for `make_examples.py` is this:

```
 main() -> 
   make_examples_runner() -> 
      processing_regions_from_options() -> (build_calling_regions, regions_to_process)
```

The `build_calling_regions()` first parses out relevant regions to include/exclude by calling a set of Nucleus helper functions to generate the ranges in this file:

https://github.com/google/deepvariant/blob/r0.7/third_party/nucleus/util/ranges.py

Then `build_calling_regions()` calls `regions_to_process()` where there is a key line that does a modulo to the [number of shards with task_id](https://github.com/google/deepvariant/blob/r0.7/deepvariant/make_examples.py#L659):

```Python
return (r for i, r in enumerate(partitioned) if i % num_shards == task_id)
```

As you know modulo allows the remainder to be bounded n-1 to the divisor, and thus the distribution of tasks is ideally uniform.  Ask more questions, since now you're getting into Computer Science concepts I know I can easily lose people in the details.

~[p]

**Comment by zyxue** [comment] 2018-10-10 23:19
Finally, make_examples finished successfully on an 8-core machine 🎉. Thank you for all your help!
