### ISSUE TITLE
How to merge Pacbio gvcfs?

### ISSUE THREAD

**Issue by rabbitdsy** [google/deepvariant#796] opened 2024-03-27 06:21 UTC
I generated Pacbio gvcfs of 30 samples using Deepvariant.
And now I want to merge those gvcfs using GLnexus, what --config should I choose? Is "DeepVariant" suitable?

            Name          CRC32C	Description
            gatk      1926883223	Joint-call GATK-style gVCFs
 gatk_unfiltered      4039280095	Merge GATK-style gVCFs with no QC filters or genotype revision
          xAtlas      1991666133	Joint-call xAtlas gVCFs
xAtlas_unfiltered       221875257	Merge xAtlas gVCFs with no QC filters or genotype revision
          weCall      2898360729	Joint-call weCall gVCFs
weCall_unfiltered      4254257210	Merge weCall gVCFs with no filtering or genotype revision
     DeepVariant      2932316105	Joint call DeepVariant whole genome sequencing gVCFs
  DeepVariantWGS      2932316105	Joint call DeepVariant whole genome sequencing gVCFs
  DeepVariantWES      1063427682	Joint call DeepVariant whole exome sequencing gVCFs
DeepVariantWES_MED_DP      2412618877	Joint call DeepVariant whole exome sequencing gVCFs, populating 0/0 DP from MED_DP instead of MIN_DP
DeepVariant_unfiltered      3285998180	Merge DeepVariant gVCFs with no QC filters or genotype revision
        Strelka2       395868656	[EXPERIMENTAL] Merge Strelka2 gVCFs with no QC filters or genotype revision

**Comment by AndrewCarroll** [comment] 2024-03-29 18:04
Hi @rabbitdsy For PacBio I recommend the DeepVariant present. I hope this answers your question.

**Comment by lucasbrambrink** [comment] 2024-04-03 18:10
Closing this issue for now, but don't hesitate to reopen if the issue is not resolved.

**Closed by lucasbrambrink** 2024-04-03 18:10 UTC
