### ISSUE TITLE
Segmentation fault DeepTrio v1.6 for ONT duo

### ISSUE THREAD

**Issue by dennishendriksen** [google/deepvariant#724] opened 2023-10-31 19:02 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md**:
Yes

**Describe the issue:**
DeepTrio v1.6 crashes reproducibly with a segmentation fault

**Setup**
  - Operating system:
Linux 3.10.0-1160.81.1.el7.x86_64
  - DeepVariant version:
1.6
  - Installation method (Docker, built from source, etc.):
Docker image converted to apptainer image which can be downloaded [here](https://downloads.molgeniscloud.org/downloads/vip/images/deepvariant_deeptrio-1.6.0.sif)
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
Nanopore data derived from [GIAB](https://github.com/genome-in-a-bottle/giab_data_indexes) HG002 mapped to GRCh38. The data subsampled resulting in a 80MB .bam file.

**Steps to reproduce:**
  - Command:
```
    local args=()
    args+=("--model_type" "ONT")
    args+=("--ref" "GCA_000001405.15_GRCh38_no_alt_analysis_set.fna")
    args+=("--reads_child" "i_am_my_father_HG002_validated.bam")
    args+=("--reads_parent1" "i_am_my_father_HG002_copy_validated.bam")
    args+=("--sample_name_child" "HG002")
    args+=("--sample_name_parent1" "HG002_copy")
    args+=("--output_gvcf_child" "i_am_my_father_HG002_chunk_8_snv.g.vcf.gz")
    args+=("--output_gvcf_parent1" "i_am_my_father_HG002_copy_chunk_8_snv.g.vcf.gz")
    args+=("--num_shards" "6")
    args+=("--regions" "regions_chunk_8.bed")
    args+=("--intermediate_results_dir" "intermediate_results")
    args+=("--output_vcf_child" "i_am_my_father_HG002_chunk_8_snv.vcf.gz")
    args+=("--output_vcf_parent1" "i_am_my_father_HG002_copy_chunk_8_snv.vcf.gz")

    ${CMD_DEEPVARIANT_DEEPTRIO} "${args[@]}"
```
content of .bed file:
```
$ cat regions_chunk_8.bed
chr9    0       138394717
```

stats of .bam file:
```
chr1    248956422       1319    0
chr2    242193529       929     0
chr3    198295559       749     0
chr4    190214555       1042    0
chr5    181538259       649     0
chr6    170805979       667     0
chr7    159345973       613     0
chr8    145138636       622     0
chr9    138394717       586     0
chr10   133797422       622     0
chr11   135086622       538     0
chr12   133275309       478     0
chr13   114364328       409     0
chr14   107043718       340     0
chr15   101991189       379     0
chr16   90338345        409     0
chr17   83257441        432     0
chr18   80373285        308     0
chr19   58617616        223     0
chr20   64444167        330     0
chr21   46709983        284     0
chr22   50818468        203     0
chrX    156040895       290     0
chrY    57227415        292     0
chrM    16569   11      0
chr1_KI270706v1_random  175055  4       0
chr1_KI270707v1_random  32032   1       0
chr1_KI270708v1_random  127682  1       0
chr1_KI270709v1_random  66860   28      0
chr1_KI270710v1_random  40176   1       0
chr1_KI270711v1_random  42210   0       0
chr1_KI270712v1_random  176043  3       0
chr1_KI270713v1_random  40745   0       0
chr1_KI270714v1_random  41717   0       0
chr2_KI270715v1_random  161471  3       0
chr2_KI270716v1_random  153799  3       0
chr3_GL000221v1_random  155397  6       0
chr4_GL000008v2_random  209709  6       0
chr5_GL000208v1_random  92689   0       0
chr9_KI270717v1_random  40062   1       0
chr9_KI270718v1_random  38054   0       0
chr9_KI270719v1_random  176845  6       0
chr9_KI270720v1_random  39050   2       0
chr11_KI270721v1_random 100316  1       0
chr14_GL000009v2_random 201709  6       0
chr14_GL000225v1_random 211173  48      0
chr14_KI270722v1_random 194050  3       0
chr14_GL000194v1_random 191469  5       0
chr14_KI270723v1_random 38115   1       0
chr14_KI270724v1_random 39555   1       0
chr14_KI270725v1_random 172810  2       0
chr14_KI270726v1_random 43739   0       0
chr15_KI270727v1_random 448248  4       0
chr16_KI270728v1_random 1872759 17      0
chr17_GL000205v2_random 185591  1       0
chr17_KI270729v1_random 280839  5       0
chr17_KI270730v1_random 112551  3       0
chr22_KI270731v1_random 150754  6       0
chr22_KI270732v1_random 41543   0       0
chr22_KI270733v1_random 179772  36      0
chr22_KI270734v1_random 165050  7       0
chr22_KI270735v1_random 42811   2       0
chr22_KI270736v1_random 181920  26      0
chr22_KI270737v1_random 103838  0       0
chr22_KI270738v1_random 99375   0       0
chr22_KI270739v1_random 73985   1       0
chrY_KI270740v1_random  37240   0       0
chrUn_KI270302v1        2274    0       0
chrUn_KI270304v1        2165    0       0
chrUn_KI270303v1        1942    0       0
chrUn_KI270305v1        1472    0       0
chrUn_KI270322v1        21476   0       0
chrUn_KI270320v1        4416    0       0
chrUn_KI270310v1        1201    0       0
chrUn_KI270316v1        1444    0       0
chrUn_KI270315v1        2276    0       0
chrUn_KI270312v1        998     0       0
chrUn_KI270311v1        12399   0       0
chrUn_KI270317v1        37690   0       0
chrUn_KI270412v1        1179    0       0
chrUn_KI270411v1        2646    0       0
chrUn_KI270414v1        2489    0       0
chrUn_KI270419v1        1029    0       0
chrUn_KI270418v1        2145    0       0
chrUn_KI270420v1        2321    0       0
chrUn_KI270424v1        2140    0       0
chrUn_KI270417v1        2043    0       0
chrUn_KI270422v1        1445    0       0
chrUn_KI270423v1        981     0       0
chrUn_KI270425v1        1884    0       0
chrUn_KI270429v1        1361    0       0
chrUn_KI270442v1        392061  4       0
chrUn_KI270466v1        1233    3       0
chrUn_KI270465v1        1774    0       0
chrUn_KI270467v1        3920    6       0
chrUn_KI270435v1        92983   1       0
chrUn_KI270438v1        112505  26      0
chrUn_KI270468v1        4055    0       0
chrUn_KI270510v1        2415    0       0
chrUn_KI270509v1        2318    0       0
chrUn_KI270518v1        2186    0       0
chrUn_KI270508v1        1951    0       0
chrUn_KI270516v1        1300    0       0
chrUn_KI270512v1        22689   0       0
chrUn_KI270519v1        138126  1       0
chrUn_KI270522v1        5674    0       0
chrUn_KI270511v1        8127    0       0
chrUn_KI270515v1        6361    0       0
chrUn_KI270507v1        5353    0       0
chrUn_KI270517v1        3253    0       0
chrUn_KI270529v1        1899    0       0
chrUn_KI270528v1        2983    0       0
chrUn_KI270530v1        2168    0       0
chrUn_KI270539v1        993     0       0
chrUn_KI270538v1        91309   2       0
chrUn_KI270544v1        1202    0       0
chrUn_KI270548v1        1599    0       0
chrUn_KI270583v1        1400    0       0
chrUn_KI270587v1        2969    0       0
chrUn_KI270580v1        1553    0       0
chrUn_KI270581v1        7046    0       0
chrUn_KI270579v1        31033   1       0
chrUn_KI270589v1        44474   0       0
chrUn_KI270590v1        4685    0       0
chrUn_KI270584v1        4513    0       0
chrUn_KI270582v1        6504    0       0
chrUn_KI270588v1        6158    0       0
chrUn_KI270593v1        3041    0       0
chrUn_KI270591v1        5796    0       0
chrUn_KI270330v1        1652    0       0
chrUn_KI270329v1        1040    0       0
chrUn_KI270334v1        1368    0       0
chrUn_KI270333v1        2699    4       0
chrUn_KI270335v1        1048    0       0
chrUn_KI270338v1        1428    0       0
chrUn_KI270340v1        1428    0       0
chrUn_KI270336v1        1026    1       0
chrUn_KI270337v1        1121    0       0
chrUn_KI270363v1        1803    0       0
chrUn_KI270364v1        2855    0       0
chrUn_KI270362v1        3530    0       0
chrUn_KI270366v1        8320    0       0
chrUn_KI270378v1        1048    0       0
chrUn_KI270379v1        1045    0       0
chrUn_KI270389v1        1298    0       0
chrUn_KI270390v1        2387    0       0
chrUn_KI270387v1        1537    0       0
chrUn_KI270395v1        1143    0       0
chrUn_KI270396v1        1880    0       0
chrUn_KI270388v1        1216    0       0
chrUn_KI270394v1        970     0       0
chrUn_KI270386v1        1788    0       0
chrUn_KI270391v1        1484    0       0
chrUn_KI270383v1        1750    0       0
chrUn_KI270393v1        1308    0       0
chrUn_KI270384v1        1658    0       0
chrUn_KI270392v1        971     0       0
chrUn_KI270381v1        1930    0       0
chrUn_KI270385v1        990     0       0
chrUn_KI270382v1        4215    0       0
chrUn_KI270376v1        1136    0       0
chrUn_KI270374v1        2656    0       0
chrUn_KI270372v1        1650    0       0
chrUn_KI270373v1        1451    0       0
chrUn_KI270375v1        2378    0       0
chrUn_KI270371v1        2805    0       0
chrUn_KI270448v1        7992    0       0
chrUn_KI270521v1        7642    0       0
chrUn_GL000195v1        182896  4       0
chrUn_GL000219v1        179198  2       0
chrUn_GL000220v1        161802  37      0
chrUn_GL000224v1        179693  6       0
chrUn_KI270741v1        157432  1       0
chrUn_GL000226v1        15008   48      0
chrUn_GL000213v1        164239  1       0
chrUn_KI270743v1        210658  3       0
chrUn_KI270744v1        168472  13      0
chrUn_KI270745v1        41891   0       0
chrUn_KI270746v1        66486   2       0
chrUn_KI270747v1        198735  2       0
chrUn_KI270748v1        93321   2       0
chrUn_KI270749v1        158759  0       0
chrUn_KI270750v1        148850  0       0
chrUn_KI270751v1        150742  4       0
chrUn_KI270752v1        27745   0       0
chrUn_KI270753v1        62944   1       0
chrUn_KI270754v1        40191   0       0
chrUn_KI270755v1        36723   0       0
chrUn_KI270756v1        79590   3       0
chrUn_KI270757v1        71251   2       0
chrUn_GL000214v1        137718  9       0
chrUn_KI270742v1        186739  9       0
chrUn_GL000216v2        176608  17      0
chrUn_GL000218v1        161147  3       0
chrEBV  171823  10      0
*       0       0       0
```
  - Error trace: (if applicable)
```
Fatal Python error: Segmentation fault

Current thread 0x00002b91584d7740 (most recent call first):
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deepvariant/very_sensitive_caller.py", line 67 in get_candidate_positions
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2047 in candidates_in_region
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1734 in process
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2838 in make_examples_runner
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deeptrio/make_examples.py", line 424 in main
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/absl_py/absl/app.py", line 258 in _run_main
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/absl_py/absl/app.py", line 312 in run
  File "/tmp/Bazel.runfiles_n9w2sjmt/runfiles/com_google_deepvariant/deeptrio/make_examples.py", line 434 in <module>
```
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
Unfortunately I cannot run Docker on my environment.

**Any additional context:**
The issue cannot be reproduced with `WES` model and Illumina WES data.

**Comment by kishwarshafin** [comment] 2023-11-01 18:35
hi @dennishendriksen,

Currently DeepTrio ONT is not supported officially. The code and a model exists but no documentation because we were not satisfied to make a official release. One of the reasons for the segfault could be because of low memory? Can you let us know the command you ran and the memory you have? Also, if easier then if you can share the bams then I can try to run it on our end and see what's happening.

**Comment by dennishendriksen** [comment] 2023-11-02 06:47
hi @kishwarshafin ,

Thank you for your quick reply. I was under the impression that DeepTrio ONT was supported due to the final comment in https://github.com/google/deepvariant/issues/715. Good to know that it is not officially supported yet.

> One of the reasons for the segfault could be because of low memory? Can you let us know the command you ran and the memory you have?

The command is listed above. I've tried running with 6 threads/24GB RAM and 6 threads/128GB RAM. Both result in the same segmentation fault.

> Also, if easier then if you can share the bams then I can try to run it on our end and see what's happening.
The .bams can be downloaded [here](https://downloads.molgeniscloud.org/downloads/vip/_dev/github/deepvariant_724/).

Thank you for looking into the issue,
Greetings,
@dennishendriksen

**Comment by kishwarshafin** [comment] 2023-11-20 01:05
@dennishendriksen ,

It seems like you are using identical data for child and parent. That would create a lot of examples given all of the sites would be identical. Can you please try with HG002, HG003/HG004 duo data in your setup and see if you are still facing the same issue.

You can download the data here:
```bash
mkdir -p input
HTTPDIR=https://storage.googleapis.com/deepvariant/ont-case-study-testdata

curl ${HTTPDIR}/HG002_R104_sup_merged.50x.chr20.bam > input/HG002_R104_sup_merged.50x.chr20.bam
curl ${HTTPDIR}/HG002_R104_sup_merged.50x.chr20.bam.bai > input/HG002_R104_sup_merged.50x.chr20.bam.bai

curl ${HTTPDIR}/HG003_R104_sup_merged.40x.chr20.bam > input/HG003_R104_sup_merged.40x.chr20.bam
curl ${HTTPDIR}/HG003_R104_sup_merged.40x.chr20.bam.bai > input/HG003_R104_sup_merged.40x.chr20.bam.bai

curl ${HTTPDIR}/HG004_R104_sup_merged.40x.chr20.bam > input/HG004_R104_sup_merged.40x.chr20.bam
curl ${HTTPDIR}/HG004_R104_sup_merged.40x.chr20.bam.bai > input/HG004_R104_sup_merged.40x.chr20.bam.bai
```

I would **strongly** suggest running it on a small chunk as runtime was one of the issues we faced with DeepTrio ONT mode.

**Comment by kishwarshafin** [comment] 2023-11-20 01:06
Also, I can confirm that your data caused out of memory (OOM) issue. Can you tell us which basecaller version you used to basecall your ONT data?

**Comment by dennishendriksen** [comment] 2023-11-20 06:13
@kishwarshafin,

Thank you for diving into this issue. The data was very likely derived from the [GIAB HG002 ONT Ultra-long UCSC sample](https://ftp.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/UCSC_Ultralong_OxfordNanopore_Promethion/README_ONT-UL_UCSC_HG002.md) which base-called reads with guppy (version 3.2.5). We used minimap for alignment.

I'll update our test to use different data for child and parent. Unfortunately I'm a bit pressed for time at the moment, but will do so on the first available occassion.

**Comment by kishwarshafin** [comment] 2023-11-20 17:02
@dennishendriksen ,

1) Totally understandable, please give it a try when you have time and let us know if you are still facing issues. 
2) Those are R9.4 data. The ONT model only supports R10.4 simplex or duplex. R9.4 has elevated error rate that causes a ton of candidates. DeepTio wouldn't work with R9 data.

I am closing this issue. Feel free to reopen in the future.

**Closed by kishwarshafin** 2023-11-20 17:02 UTC
