### ISSUE TITLE
test_make_labeler_ref fail due to mock data

### ISSUE THREAD

**Issue by qili93** [google/deepvariant#154] opened 2019-02-14 10:40 UTC
Hi There,

I compiled the whole deepvariant on ppc64le with IBM Advance Toolchain 11.0 with all its dependencies on RHEL 7.5. And most test cases passed, but only 2 test cases failed.

Found one root cause today of "//deepvariant/labeler:haplotype_labeler_test" as following. While suppose this is not related to platform/environment issue? Would you please kindly help to comment how to fix this error?

The detailed root cause please refer to the comments inline in the code, thanks in advance :)

In the test file of "deepvariant/labeler/haplotype_labeler_test.py", the function of "test_make_labeler_ref"

```python
  def test_make_labeler_ref(self, candidates, truths, expected_start,
                            expected_end, bufsize):
    expected_bases = 'A' * (expected_end - expected_start)

    ## generate a Mock object instead of real object of InMemoryFastaReader
    labeler = _make_labeler()
    labeler._ref_reader.query.return_value = expected_bases

    labeler_ref = labeler.make_labeler_ref(candidates, truths, bufsize=bufsize)

    labeler._ref_reader.query.assert_called_once_with(
        ranges.make_range('20', expected_start, expected_end))
    self.assertEqual(labeler_ref.start, expected_start)
    self.assertEqual(labeler_ref.end, expected_end)
    self.assertEqual(
        labeler_ref.bases(expected_start, expected_end), expected_bases)
```

So when in the file of "deepvariant/labeler/haplotype_labeler.py", the function of "make_labeler_ref" will generate an incorrect output as "self._ref_reader" is mock

```python
  def make_labeler_ref(self, candidates, true_variants, bufsize=20):
    all_variants = candidates + true_variants
    contig = all_variants[0].reference_name
    start = min(x.start for x in all_variants)
    end = max(x.end for x in all_variants)

    ## always output contig_nbp = 1, as self._ref_reader is Mock object
    ## in fact contig_nbp=[<MagicMock name='mock.contig().n_bases' id='70366068929488'>]
    ## change the above type to int becomes "1", then the region.end will be 1 to cause test fail
    contig_nbp = self._ref_reader.contig(contig).n_bases 
    region = ranges.make_range(contig, max(start - 1, 0),
                               min(end + bufsize, contig_nbp))
    ref_bases = self._ref_reader.query(region)
    return ReferenceRegion(ref_bases, start=region.start)
```

**Comment by pichuan** [comment] 2019-02-18 06:12
Hi @qili93 
can you paste your error messages here?

Many of the recent test errors reported by users are related to the fact that we didn't pin our intervaltree version in our last release, and intervaltree v3 came out and had some API changes...

So, the first thing to try is to change this line:
https://github.com/google/deepvariant/blob/r0.7/run-prereq.sh#L86
to:
```
pip install --user 'intervaltree==2.1.0'
```
and see if the tests will pass? Please let me know. Thanks.

**Comment by qili93** [comment] 2019-02-18 10:49
Hi @pichuan,

The "intervaltree==2.1.0" resolved my another failed case of "//deepvariant:make_examples_test". While "//deepvariant/labeler:haplotype_labeler_test" still failed. And the following is the error message that I got:

======================================================================
FAIL: test_make_labeler_ref(truths=[], expected_end=21, expected_start=9, bufsize=0, candidates=[reference_bases: "A"
alternate_bases: "C"
end: 11
reference_name: "20"
start: 10
, reference_bases: "A"
alternate_bases: "C"
end: 21
reference_name: "20"
start: 20
]) (__main__.HaplotypeLabelerClassUnitTest)
test_make_labeler_ref(truths=[], expected_end=21, expected_start=9, bufsize=0, candidates=[reference_bases: "A"
alternate_bases: "C"
end: 11
reference_name: "20"
start: 10
, reference_bases: "A"
alternate_bases: "C"
end: 21
reference_name: "20"
start: 20
]) (__main__.HaplotypeLabelerClassUnitTest)
test_make_labeler_ref(truths=[], expected_end=21, expected_start=9, bufsize=0, candidates=[reference_bases: "A"
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/dc155a991b1776fcc65387121539d20a/execroot/com_google_deepvariant/bazel-out/ppc-opt/bin/deepvariant/labeler/haplotype_labeler_test.runfiles/absl_py/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/root/.cache/bazel/_bazel_root/dc155a991b1776fcc65387121539d20a/execroot/com_google_deepvariant/bazel-out/ppc-opt/bin/deepvariant/labeler/haplotype_labeler_test.runfiles/absl_py/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "/root/.cache/bazel/_bazel_root/dc155a991b1776fcc65387121539d20a/execroot/com_google_deepvariant/bazel-out/ppc-opt/bin/deepvariant/labeler/haplotype_labeler_test.runfiles/absl_py/absl/testing/parameterized.py", line 256, in bound_param_test
    test_method(self, **testcase_params)
  File "/root/.cache/bazel/_bazel_root/dc155a991b1776fcc65387121539d20a/execroot/com_google_deepvariant/bazel-out/ppc-opt/bin/deepvariant/labeler/haplotype_labeler_test.runfiles/com_google_deepvariant/deepvariant/labeler/haplotype_labeler_test.py", line 371, in test_make_labeler_ref
    ranges.make_range('20', expected_start, expected_end))
  File "/home/qilibj/inst/lib/python2.7/site-packages/mock/mock.py", line 948, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/home/qilibj/inst/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/root/.cache/bazel/_bazel_root/dc155a991b1776fcc65387121539d20a/execroot/com_google_deepvariant/bazel-out/ppc-opt/bin/deepvariant/labeler/haplotype_labeler_test.runfiles/six_archive/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: query(reference_name: "20"
start: 9
end: 21
)
Actual call: query(reference_name: "20"
start: 9
end: 1 <== this ends with 1 due to the mock object returns 1
)

**Comment by pichuan** [comment] 2019-02-18 18:57
Hi @qili93 
I wasn't able to reproduce your error. Here is what I did (on a Ubuntu 16 machine)
```
git clone https://github.com/google/deepvariant.git
cd deepvariant
bazel test -c opt //deepvariant/labeler:haplotype_labeler_test
```

And this passed for me.

Currently your setting might be outside our actively supported platform. If you can suggest a patch (that wouldn't break other settings), we're happy to make a fix internally as well. But we don't currently have extra bandwidth to look into this issue.

One more question for you (it'll really help us understand your need and why you need to build) -- Were you able to run with our prebuilt docker container image? If so, what was the reason that you decided to build on your own? 

Thank you!

**Comment by pgrosu** [comment] 2019-02-18 20:50
Wait @pichuan, are you saying you're not even going to have a DeepVariant app at the Google Play store?  That would be sooo cool ;)

**Comment by qili93** [comment] 2019-02-19 03:01
Thanks @pichuan :)

Finally I got the root cause of this issue, it seem the return number of min on Ubuntu and RHEL are different. I tried to run the following commands on both python2:

The output of **Ubuntu** (on X86) is:
```
>>> import mock
>>>
>>> expected_start=9
>>> expected_end=21
>>> bufsize=0
>>> expected_bases = 'A' * (expected_end - expected_start)
>>>
>>> start=10
>>> end=21
>>> contig='20'
>>> ref_reader = mock.MagicMock()
>>> ref_reader.query.return_value = expected_bases
>>> contig_nbp = ref_reader.contig(contig).n_bases
>>> res = min(end + bufsize, contig_nbp)
>>> res
21
```

And then I tried the same code on **RHEL 7.5 (both on X86 and Power**, the output is:

```
>>> import mock
>>>
>>> expected_start=9
>>> expected_end=21
>>> bufsize=0
>>> expected_bases = 'A' * (expected_end - expected_start)
>>>
>>> start=10
>>> end=21
>>> contig='20'
>>> ref_reader = mock.MagicMock()
>>> ref_reader.query.return_value = expected_bases
>>> contig_nbp = ref_reader.contig(contig).n_bases
>>> res = min(end + bufsize, contig_nbp)
>>> res
<MagicMock name='mock.contig().n_bases' id='140373647899088'>
>>> int(res)
1
```

And I accidentally run the above command with Python3, and it throw the following error:

```
>>> res = min(end + bufsize, contig_nbp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'MagicMock' and 'int'
``` 

So propose to fix the above type conversion if you have plan to support RHEL or upgrade to Python 3 in the future :)

**Comment by pichuan** [comment] 2019-02-19 03:14
Hi @qili93 
Thank you for looking into this! We have an internal issue to track this. I don't have a timeline for this now, but will let you know when we have more clear plans. 
Closing this issue now.

**Closed by pichuan** 2019-02-19 03:14 UTC

**Comment by cmclean** [comment] 2019-02-20 22:11
Hi @qili93 ,

This is a bug that the mock ref_reader does not have its 'contig' function return value populated. This has been fixed internally and will be part of the next release.

In the meantime, if you want to modify your own version of the code you need to do the following:

In deepvariant/labeler/BUILD, in the "haplotype_labeler_test", add the following dependency:
"//third_party/nucleus/protos:reference_py_pb2",

In deepvariant/labeler/haplotype_labeler_test.py, include the following import and mock call:

### Insert at line 42
from third_party.nucleus.protos import reference_pb2

### Insert at line 346
labeler._ref_reader.contig.return_value = reference_pb2.ContigInfo(name='20', n_bases=50)

**Comment by qili93** [comment] 2019-03-04 09:52
Thanks so much @cmclean :)
