### ISSUE TITLE
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

### ISSUE THREAD

**Issue by scfurl** [google/deepvariant#640] opened 2023-05-02 21:05 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**: YES

**Describe the issue:**
(A clear and concise description of what the issue is.)
CANNOT RUN EXAMPLE DATA USING A SINGULARITY CONTAINER - GETTING AN ERROR: RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem.

**Setup**
  - Operating system:  Ubuntu 18.04 (bionic)
  - DeepVariant version: 1.5.0
  - Installation method (Docker, built from source, etc.): SINGULARITY sif made as follows:
BIN_VERSION="1.5.0"
singularity pull deepvariant.sif docker://google/deepvariant:"${BIN_VERSION}"
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
EXAMPLE DATA PROVIDED

**Steps to reproduce:**
  - Command:

INPUT_DIR="${PWD}/quickstart-testdata"
OUTPUT_DIR="${PWD}/quickstart-output"

singularity exec --bind "${INPUT_DIR}":"/input","${OUTPUT_DIR}":"/output",/usr/lib/locale/:/usr/lib/locale/ \
  /fh/fast/furlan_s/grp/sifs/deepvariant.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz

  - Error trace: (if applicable) SEE BELOW

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

YES THIS IS WITH THE QUICK START EXAMPLE

**Any additional context:**

Message:

2023-05-02 14:40:43.757041: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0502 14:40:56.961649 140501830911808 run_deepvariant.py:364] Re-using the directory for intermediate results in /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p

***** Intermediate results will be written to /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p in docker. ****

***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/make_examples.tfrecord@1.gz" --channels "insert_size" --gvcf "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

2023-05-02 14:41:58.436801: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0502 14:42:09.254817 140040320145216 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0502 14:42:09.301696 140040320145216 make_examples_core.py:257] Preparing inputs
I0502 14:42:09.324342 140040320145216 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0502 14:42:09.328370 140040320145216 make_examples_core.py:257] Common contigs are ['chr20']
I0502 14:42:09.424478 140040320145216 make_examples_core.py:257] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2023-05-02 14:42:09.427029: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
I0502 14:42:09.448862 140040320145216 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0502 14:42:09.665297 140040320145216 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0502 14:42:09.668077 140040320145216 make_examples_core.py:257] Writing gvcf records to /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/gvcf.tfrecord-00000-of-00001.gz
I0502 14:42:10.668800 140040320145216 make_examples_core.py:257] Writing examples to /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/make_examples.tfrecord-00000-of-00001.gz
I0502 14:42:10.669139 140040320145216 make_examples_core.py:257] Overhead for preparing inputs: 1 seconds
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>
    app.run(main)
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 186, in main
    make_examples_core.make_examples_runner(options)
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2189, in make_examples_runner
    region_example_shape = region_processor.writes_examples_in_region(
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1187, in writes_examples_in_region
    for example in self.create_pileup_examples(
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1793, in create_pileup_examples
    pileup_images = self.pic.create_pileup_images(
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 534, in create_pileup_images
    pileup = _pileup_for_pair_of_alts(alts)
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 486, in _pileup_for_pair_of_alts
    ref_image = self.build_pileup(
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 435, in build_pileup
    build_pileup_for_one_sample(reads_for_samples[i], sample))
  File "/fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/Bazel.runfiles_24e7ffgp/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 355, in build_pileup_for_one_sample
    rows = ([self._encoder.encode_reference(refbases)] *
ImportError: numpy.core.multiarray failed to import
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/make_examples.tfrecord@1.gz --channels insert_size --gvcf /fh/scratch/delete90/furlan_s/targ_reseq/230117_Sami/AML_1101_merge/tmp_dir/tmpzz53zv8p/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real	1m18.483s
user	0m6.533s
sys	0m5.261s

**Comment by scfurl** [comment] 2023-05-02 21:05
Thanks for looking!

**Comment by MariaNattestad** [comment] 2023-05-03 21:05
Thanks for the question!
I tried to run the quick start on a GCP VM but 

One hint from the [documentation](https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility) that the error links to is that it could have to do with numpy versions.

Can you try `pip install numpy --upgrade` and then rerun?

**Comment by scfurl** [comment] 2023-05-04 14:47
Thank you for the prompt reply!

I am admittedly a little confused.  I am running deep variant using a singularity container, so my local numpy version shouldn't matter right?

I did try creating a container using 1.4.0 and it worked...

**Comment by pichuan** [comment] 2023-05-04 19:47
I was curious so I also poked around.

I also wasn't able to reproduce the issue. And I also agree that the version in Singularity container should be the one that's used.

```
$ singularity --version
singularity version 3.7.0
```

```
BIN_VERSION="1.5.0"
singularity pull deepvariant.sif docker://google/deepvariant:"${BIN_VERSION}"
```

```
$ singularity exec deepvariant.sif pip freeze | grep numpy
numpy==1.24.2
```

```
$ singularity shell deepvariant.sif
Singularity> python -c "import numpy; print(numpy.__version__)"
1.24.2
```

On this machine I'm on, I have an older version:

```
$ python3 -c "import numpy; print(numpy.__version__)"
1.17.4
```

But when running with Singularity, it seems to be seeing the one in the container:

```
$ singularity exec --bind "${INPUT_DIR}":"/input","${OUTPUT_DIR}":"/output",/usr/lib/locale/:/usr/lib/locale/ deepvariant.sif python -c "import numpy; print(numpy.__version__)"
1.24.2
```

I also don't have any answer to this.. :thinking: 

@scfurl Glad to hear that at least 1.4.0 works for you.

**Comment by pgrosu** [comment] 2023-05-11 01:39
@pichuan is correct.  The numpy version being run is the one from inside the Singularity image.  Based on the [Singularity source code](https://github.com/sylabs/singularity/blob/main/cmd/internal/cli/singularity.go#L596-L601) it is using the Go [os/exec](https://pkg.go.dev/os/exec#pkg-overview) package.  An exec command will overwrite the whole current process to execute another program, which means the numpy version has to come from the image itself.

**Comment by nvnieuwk** [comment] 2023-05-16 14:56
I am running into the same issue when running on a small CRAM file only. (I'm also using docker instead of singularity). The CRAM file only contains this region: `chr22:0-40001`. Could the file size be a factor here?

**Comment by nvnieuwk** [comment] 2023-05-16 14:59
FYI:
The command output is
```bash
           RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError
         section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .                       
           Traceback (most recent call last):                                                                                                                                  
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 196, in <module>                                           
               app.run(main)                                                                                                                                                   
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/absl_py/absl/app.py", line 312, in run                                                                                
               _run_main(main, args)                                                                                                                                           
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/absl_py/absl/app.py", line 258, in _run_main                                                                          
               sys.exit(main(argv))                                                                                                                                            
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 186, in main                                               
               make_examples_core.make_examples_runner(options)                                                                                                                
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2189, in make_examples_runner                         
               region_example_shape = region_processor.writes_examples_in_region(                                                                                              
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1187, in writes_examples_in_region                    
               for example in self.create_pileup_examples(                                                                                                                     
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1793, in create_pileup_examples                       
               pileup_images = self.pic.create_pileup_images(                                                                                                                  
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 534, in create_pileup_images                                
               pileup = _pileup_for_pair_of_alts(alts)                                                                                                                         
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 486, in _pileup_for_pair_of_alts                            
               ref_image = self.build_pileup(                                                                                                                                  
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 435, in build_pileup                                        
               build_pileup_for_one_sample(reads_for_samples[i], sample))                                                                                                      
             File "/tmp/Bazel.runfiles_gd__toh4/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 355, in build_pileup_for_one_sample                         
               rows = ([self._encoder.encode_reference(refbases)] *                                                                                                            
           ImportError: numpy.core.multiarray failed to import                                                                                                                 
           I0516 14:57:26.170286 139707932989248 make_examples_core.py:257] Task 0/2: Writing example info to ./make_examples.tfrecord-00000-of-00002.gz.example_info.json     
           I0516 14:57:26.170386 139707932989248 make_examples_core.py:2273] example_shape = None                                                                              
           I0516 14:57:26.170525 139707932989248 make_examples_core.py:2274] example_channels = [1, 2, 3, 4, 5, 6, 19]                                                         
           I0516 14:57:26.170763 139707932989248 make_examples_core.py:257] Task 0/2: Found 0 candidate variants                                                               
           I0516 14:57:26.170813 139707932989248 make_examples_core.py:257] Task 0/2: Created 0 examples                                                                       
           parallel: This job failed:                                                                                                                                          
           /opt/deepvariant/bin/make_examples --mode calling --ref genome.fasta --reads test.paired_end.sorted.cram --examples ./make_examples.tfrecord@2.gz --channels        
         insert_size --gvcf ./gvcf.tfrecord@2.gz --regions genome.bed --task 1     
```

And the command is
```bash
/opt/deepvariant/bin/run_deepvariant \
    --ref=genome.fasta \
    --reads=test.paired_end.sorted.cram \
    --output_vcf=test_out.vcf.gz \
    --output_gvcf=test_out.g.vcf.gz \
    --model_type=WGS  \
    --regions genome.bed \
    --intermediate_results_dir=. \
    --num_shards=2
```

**Comment by pichuan** [comment] 2023-05-16 17:08
@nvnieuwk Does it mean you only encounter this issue when running on a small region? Does the same setting work when you run something like the Quick Start?

**Comment by pgrosu** [comment] 2023-05-16 20:04
@nvnieuwk Are you sure you are running inside the Docker image?  I listed all the files regarding the `/tmp` folder inside the Docker container (which all must be the same for all users), and I cannot find the ones shown above:

```Bash
root@0f98b9adcd2d:/# /opt/deepvariant/bin/run_deepvariant --version
DeepVariant version 1.5.0
root@0f98b9adcd2d:/# ls /tmp/Bazel.runfiles_gd__toh4/
ls: cannot access '/tmp/Bazel.runfiles_gd__toh4/': No such file or directory
root@0f98b9adcd2d:/# find /tmp
/tmp
/tmp/tmpb20xyssf
/tmp/__pycache__
/tmp/__pycache__/__autograph_generated_file7y1wd6da.cpython-38.pyc
/tmp/__pycache__/__autograph_generated_fileilucivm5.cpython-38.pyc
/tmp/tmp0y_1vxbg
root@0f98b9adcd2d:/# find  | grep bazel
./usr/local/lib/python3.8/dist-packages/absl/testing/_bazelize_command.py
./usr/local/lib/python3.8/dist-packages/absl/testing/__pycache__/_bazel_selected_py3.cpython-38.pyc
./usr/local/lib/python3.8/dist-packages/absl/testing/__pycache__/_bazelize_command.cpython-38.pyc
./usr/local/lib/python3.8/dist-packages/absl/testing/_bazel_selected_py3.py
root@0f98b9adcd2d:/#
```

I remember seeing things like `/tmp/Bazel.runfiles_gd__toh4/` only when I compiled DeepVariant from scratch.  It's a tricky task to get it compiled, so I just wanted to be sure you didn't mix up the session you might be running in.

**Comment by nvnieuwk** [comment] 2023-05-17 05:56
> @nvnieuwk Does it mean you only encounter this issue when running on a small region? Does the same setting work when you run something like the Quick Start?

Yes I've tried it with a CRAM file that contains the whole chromosome 21 and this works, but when I use a BAM with the subset `chr22:0-40001`, I get the earlier mentioned error

**Comment by pichuan** [comment] 2023-05-17 06:30
@nvnieuwk from my understanding, I would be surprised if the numpy error is related to the region. I feel that might be a red herring. Unfortunately I don't have a clear answer for you because I can't reproduce your exact setting.
If you think it can still be related to the small region, the next thing I'd suggest you try is: Start from the setting that worked before (CRAM file that contains the whole chromosome 21). First confirm that still works, and just change one thing: restrict to a smaller region and see if that still works or fails with the numpy error again.

Sorry that I don't have better suggestions for now.

**Comment by nvnieuwk** [comment] 2023-05-17 06:44
Thank you for the suggestions, I've tried running the chr21 CRAM in the same setup and they didn't work here either. Something must be wrong with the setup of that repository, I'll check the differences with the repo where deepvariant worked :)

**Comment by pgrosu** [comment] 2023-05-17 06:57
Hi Nicolas,

Aside from Pi-Chuan's recommendation -- which I think is very good to try -- see if also doing these two steps yield any results (which might make the region issue go away naturally):

1) To minimize the number of working variables, first let's try Docker by itself.  This would be without NextFlow, just by using the command-line (in a terminal Bash session) replicating exactly the [DeepVariant QuickStart](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md).  If it does work, then the next step should be easier to configure.

2) If step 1 works, then you can customize a NextFlow pipeline based on the configuration of step one, using [containerOptions](https://www.nextflow.io/docs/latest/process.html#containeroptions), which I'm sure you already know or a custom process.  I am assuming your NextFlow implementation allows you to create custom pipelines, which do not add any default volume mounts or environment variables.

Paul

**Comment by nvnieuwk** [comment] 2023-05-17 07:22
Thanks for all the suggestions. I've succesfully ran the quickstart on my system, but am still unable to run it via nextflow. I've tried it on gitpod right now and it works there (in the same nextflow setup). Very weird...

**Comment by pichuan** [comment] 2023-05-18 06:21
Hi @nvnieuwk , it seems like you're able to find a working setup now. It seems like @scfurl also found that 1.4.0 worked. 

I'll close this issue for now given that we don't have a reproducible setting on our side to fix the issue.

**Closed by pichuan** 2023-05-18 06:21 UTC
