### ISSUE TITLE
The TF examples has image/format 'None'

### ISSUE THREAD

**Issue by luisas** [google/deepvariant#52] opened 2018-03-06 11:33 UTC
Hi, 

when I run deepVariant, using 2 shards for the makeExample, the call_variants fails.
The error is : 
```
ValueError: The TF examples in shardedExamples/examples.tfrecord@2.gz has image/format 'None' (expected 'raw') which means you might need to rerun make_examples to genenerate the examples again.
```

One confusing thing that happens: 
The error only shows up only when running with my own BAM file ( mapped to hg19 ) but when I run deepVariant with the example BAM file provided by Google this does not happen.

I would appreciate any kind of help.

Thanks a lot, 
Luisa

**Comment by depristo** [comment] 2018-03-06 14:50
Can you produce a small snippet of your BAM file and an associated command line that reproduces the issue and share it with us? We'd be happy to debug but it'd be great to have a simple example that causes the problem.

**Comment by luisas** [comment] 2018-03-07 10:36
The Bam file was downloaded from

```
https://www.encodeproject.org/files/ENCFF528VXT/@@download/ENCFF528VXT.bam
```

Then, since it was missing the @RG line, I added it manually just to test using picard:
```
java -jar /picard.jar AddOrReplaceReadGroups I=ENCFF528VXT.bam O=ENCFF528VXT.bam RGID=4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=20
```
The output of runninng
```
samtools view -H ENCFF528VXT.bam
```
is the following :
```
@HD VN:1.5 SO:coordinate
@SQ SN:chr1 LN:249250621
@SQ SN:chr2 LN:243199373
@SQ SN:chr3 LN:198022430
@SQ SN:chr4 LN:191154276
@SQ SN:chr5 LN:180915260
@SQ SN:chr6 LN:171115067
@SQ SN:chr7 LN:159138663
@SQ SN:chr8 LN:146364022
@SQ SN:chr9 LN:141213431
@SQ SN:chr10 LN:135534747
@SQ SN:chr11 LN:135006516
@SQ SN:chr12 LN:133851895
@SQ SN:chr13 LN:115169878
@SQ SN:chr14 LN:107349540
@SQ SN:chr15 LN:102531392
@SQ SN:chr16 LN:90354753
@SQ SN:chr17 LN:81195210
@SQ SN:chr18 LN:78077248
@SQ SN:chr19 LN:59128983
@SQ SN:chr20 LN:63025520
@SQ SN:chr21 LN:48129895
@SQ SN:chr22 LN:51304566
@SQ SN:chrX LN:155270560
@SQ SN:chrY LN:59373566
@SQ SN:chrM LN:16571
@RG ID:4 LB:lib1 PL:illumina SM:20 PU:unit1
@PG ID:bwa PN:bwa VN:0.7.10-r789 CL:/usr/local/bin/bwa0.7.10 sampe -P reference_files/male.hg19.fa.gz ENCFF182MTO.sai ENCFF949NMY.sai ENCFF182MTO.fastq.gz ENCFF949NMY.fastq.gz
@PG ID:MarkDuplicates PN:MarkDuplicates VN:1.92() CL:net.sf.picard.sam.MarkDuplicates INPUT=[ENCFF182MTOENCFF949NMY.raw.srt.filt.srt.bam] OUTPUT=ENCFF182MTOENCFF949NMY.raw.srt.dupmark.bam METRICS_FILE=ENCFF182MTOENCFF949NMY.raw.srt.dup.qc REMOVE_DUPLICATES=false ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 READ_NAME_REGEX=[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).* OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
```

I uploaded the modified file on this public s3 bucket so you can have a look on it directly from here : 
s3://dv-testfiles/hg19.fa
s3://dv-testfiles/ENCFF528VXT.bam

There you can find the genome I used for running too.

Before i created the needed files ( done in the following docker container https://hub.docker.com/r/luisas/samtools/ ) :
```
samtools index ENCFF528VXT.bam
samtools faidx hg19.fa
bgzip -c -i hg19.fa > hg19.fa.gz
samtools faidx "hg19.fa.gz"
```

Then I ran in the docker container you provide :
```
mkdir shardedExamples

time seq 0 1 | parallel --eta --halt 2 python /opt/deepvariant/bin/make_examples.zip --mode calling --ref hg19.fa --regions chr20:10,000,000-10,010,000 --reads ENCFF528VXT.bam --examples shardedExamples/examples.tfrecord@2.gz --task {}

```

```
/opt/deepvariant/bin/call_variants --outfile call_variants_output.tfrecord --examples shardedExamples/examples.tfrecord@2.gz --checkpoint dv2/models/model.ckpt
```

and here the error output:
```
WARNING: Logging before flag parsing goes to stderr.
W0307 09:54:53.415692 140603705038592 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
Traceback (most recent call last):
File "/tmp/Bazel.runfiles_vZjmn7/runfiles/genomics/deepvariant/call_variants.py", line 410, in module
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "/tmp/Bazel.runfiles_vZjmn7/runfiles/genomics/deepvariant/call_variants.py", line 401, in main
batch_size=FLAGS.batch_size)
File "/tmp/Bazel.runfiles_vZjmn7/runfiles/genomics/deepvariant/call_variants.py", line 324, in call_variants
examples_filename, example_format))
ValueError: The TF examples in shardedExamples/examples.tfrecord@2.gz has image/format 'None' (expected 'raw') which means you might need to rerun make_examples to genenerate the examples again.
```

Thanks a lot, 
Luisa

**Comment by depristo** [comment] 2018-03-07 15:53
Thanks Luisa! It seems those s3 files aren't public:

wget http://dv-testfiles.s3.amazonaws.com/ENCFF528VXT.bam
--2018-03-07 07:28:01--  http://dv-testfiles.s3.amazonaws.com/ENCFF528VXT.bam
Resolving dv-testfiles.s3.amazonaws.com (dv-testfiles.s3.amazonaws.com)... 52.218.52.113
Connecting to dv-testfiles.s3.amazonaws.com (dv-testfiles.s3.amazonaws.com)|52.218.52.113|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-07 07:28:01 ERROR 403: Forbidden.

**Comment by luisas** [comment] 2018-03-07 16:00
Thank a lot for your answer. Now the are public for real!

Luisa

2018-03-07 16:53 GMT+01:00 Mark DePristo <notifications@github.com>:

**Comment by cmclean** [comment] 2018-03-07 18:34
This looks like a duplicate of https://github.com/google/deepvariant/issues/27 -- some of your data shards are empty (no examples were created in the shard), which was not being handled properly and was fixed in DeepVariant 0.5.1. If you upgrade to use that release version does the problem remain?

**Comment by pprieto** [comment] 2018-03-07 21:21
Yes, I was having the same issue using the old version 0.4.1, when I change to 0.5.1:
```
gcr.io/deepvariant-docker/deepvariant:0.4.1
```

I get this error instead:
```
  WARNING: Logging before flag parsing goes to stderr.
  W0307 21:19:10.482634 140039107020544 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
  W0307 21:19:10.488955 140039107020544 call_variants.py:299] Unable to read any records from shardedExamples/examples.tfrecord@64.gz. Output will contain zero records.
  Traceback (most recent call last):
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/genomics/deepvariant/call_variants.py", line 391, in <module>
      tf.app.run()
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
      _sys.exit(main(_sys.argv[:1] + flags_passthrough))
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/genomics/deepvariant/call_variants.py", line 382, in main
      batch_size=FLAGS.batch_size)
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/genomics/deepvariant/call_variants.py", line 317, in call_variants
      predictions = model.create(images, 3, is_training=False)['Predictions']
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/genomics/deepvariant/modeling.py", line 360, in create
      images, num_classes, create_aux_logits=False, is_training=is_training)
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/org_tensorflow_slim/nets/inception_v3.py", line 483, in inception_v3
      depth_multiplier=depth_multiplier)
    File "/tmp/Bazel.runfiles_i7Wypy/runfiles/org_tensorflow_slim/nets/inception_v3.py", line 104, in inception_v3_base
      net = slim.conv2d(inputs, depth(32), [3, 3], stride=2, scope=end_point)
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
      return func(*args, **current_args)
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1011, in convolution
      input_rank)
  ValueError: ('Convolution not supported for input with rank', 1)
```
Have you seen this error before?

**Comment by pgrosu** [comment] 2018-03-07 21:36
I was suspicious something else might be the issue.  So I did a simple test to see if there is an issue with Luisa's BAM file, and noticed that I cannot even create an index - which would naturally make even the prerequisite `make_examples` not complete properly:

```
paul@gubuntu:~/data/luisa$ wget http://dv-testfiles.s3.amazonaws.com/ENCFF528VXT.bam
--2018-03-07 16:20:42--  http://dv-testfiles.s3.amazonaws.com/ENCFF528VXT.bam
Resolving dv-testfiles.s3.amazonaws.com (dv-testfiles.s3.amazonaws.com)... 52.218.52.113
Connecting to dv-testfiles.s3.amazonaws.com (dv-testfiles.s3.amazonaws.com)|52.218.52.113|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 357342653 (341M) [binary/octet-stream]
Saving to: âENCFF528VXT.bamâ

ENCFF528VXT.bam                  100%[=========================================================>] 340.79M  1.26MB/s    in 5m 17s

2018-03-07 16:25:59 (1.08 MB/s) - âENCFF528VXT.bamâ saved [357342653/357342653]

paul@gubuntu:~/data/luisa$ samtools index ENCFF528VXT.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bgzf_read] Read block operation failed with error -1 after 143 of 246 bytes
samtools index: failed to create index for "ENCFF528VXT.bam"
paul@gubuntu:~/data/luisa$
paul@gubuntu:~/data/luisa$
paul@gubuntu:~/data/luisa$ cd ~/deepvariant/bazel-bin
paul@gubuntu:~/deepvariant/bazel-bin$ PYTHONPATH=. /usr/bin/python deepvariant/make_examples --mode calling --ref /home/paul/data/luisa/hg19.fa --reads /home/paul/data/luisa/ENCFF528VXT.bam --examples /home/paul/data/luisa/shardedExamples/examples.tfrecord@2.gz --regions chr20:10,000,000-10,010,000 --task 0
WARNING: Logging before flag parsing goes to stderr.
I0307 16:27:52.052795 140569100494592 client.py:1004] Timeout attempting to reach GCE metadata service.
W0307 16:27:52.112967 140569100494592 htslib_gcp_oauth.py:88] GCP credentials not found; only local files and public gs:// URIs will be accessible from htslib
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
Traceback (most recent call last):
  File "/home/paul/.cache/bazel/_bazel_paul/26d0829f7bba5a6d91f862666f0d8ee5/execroot/genomics/bazel-out/k8-opt/bin/deepvariant/make_examples.runfiles/genomics/deepvariant/make_examples.py", line 1105, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/paul/.cache/bazel/_bazel_paul/26d0829f7bba5a6d91f862666f0d8ee5/execroot/genomics/bazel-out/k8-opt/bin/deepvariant/make_examples.runfiles/genomics/deepvariant/make_examples.py", line 1056, in main
    options = default_options(add_flags=True, flags_obj=FLAGS)
  File "/home/paul/.cache/bazel/_bazel_paul/26d0829f7bba5a6d91f862666f0d8ee5/execroot/genomics/bazel-out/k8-opt/bin/deepvariant/make_examples.runfiles/genomics/deepvariant/make_examples.py", line 225, in default_options
    with genomics_io.make_sam_reader(flags_obj.reads) as sam_reader:
  File "/home/paul/.cache/bazel/_bazel_paul/26d0829f7bba5a6d91f862666f0d8ee5/execroot/genomics/bazel-out/k8-opt/bin/deepvariant/make_examples.runfiles/genomics/deepvariant/core/genomics_io.py", line 143, in make_sam_reader
    random_seed=random_seed))
ValueError: Not found: No index found for /home/paul/data/luisa/ENCFF528VXT.bam
paul@gubuntu:~/deepvariant/bazel-bin$
```

**Comment by luisas** [comment] 2018-03-07 22:20
Indeed the file was truncated, sorry about that. I am still testing locally
with other even smaller files ( like : wget
http://dv-testfiles.s3.amazonaws.com/wgEncodeUwRepliSeqGm12878G1bAlnRep1.bam
which is public and smaller and not truncated ) and I get the same exact
error again.

2018-03-07 22:36 GMT+01:00 Paul Grosu <notifications@github.com>:

**Comment by pprieto** [comment] 2018-03-07 22:46
Believe the issue was coming from limiting the previous step to certain regions. When running it now on full genome without restriction with 0.5.1 and the latest models it works for me

Thanks!

**Closed** 2018-03-20 17:26 UTC
