### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by jellycatfish195** [google/deepvariant#879] opened 2024-09-06 02:56 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:

**Describe the issue:**
I tried to test run deepvariant following the quick-start guide at https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-quick-start.md and I got `Fatal Python error: Segmentation fault`.

**Setup**
  - Operating system: Ubuntu 20.04.6 LTS
  - DeepVariant version: r1.6.1
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: exact same data in the quick start guide

**Steps to reproduce:**
  - Command:
```  
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  deepvbuild:latest \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=1
```
  - Error trace:
```
I0906 02:45:46.585311 275767425675280 run_deepvariant.py:519] Re-using the directory for intermediate results in /output/intermediate_results_dir

***** Intermediate results will be written to /output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" --channels "insert_size" --gvcf "/output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

I0906 02:45:51.909050 257960059396112 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0906 02:45:51.913105 257960059396112 make_examples_core.py:301] Preparing inputs
I0906 02:45:51.913431 257960059396112 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0906 02:45:51.913708 257960059396112 make_examples_core.py:301] Common contigs are ['chr20']
I0906 02:45:51.914803 257960059396112 make_examples_core.py:301] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
I0906 02:45:51.916343 257960059396112 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0906 02:45:51.961755 257960059396112 genomics_reader.py:222] Reading /input/NA12878_S1.chr20.10_10p1mb.bam with NativeSamReader
I0906 02:45:51.961891 257960059396112 make_examples_core.py:301] Writing gvcf records to /output/intermediate_results_dir/gvcf.tfrecord-00000-of-00001.gz
I0906 02:45:51.962091 257960059396112 make_examples_core.py:301] Writing examples to /output/intermediate_results_dir/make_examples.tfrecord-00000-of-00001.gz
I0906 02:45:51.962123 257960059396112 make_examples_core.py:301] Overhead for preparing inputs: 0 seconds
Fatal Python error: Segmentation fault

Current thread 0x0000ea9d01b4e010 (most recent call first):
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/realigner/window_selector.py", line 116 in _variant_reads_threshold_selector
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/realigner/window_selector.py", line 76 in _candidates_from_reads
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/realigner/window_selector.py", line 233 in select_windows
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/realigner/realigner.py", line 806 in realign_reads
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples_core.py", line 1881 in realign_reads
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples_core.py", line 1908 in <listcomp>
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples_core.py", line 1907 in realign_reads_per_sample_multisample
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples_core.py", line 1709 in process
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples_core.py", line 2838 in make_examples_runner
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples.py", line 224 in main
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/absl_py/absl/app.py", line 258 in _run_main
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/absl_py/absl/app.py", line 312 in run
  File "/tmp/Bazel.runfiles_v_91gifn/runfiles/_main/deepvariant/make_examples.py", line 234 in <module>
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/ucsc.hg19.chr20.unittest.fasta --reads /input/NA12878_S1.chr20.10_10p1mb.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --channels insert_size --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real    0m5.584s
user    0m13.426s
sys     0m0.563s
```
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
I am running this on an AWS graviton4 machine (aarch64 architecture). The Dockerfile does not work for me directly. I had to run `build-prereq.sh` and resolve all the errors manually within a docker container. But I did run build_and_test.sh to make sure all tests passed and the binaries were also built successfully.

**Comment by lucasbrambrink** [comment] 2024-09-06 18:57
Hi @jellycatfish195 

This is interesting. You mention that Dockerfile did not work for directly, do you have more information on that? I notice you run `deepvbuild:latest` as opposed to `google/deepvariant:"${BIN_VERSION}"`, what prompted that decision?

You also mention that you ran `build-prereq.sh` and encountered some errors. Do you have a log file of those errors?

Thanks!

**Comment by SiyingFeng1995** [comment] 2024-09-06 20:07
Hi @lucasbrambrink ,

Thanks for your prompt response.

I started with an empty docker container and ran each script manually. And after I built, I committed the container to create a new image: deepvbuild:latest. Because I made quite a few changes, I have lost track of all the changes I have made. 

For example, I made quite some changes to the version numbers because pip has version conflicts. The main ones are that I had to use python3.9 and pandas 1.4.4. Also, I kind of have to switch between numpy 2.0.2 (to build) and 1.24.1 (to run). I also had to install tensorflow-addons from git repo because pip does not have that.

In build-prereq.sh, I downloaded bazel 7.3.1 linux arm64 binary. The main difficulty lies in building pyclif. There were a lot of errors related to protobuf cmake modules or linking abseil but it worked in the end. I don't think they should cause problems if they build successfully.

For `build_release_binaries.sh`, I had to change the folder name from `k8-opt` to `aarch64-opt`. I am not sure whether this would cause problems but I also commented out line 59: `find "runfiles/com_google_deepvariant" -name '*.so' -exec ln --force -s --relative "runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so" {} \;` because there were no such folders or .so files.

Because all bazel tests are passed and the binaries are successfully built, I would think it is not an error related to the dependencies. I am not sure how to get more information on what may go wrong from the error trace. Please feel free to let me know if there is anything else I can run to generate more useful information.

Thanks!

**Comment by SiyingFeng1995** [comment] 2024-09-06 20:59
Hi @lucasbrambrink ,

I tried to recreate the building process, so here are some changes I made to the scripts:
```
diff --git a/settings.sh b/settings.sh
index 9d5f58c0..649b1bb8 100755
--- a/settings.sh
+++ b/settings.sh
@@ -89,18 +89,18 @@ export DV_GPU_BUILD="${DV_GPU_BUILD:-0}"
 # DeepVariant's call_variants step by >3x. This is called the GCP (Google Cloud
 # Platform) optimized wheel because all GCP instances have at least Sandy Bridge
 # or better chipsets, so this wheel should run anywhere on GCP.
-export DV_USE_GCP_OPTIMIZED_TF_WHL="${DV_USE_GCP_OPTIMIZED_TF_WHL:-1}"
+export DV_USE_GCP_OPTIMIZED_TF_WHL="${DV_USE_GCP_OPTIMIZED_TF_WHL:-0}"
 export GCP_OPTIMIZED_TF_WHL_FILENAME="tensorflow-${DV_GCP_OPTIMIZED_TF_WHL_VERSION}.deepvariant_gcp-cp27-none-linux_x86_64.whl"
 export GCP_OPTIMIZED_TF_WHL_PATH="${DV_PACKAGE_BUCKET_PATH}/tensorflow"
 export GCP_OPTIMIZED_TF_WHL_CURL_PATH="${DV_PACKAGE_CURL_PATH}/tensorflow"
-export DV_TF_NUMPY_VERSION="1.19.2"  # To match GCP_OPTIMIZED_TF_WHL_FILENAME
+export DV_TF_NUMPY_VERSION="1.24.1"  # To match GCP_OPTIMIZED_TF_WHL_FILENAME
 
 # Set this to 1 to make our prereq scripts install the CUDA libraries.
 # If you already have CUDA installed, such as on a properly provisioned
 # Docker image, it shouldn't be necessary.
 export DV_INSTALL_GPU_DRIVERS="${DV_INSTALL_GPU_DRIVERS:-0}"
 
-export PYTHON_VERSION=3.8
+export PYTHON_VERSION=3.9
 # shellcheck disable=SC2155
 export PYTHON_BIN_PATH="$(which python${PYTHON_VERSION})"
 export PYTHON_LIB_PATH="/usr/local/lib/python${PYTHON_VERSION}/dist-packages"
@@ -112,7 +112,7 @@ export USE_DEFAULT_PYTHON_LIB_PATH=1
 #    --experimental_build_setting_api"
 # Presumably it won't be needed at some later point when bazel_skylib is
 # upgraded again.
-export DV_COPT_FLAGS="--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11"
+# export DV_COPT_FLAGS="--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11"
 
 function note_build_stage {
   echo "========== [$(date)] Stage '${1}' starting"
```
```
diff --git a/build-prereq.sh b/build-prereq.sh
index ad34e285..1fc2d203 100755
--- a/build-prereq.sh
+++ b/build-prereq.sh
@@ -41,7 +41,7 @@ source settings.sh
 
 note_build_stage "Install the runtime packages"
 
-./run-prereq.sh
+#./run-prereq.sh
 
 note_build_stage "Update package list"
 
@@ -71,12 +71,17 @@ function ensure_wanted_bazel_version {
   then
     echo "Bazel ${wanted_bazel_version} already installed on the machine, not reinstalling"
   else
-    pushd ~/bazel
-    curl -L -O https://github.com/bazelbuild/bazel/releases/download/"${wanted_bazel_version}"/bazel-"${wanted_bazel_version}"-installer-linux-x86_64.sh
-    chmod +x bazel-*.sh
-    ./bazel-"${wanted_bazel_version}"-installer-linux-x86_64.sh --user > /dev/null
-    rm bazel-"${wanted_bazel_version}"-installer-linux-x86_64.sh
-    popd
+    wget https://github.com/bazelbuild/bazel/releases/download/7.3.1/bazel-7.3.1-linux-arm64
+    cp bazel-7.3.1-linux-arm64 /usr/local/bin/bazel
+    cp bazel-7.3.1-linux-arm64 /usr/local/bin/bazelisk
+    chmod +x /usr/local/bin/bazel
+    chmod +x /usr/local/bin/bazelisk
   fi
 }
```
```
diff --git a/tools/build_clif.sh b/tools/build_clif.sh
index c7c3378b..a08ab475 100755
--- a/tools/build_clif.sh
+++ b/tools/build_clif.sh
@@ -39,7 +39,7 @@ echo ========== Run this script in root mode.
 CLIF_UBUNTU_VERSION="${CLIF_UBUNTU_VERSION-20.04}"
 ABSL_PIN="${ABSL_PIN-29bf8085f3bf17b84d30e34b3d7ff8248fda404e}"
 PROTOBUF_VERSION=3.13.0
-CLIF_PYTHON_VERSION="${CLIF_PYTHON_VERSION-3.8}"
+CLIF_PYTHON_VERSION="${CLIF_PYTHON_VERSION-3.9}"
 # CLIF_PIN can be set to a specific commit hash on
 # https://github.com/google/clif/commits/main.
 # If not set, the default is to checkout the latest commit.
@@ -65,6 +65,21 @@ apt-get install "${APT_ARGS[@]}" --no-install-recommends \
     wget \
     unzip
 
+apt-get install "${APT_ARGS[@]}" python3-apt
+cd /usr/lib/python3/dist-packages
+if [ -e apt_pkg.so ]; then
+    rm apt_pkg.so
+fi
+ln -s apt_pkg.cpython-38-aarch64-linux-gnu.so apt_pkg.so
+cd -
+
+export PATH=/root/.local/bin/:$PATH
+apt-get install "${APT_ARGS[@]}" libcairo2-dev
+pip install pygobject
+apt-get install "${APT_ARGS[@]}" libgirepository1.0-dev
+pip install --upgrade pygobject
+sed -i 's/isAlive/is_alive/g' /usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py 
+
 # Configure LLVM 11 apt repository
 wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key |  apt-key add - && \
   add-apt-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-11 main"
@@ -79,7 +94,6 @@ apt-get install  "${APT_ARGS[@]}" \
     libllvm11 \
     llvm-11 \
     llvm-11-dev \
-    llvm-11-linker-tools \
     python3-dev \
     zlib1g-dev
 
@@ -147,4 +161,5 @@ if [[ ! -z ${CLIF_PIN} ]]; then
   git checkout "${CLIF_PIN}"
 fi
 
+sed -i 's/11.1.0/11.0.0/g' clif/cmake/modules/CLIFUtils.cmake 
 ./INSTALL.sh
```
After these changes, I am stuck again at building clif because of the following error:
```
[100%] Linking CXX executable clif-matcher
/usr/bin/ld: libclifMatcher.a(matcher.cc.o): in function `absl::lts_20230802::log_internal::LogMessage& absl::lts_20230802::log_internal::LogMessage::operator<< <27>(char const (&) [27])':
matcher.cc:(.text._ZN4absl12lts_2023080212log_internal10LogMessagelsILi27EEERS2_RAT__Kc[_ZN4absl12lts_2023080212log_internal10LogMessagelsILi27EEERS2_RAT__Kc]+0x38): undefined reference to `void absl::lts_20230802::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20230802::log_internal::LogMessage::StringType)0>(std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: libclifMatcher.a(matcher.cc.o): in function `absl::lts_20230802::log_internal::LogMessage& absl::lts_20230802::log_internal::LogMessage::operator<< <24>(char const (&) [24])':
matcher.cc:(.text._ZN4absl12lts_2023080212log_internal10LogMessagelsILi24EEERS2_RAT__Kc[_ZN4absl12lts_2023080212log_internal10LogMessagelsILi24EEERS2_RAT__Kc]+0x38): undefined reference to `void absl::lts_20230802::log_internal::LogMessage::CopyToEncodedBuffer<(absl::lts_20230802::log_internal::LogMessage::StringType)0>(std::basic_string_view<char, std::char_traits<char> >)'
collect2: error: ld returned 1 exit status
make[3]: *** [clif/backend/CMakeFiles/clif-matcher.dir/build.make:147: clif/backend/clif-matcher] Error 1
make[2]: *** [CMakeFiles/Makefile2:1342: clif/backend/CMakeFiles/clif-matcher.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1349: clif/backend/CMakeFiles/clif-matcher.dir/rule] Error 2
make: *** [Makefile:617: clif-matcher] Error 2
```
I had the same error last time but it somehow worked magically when I removed `build/` folder after a while.

I think these are the major changes I have made apart from the changes to the `build_release_binaries.sh`. Please feel free to let me know if anything looks weird to you.

**Comment by lucasbrambrink** [comment] 2024-09-06 22:10
Hi,

Thanks for providing all of that information, it is very helpful. The issue does actually lie in pyclif and protobuf. We use an older version of protobuf that is stable with pyclif; updating it will break the interoperability between C++ and Python (the source of that seg fault). Our tests in `build_and_test.sh` do not appear to catch this, of which I have made a note to update in the future. 

Is there a reason you cannot use our Docker builds from `1.6.1`? Also, if docker does not work for you, are you able to use singularity? I am unsure that brute forcing a docker build will lead to a container that runs everything as intended.

**Comment by SiyingFeng1995** [comment] 2024-09-07 03:47
Hi,

Thanks for your answer. It is good to know that pyclif and protobuf is the problem. I think I did not change the version of protobuf and pyclif because I did not change the commit numbers of the repositories, i.e. `ABSL_PIN`, `PROTOBUF_VERSION` or `CLIF_PYTHON_VERSION` in `tools/build_clif.sh`. I did change the python version number though because otherwise some packages are not installable through pip, e.g. jaxlib from clu requires python >= 3.9. I am not sure whether this is normal or it is the root cause of the problem.

I did pull the Docker builds before I tried to build my own image but it seems it is built only for amd64 platform. The machine I use is in arm architecture, i.e. aarch64, so the docker build did not work for me. I don't think singularity would solve this problem because it still needs the docker to be built for the target architecture or using multi-platform builds. Do you think it is feasible to have such a build in the future?

P.S. I solved the linking error for clif by building abseil-cpp again right before building clif. I am not sure whether it is because something in between overwrites the path.

**Comment by SiyingFeng1995** [comment] 2024-09-07 05:10
Hi,

Thanks for your answer. It is good to know that pyclif and protobuf is the problem. I think I did not change the version of protobuf and pyclif because I did not change the commit numbers of the repositories, i.e. ABSL_PIN, PROTOBUF_VERSION or CLIF_PYTHON_VERSION in tools/build_clif.sh. I did change the python version number though because otherwise some packages are not installable through pip, e.g. jaxlib from clu requires python >= 3.9. I am not sure whether this is normal or it is the root cause of the problem.

I did pull the Docker builds before I tried to build my own image but it seems it is built only for amd64 platform. The machine I use is in arm architecture, i.e. aarch64, so the docker build did not work for me. I don't think singularity would solve this problem because it still needs the docker to be built for the target architecture or using multi-platform builds. Please feel free to let me know if I am wrong. However, do you think it is feasible to have such a build in the future?

P.S. I solved the linking error for clif by building abseil-cpp again right before building clif. I am not sure whether it is because something in between overwrites the path.

**Comment by jellycatfish195** [comment] 2024-09-07 12:17
Hi,

Thanks for your answer. It is good to know that pyclif and protobuf is the problem. I think I did not change the version of protobuf and pyclif because I did not change the commit numbers of the repositories, i.e. `ABSL_PIN`, `PROTOBUF_VERSION` or `CLIF_PYTHON_VERSION` in `tools/build_clif.sh`. I did change the python version number though because otherwise some packages are not installable through pip, e.g. jaxlib from clu requires python >= 3.9. I am not sure whether this is normal or it is the root cause of the problem.

I did pull the Docker builds before I tried to build my own image but it seems it is built only for amd64 platform. The machine I use is in arm architecture, i.e. aarch64, so the docker build did not work for me. Please feel free to let me know if I am wrong. But I don't think singularity would solve this problem because it still needs the docker to be built for the target architecture or using multi-platform builds. Do you think it is feasible to have such a build in the future?

P.S. I solved the linking error for clif by building abseil-cpp again right before building clif. I am not sure whether it is because something in between overwrites the path.

**Comment by kishwarshafin** [comment] 2024-09-09 16:11
@jellycatfish195 ,

Unfortunately aarch64 is not currently supported by DeepVariant build and it seems like you have to modify the build a lot and ultimately it breaks the build. Given the issue of supporting aarch64 has not been requested many times so we haven't looked into it. Is to possible for you to get a machine with x64 and use DeepVariant via that?

**Comment by jellycatfish195** [comment] 2024-09-10 01:02
Hi @kishwarshafin ,

I am doing profiling on my machine so I guess switching to an x64 machine is not an option for me. 

It would be great to have a stable build for aarch64 in the future though if it is not too much trouble.

**Comment by kishwarshafin** [comment] 2024-09-10 01:12
In your first comment you said: "I am running this on an AWS graviton4 machine (aarch64 architecture)." so I thought switching instance type was an option for you. I am sorry for your trouble.

We can give it a shot but the next release is pretty close and we may not have enough bandwidth to support aarch64. However, I will file a bug internally and see if we can support aarch64 in the future.

**Closed** 2024-09-10 16:11 UTC
