### ISSUE TITLE
Using openvino needs to write, causes issues with read-only container

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#404] opened 2021-01-15 11:56 UTC
Hi,
I've been encountering an issue when using the `openvino` extra arg for calling variants. When I do not use this flag, things progress as expected. When using the extra flag, both via `--call_variants_extra_args "use_openvino=true"` to *run_deepvariant* as well as the `--use_openvino` to *call_variants*, there is the following error about being unable to save the new model due to read-only system.

This is running V1.1.0 via singularity on a linux system, using the pacbio hifi model. 

```
Instructions for updating:
Use `tf.compat.v1.graph_util.remove_training_nodes`
Traceback (most recent call last):
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
    use_tpu=FLAGS.use_tpu,
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 409, in call_variants
    checkpoint_path, input_fn=tf_dataset, model=model)
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 89, in __init__
    freeze_graph(model, checkpoint_path, tensor_shape)
  File "/scratch/13530063.tmpdir/Bazel.runfiles_69_p3nci/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 81, in freeze_graph
    f.write(graph_def.SerializeToString())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 101, in write
    self._prewrite_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 87, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.PermissionDeniedError: model.pb; Read-only file system
```

I guess since the model resides in the container, it can't be updated as singularity is read-only without sudo. Would there be some way of passing the `--checkpoint "/opt/models/pacbio/model.ckpt"` parameter, but allowing it to be saved elsewhere?

Thanks,
Alex

**Comment by pichuan** [comment] 2021-01-16 01:32
Hi @ASLeonard , thanks for the report.
Now I think about it, I might not have tested the combination of Singularity and our use of OpenVINO together.
I'll run this through the [PacBio example](https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md) and confirm that I can reproduce this issue.

There are a few fixes I can think of, which you also suggested:
1. We can provide a flag that allows users to provide a pointer to the OpenVINO model file. This will require the user to run the freeze_graph code to convert the model themselves.
2. At this line:
https://github.com/google/deepvariant/blob/2dbebb4d97e15d0d5fcf303a4466314b1f313208/deepvariant/openvino_estimator.py#L80
We can provide the intermediate directory to write the model.pb file in. And users can specify a directory that Singularity won't be unhappy with.

I'll first try to reproduce the issue, and then I'll likely try with option 2 above. 
Thanks for reporting this issue. I'll update again when I look into it more.

Also tagging @dkurt here as an FYI.

**Comment by pichuan** [comment] 2021-01-16 03:30
Follow up: I looked my older work log -- I actually did test the Singularity+OpenVINO combination. I didn't see any issues at the time.

I repeated my steps, and still found that **I wasn't able to reproduce your issue, if I'm running in a directory where I have write access.** But, I'm able to see the same issue, if I start my command in a directory where I can't write to.

I have two questions for you:
(1) When you run the command, do you have write permission to the directory you're in? (Based on the current code, that's where the converted model files are written to.)
(2) What is your Singularity version?

I listed all my steps below in case it's useful.

---

# Worklog

## Get a Ubuntu16.04 machine
I used the [command here](https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md) to get a Ubuntu16.04 machine.

## Set up on the machine
After ssh into the machine, before start running the [PacBio tutorial](https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md), I'll install things first:

```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```
After installing conda, I logged out and re-logged in.

I install Singularity:
```
curl -O https://raw.githubusercontent.com/google/deepvariant/r1.1/scripts/install_singularity.sh
bash install_singularity.sh
```

Here is my Singularity version:
```
(base) pichuan@pichuan-cpu:~$ singularity --version
singularity version 3.3.0-1
```

## Run through PacBio tutorial
I follow the steps here:
https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md
and ran through all commands set up conda, and download all files.

When I get to this step:
https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-pacbio-model-case-study.md#run-deepvariant-on-chromosome-20-alignments

I added `--call_variants_extra_args "use_openvino=true"`. So my command is:
```
ulimit -u 10000 # https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable/54746150#54746150
BIN_VERSION="1.1.0"
mkdir -p deepvariant1

singularity exec --bind /usr/lib/locale/ \
  docker://google/deepvariant:${BIN_VERSION} \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref reference/GRCh38_no_alt_analysis_set.fasta \
    --reads input/HG003.GRCh38.chr20.pFDA_truthv2.bam \
    --output_vcf deepvariant1/output.vcf.gz \
    --num_shards $(nproc) \
    --regions chr20 \
    --call_variants_extra_args "use_openvino=true"
```

This actually worked for me. I'll paste some logs around the model conversion:
```
Instructions for updating:
Use `tf.compat.v1.graph_util.remove_training_nodes`
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /home/pichuan/model.pb
        - Path for generated IR:        /home/pichuan/.
        - IR output name:       model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  [128,128,128,128,128,128,128,128,128]
        - Scale values:         Not specified
        - Scale factor:         128.0
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
Model Optimizer version:

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /home/pichuan/./model.xml
[ SUCCESS ] BIN file: /home/pichuan/./model.bin
[ SUCCESS ] Total execution time: 24.29 seconds.
[ SUCCESS ] Memory consumed: 761 MB.
It's been a while, check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/en-us/openvino-toolkit/choose-download?cid=&source=upgrade&content=2020_3_LTS or on the GitHub*
WARNING:tensorflow:From /tmp/Bazel.runfiles_wz_ompqi/runfiles/com_google_deepvariant/deepvariant/data_providers.py:375: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
...
```
After this, the call_variants steps started running with no issues:
```
...
I0116 03:14:04.107081 140161826506496 openvino_estimator.py:118] Using OpenVINO in call_variants.
I0116 03:14:04.367440 140161826506496 openvino_estimator.py:155] Processed 1 examples in call_variants (using OpenVINO)
I0116 03:14:23.278933 140161826506496 openvino_estimator.py:155] Processed 15001 examples in call_variants (using OpenVINO)
I0116 03:14:42.118756 140161826506496 openvino_estimator.py:155] Processed 30001 examples in call_variants (using OpenVINO)
I0116 03:15:00.622359 140161826506496 openvino_estimator.py:155] Processed 45001 examples in call_variants (using OpenVINO)
...
```
My run completes with no issue. (postprocess_variants finished running as well).

## What if I run this from a directory that I don't have write-permission?
My previous run was done in a working directory that I can write to:
```
(base) pichuan@pichuan-cpu:~$ pwd
/home/pichuan
```

And in fact, after my run, I can still see some of the `model.*` files
```
(base) pichuan@pichuan-cpu:~$ ls model.*
model.bin  model.mapping  model.xml
```
I think model.pb got deleted programmatically.

What if I repeat the run in a directory that I can't write to?

```
(base) pichuan@pichuan-cpu:~$ cd /
```
And repeat the same run:
```
singularity exec --bind /usr/lib/locale/ \
  docker://google/deepvariant:${BIN_VERSION} \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref $HOME/reference/GRCh38_no_alt_analysis_set.fasta \
    --reads $HOME/input/HG003.GRCh38.chr20.pFDA_truthv2.bam \
    --output_vcf $HOME/deepvariant1/output.vcf.gz \
    --num_shards $(nproc) \
    --regions chr20 \
    --call_variants_extra_args "use_openvino=true"
```
With this, I'm now seeing the same issue:
```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 409, in call_variants
    checkpoint_path, input_fn=tf_dataset, model=model)
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 89, in __init__
    freeze_graph(model, checkpoint_path, tensor_shape)
  File "/tmp/Bazel.runfiles_m__akao7/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 81, in freeze_graph
    f.write(graph_def.SerializeToString())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 101, in write
    self._prewrite_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 87, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.PermissionDeniedError: model.pb; Read-only file system
```

**Comment by dkurt** [comment] 2021-01-16 13:01
@pichuan, Thanks for investigation! Sorry, I just not familiar with Singularity, but am I right that it writes all the files directly to host filesystem?

Maybe, as you mentioned, it make sense to write intermediate .pb and .xml & .bin files to output directory? Basedir of output_vcf or output_gvcf.

**Comment by ASLeonard** [comment] 2021-01-16 18:07
I'll look into these options some more start of next week. My initial thought was the path to the model is inside the container (`/opt/models/pacbio/model.ckpt`), and I cannot write to a singularity container without sudo access. I'll try some different binds to see if I can get that to write to the current directory, as I definitely have write access there.

**Comment by pichuan** [comment] 2021-01-16 18:16
Thanks @ASLeonard . Can you tell me:
1. Which Singularity version do you have. (and OS version too)
2. What command did you run?

I'd still like to reproduce the issue if possible on my side. If I can get a setting as close as yours, I might be able to reproduce the issue.

And @dkurt thanks for taking a look.
I also think it'll be better to write to the intermediate output dir rather than the current working directory. I'll work on an internal fix. I'll update here when I get it to work.

**Comment by ASLeonard** [comment] 2021-01-18 11:16
Versions
- singularity version 3.6.4-1.el7
- CentOS Linux release 7.9.2009
- Kernel: Linux 3.10.0-1160.6.1.el7.x86_64

The command I was running has some differences in the singularity setup, as I had to explicitly bind the scratch directory etc on the compute nodes. When running the command that **did** work for you, I get the following error immediately `OSError: [Errno 30] Read-only file system: '/output'`, due to the binding issue.
 
```
singularity run -B ${INPUT}:/input,${OUTPUT}:/output,${OUTPUT}/intermediate_results_dir:/output/intermediate_results_dir,$TMPDIR:$TMPDIR \
  deepvariant_1.1.0.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type "PACBIO" \
  --ref /input/asm.fasta \
  --reads /input/hifi.bam \
  --output_vcf /output/asm.output.vcf.gz \
  --output_gvcf /output/asm.output.g.vcf.gz \
  --num_shards "${THREADS}" \
  --call_variants_extra_args "use_openvino=true" \
  --intermediate_results_dir /output/intermediate_results_dir
```

This correctly makes the examples and saves the results to the *intermediate_results_dir*, the error happens at the start of call_variants, when the openvino model wants to write to the read-only container.

I tried making a `models/pacbio` file and dowloaded the ckpt files, and then made a bind to `opt/models/pacbio/`, but also same error on the read only system.

I've also tried running the `bin/call_variants` command from the login nodes and ran into the same error, which was surprising as I have write permissions to more locations on those nodes.

**Comment by pichuan** [comment] 2021-01-20 00:27
Thanks @ASLeonard . I tried one more with (still with my own versions this time) and added the `-B`:

```
singularity build deepvariant.sif docker://google/deepvariant:${BIN_VERSION}
mkdir -p intermediate_results_dir
```
```
singularity run \
 -B ${HOME}/input:/input,${HOME}/reference:/reference,${HOME}/deepvariant1:/deepvariant1,${HOME}/intermediate_results_dir:/intermediate_results_dir \
 deepvariant.sif \
 /opt/deepvariant/bin/run_deepvariant \
 --model_type "PACBIO" \
 --ref /reference/GRCh38_no_alt_analysis_set.fasta \
 --reads /input/HG003.GRCh38.chr20.pFDA_truthv2.bam \
 --output_vcf /deepvariant1/output.vcf.gz \
 --output_gvcf /deepvariant1/output.g.vcf.gz \
 --num_shards $(nproc) \
 --regions "chr20:10,000,000-10,010,000" \
 --call_variants_extra_args "use_openvino=true" \
 --intermediate_results_dir /intermediate_results_dir
```

I tried this with a newer Singularity version, and still can't reproduce your error yet.

Here's the machine I'm on:
```
(deepvariant_whatshap) pichuan@pichuan-cpu:~$ singularity --version
singularity version 3.6.4
(deepvariant_whatshap) pichuan@pichuan-cpu:~$ uname -a
Linux pichuan-cpu 4.15.0-1091-gcp #104~16.04.1-Ubuntu SMP Tue Dec 15 19:05:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I'll try again later with CentOS as well to see if I can reproduce your issue. If you find out anything else, please let me know.

**Comment by ASLeonard** [comment] 2021-01-20 10:05
I got the following to work (I haven't tested to the end, but successfully reached calling variants). I'm going to keep iterating and seeing how much of these commands I can remove.

Opening singularity through a shell
`singularity shell --no-home --cleanenv --containall -B tmp:/tmp,input:/input,output:/output deepvariant_1.1.0.sif`

Changing directory to something I've bound (e.g. ouptut), and then running call_variants
```
cd ouput
../opt/deepvariant/bin/call_variants \
--examples "/output/intermediate_results_dir/make_examples.tfrecord@24.gz" \
--outfile "/output/intermediate_results_dir/call_variants_out.tfrecord.gz" \
--checkpoint "/opt/models/pacbio/model.ckpt" \
--use_openvino
```
At this point, we made progress with the following
```
Model Optimizer version: 	

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /output/./model.xml
[ SUCCESS ] BIN file: /output/./model.bin
[ SUCCESS ] Total execution time: 30.04 seconds. 
[ SUCCESS ] Memory consumed: 699 MB
```
With persistent model.bin/mapping/xml files in my output folder.

I tried unsuccessfully with different binds to be able to write files to the `/` directory in the container, which is where the openvino graph is being written. It may be related to the directory structure on our cluster not meshing well with the container.

**Comment by ASLeonard** [comment] 2021-01-20 12:28
I found an ungainly solution so I can still batch submit jobs. Using `/bin/bash -c "<stuff>"`, I can pass two commands to singularity exec. So I can do changing directory and running deepvariant in "one" command.

The full command that worked was
```
singularity exec -no-home --cleanenv --containall -B tmp:/tmp,input:/input,output:/output deepvariant_1.1.0.sif \
  /bin/bash -c "cd output; ../opt/deepvariant/bin/call_variants \
  --outfile /output/intermediate_results_dir/call_variants_output.tfrecord.gz \
  --examples /output/intermediate_results_dir/make_examples.tfrecord@24.gz \
  --checkpoint /opt/models/pacbio/model.ckpt \
  --use_openvino"
```

**Comment by pichuan** [comment] 2021-01-20 17:48
Thank you @ASLeonard for sharing your current solution.

On my end I'll continue to try to reproduce the issue. If I'm unable to, I might need to ask you to help test out my updated code after I have it. I might reach out again later on this thread. For now, I'll close this issue. Please feel free to update with more information, or submit another issue if you have other questions.

**Closed by pichuan** 2021-01-20 17:48 UTC
