### ISSUE TITLE
getting error while running deepvariant: ERROR[12893] error waiting for container: unexpected EOF

### ISSUE THREAD

**Issue by kirti141** [google/deepvariant#482] opened 2021-09-07 08:42 UTC
Getting error while running deepvariant: ERROR[12893] error waiting for container: unexpected EOF

Command: 
docker run -v "/home/input":"/input" -v "/home/output/":"/output" gcr.io/deepvariant-docker/deepvariant:1.2.0 /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/hg19.fa --reads=/input/sorted_printReads_bwa.bam --output_vcf=/output/ERR194147_output.vcf.gz --num_shards=2 --intermediate_results_dir=/output/ --output_gvcf=/output/ERR194147_output.g.vcf.gz

**Comment by MariaNattestad** [comment] 2021-09-11 01:58
Can you share more of the stack trace?

**Comment by kirti141** [comment] 2021-09-20 08:27
![dv_error](https://user-images.githubusercontent.com/56719787/133974583-c77a3de2-6bb2-4b7f-b6dc-dbc1540c75bb.png)

**Comment by pichuan** [comment] 2021-09-22 15:38
@kirti141 from the log, I agree that it isn't quite clear. 
Can you tell us about your machine? How many CPU cores, RAM, what OS, etc.

**Comment by kirti141** [comment] 2021-09-22 22:39
Machine has 64 cores, 2TB RAM, Centos is OS.

Deep variant docker code works well when input bam file size is less than
20 Gb file size, but when I increase the file size / coverage, I get the
error.

**Comment by pichuan** [comment] 2021-09-22 22:49
Hmm, empirically we've been able to handle larger input BAM than 20GB with less RAM you had. 

Another known issue (which we will fix in the next release) is that if auxiliary fields are being read in, and if the BAM has many of them, it could unnecessarily increase the RAM usage. However, in this case given that you're using WGS model (which by default isn't parsing aux fields), that shouldn't be an issue...

@kirti141 Another question for you - is there a BAM file that you can make public (with no sensitive information, of course) that we can attempt to reproduce this issue? Thanks again for reporting this.

**Comment by MariaNattestad** [comment] 2021-09-22 22:53
One quick question: How much is your coverage?

**Comment by kirti141** [comment] 2021-09-22 22:56
I think RAM is not an issue, my machine has 2TB RAM.

Coverage is 46x

**Comment by kirti141** [comment] 2021-09-22 23:00
I have no problem in making my .bam file public, but please help me where
to drop / upload it, to make it public, so you can test it.

**Comment by pichuan** [comment] 2021-09-23 00:36
@kirti141 hm, this question (data sharing) turns out to be more complicated than I thought. I'll have to think about what's a best way for this.

For now, I can try to run DV 1.2 on this large BAM file:
```
$ gsutil ls -lh gs://deepvariant/case-study-testdata/HG002_NIST_150bp_50x.bam
 110.3 GiB  2019-02-26T18:04:41Z  gs://deepvariant/case-study-testdata/HG002_NIST_150bp_50x.bam
```
on a 64 cores CentOS machine, to see if I can reproduce the issue.

I'll report back after I have a chance to run it.

**Comment by kirti141** [comment] 2021-09-23 00:49
It might work on your test data, but not working on all my samples...I
tried on many samples.

Will think of any solution for sharing my .bam file.

**Comment by pichuan** [comment] 2022-01-06 06:14
Hi @kirti141 , if you have any follow ups on suggestions to reproduce this issue, please let us know. For now I'll close this issue.

**Closed** 2022-01-15 06:34 UTC
