### ISSUE TITLE
Failed to retrieve block: error reading file for gvcf postprocess variants for WGS

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#164] opened 2019-03-21 13:36 UTC
Hi, I'm getting the following error when trying to postprocess the gvcf (generation of the normal vcf works fine). Any ideas why this is happening? It's happening across several different samples, but always at the same site. Could it be something missing in the reference fasta file? If so is there a setting to have it fail less spectacularly and skip over variants it for some reason cannot find?

```

I0320 10:18:29.648770 140566999074560 postprocess_variants.py:593] Writing output to VCF file: UFC100105-Normal-SM-CUCI1.gvcf
I0320 10:18:29.649548 140566999074560 genomics_writer.py:118] Writing UFC100105-Normal-SM-CUCI1.gvcf with NativeVcfWriter
[E::fai_retrieve] Failed to retrieve block: error reading file
Traceback (most recent call last):
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 871, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 866, in main
    header=header)
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 596, in write_variants_to_vcf
    for variant in variant_generator:
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 798, in merge_variants_and_nonvariants
    nonvariant.end, fasta_reader)
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 712, in _create_record_from_template
    ranges.make_range(retval.reference_name, start, start + 1))
  File "/cromwell_root/tmp.1b831160/Bazel.runfiles_bAePPc/runfiles/com_google_deepvariant/third_party/nucleus/io/fasta.py", line 90, in query
    return self._reader.bases(region)
ValueError: Invalid argument: Couldn't fetch bases for reference_name: "1" start: 10147 end: 10148
+ echo 'grep -v -E '\''RefCall[[:space:]]'\'' '\''UFC100105-Normal-SM-CUCI1.vcf'\'' > '\''UFC100105-Normal-SM-CUCI1.filtered.vcf'\'''
+ grep -v -E 'RefCall[[:space:]]' UFC100105-Normal-SM-CUCI1.vcf
```

**Comment by ekofman** [comment] 2019-03-25 20:58
Hi @pichuan ! Any initial hunches by any chance? Appreciate the help

**Comment by pichuan** [comment] 2019-03-25 21:12
Hi @ekofman , sorry forgot to answer this one.
Looking at the error line:
```
[E::fai_retrieve] Failed to retrieve block: error reading file
```
It seems to me that it might be having some trouble reading from the reference FASTA file and its corresponding FAI file. Can you check with FASTA file (and corresponding FAI) file you're using?

**Comment by ekofman** [comment] 2019-03-25 21:21
Like it's potentially corrupted? I'll see if I can figure that out but I'm pretty sure the fasta and fai should be fine as we use them for many of our other applications.

**Comment by pichuan** [comment] 2019-03-25 21:44
Thanks. If any of these files are public, let me know and we can also take a look.
I'll also ask my teammates who have recently looked at the postprocess_variants code to see if they have other suggestions.

**Comment by ekofman** [comment] 2019-03-25 22:00
gs://fc-f36b3dc8-85f7-4d7f-bc99-a4610229d66a/broadinstitute/reference/hg19/fasta/Homo_sapiens_assembly19.fasta

and 

gs://fc-f36b3dc8-85f7-4d7f-bc99-a4610229d66a/broadinstitute/reference/hg19/fasta/Homo_sapiens_assembly19.fasta.fai

Thanks!

**Comment by pichuan** [comment] 2019-03-26 03:29
@ekofman One question for you -- did you get this error when you directly specifying gs:// in your command?
If so, can you try another run where you copy those files to your local machine first (and point to a local machine)? I know that we should (in theory) be able to read from GCS bucket because htslib should support it, but I have not done that much in the past, so I don't know how reliable it is.
Thank you!

**Comment by ekofman** [comment] 2019-03-26 12:24
They’re being copied to the local machine actually!

**Comment by cmclean** [comment] 2019-03-26 13:54
Hi @ekofman ,

I am unable to reproduce this FASTA querying error on my machine. Can you verify the md5sums of the files you have on your local machine? When I copy the above gs:// paths, I see

$ md5sum Homo_sapiens_assembly19.fasta*
886ba1559393f75872c1cf459eb57f2d  Homo_sapiens_assembly19.fasta
fdc0ab679f6461d78980de2a2e97e8f3  Homo_sapiens_assembly19.fasta.fai

and with those files can query the position 1:10147 successfully.

**Comment by ekofman** [comment] 2019-03-26 14:04
hmm yes seems okay...

886ba1559393f75872c1cf459eb57f2d  Homo_sapiens_assembly19.fasta
fdc0ab679f6461d78980de2a2e97e8f3  Homo_sapiens_assembly19.fasta.fai

**Comment by ekofman** [comment] 2019-03-26 14:08
The strange thing is that the vcf generated perfectly with no problems, whereas the gvcf had this issue and in my final output is only 5 KB in size

**Comment by pichuan** [comment] 2019-03-26 21:41
@ekofman In this case, it seems like the gVCF file generation might have had some issues.
Since that the gVCF generation requires output from make_examples stage, is it possible that the make_examples stage weren't completely correctly? Can you check the output size from there?

And, when running manually, a common failure mode is that sometimes people will start a run, and ctrl-c in the middle. But then, sometimes some of the Python processes won't be killed, resulting corrupted intermediate outputs.

If you think this might be the case, I'd recommend re-run. If you kill the process manually, make sure to kill all in the background.

If you don't think this is the case, we can discuss other possibilities to diagnose this together. (I don't supposed your BAM file is public?)

**Comment by cmclean** [comment] 2019-03-26 21:47
It makes sense that the VCF generated successfully. In the postprocess_variants program, first the VCF is created based solely upon the outputs from the call_variants program, which has knowledge of the reference and alternate bases for each candidate site (and thus does not need to interact with the FASTA at all). The gVCF is created afterwards but needs a FASTA for cases where variants "poke holes" in a gVCF record. For example, a single gVCF record spanning hg19.chr1:10140-10150 would be represented as

chr1    10140   .    A    <*>    ...    END=10150

but if the VCF identifies an AC->C deletion at chr1:10146, then the gVCF output will look like

chr1   10140   .   A     <*>    ...    END=10145
chr1   10146   .   AC    C      ...
chr1   10148   .   C     <*>    ...    END=10150

where we find out that the chr1:10148 position has C by querying the FASTA. So it looks like your gVCF creation is dying on the first gVCF record that requires reading from the FASTA, and this is why the gVCF is truncated to be so small.

It's still unclear to me why querying this FASTA has issues though.

**Comment by pichuan** [comment] 2019-04-12 04:20
Hi @ekofman , with this issue, I think we might have left at a place where there is still a mystery.

Now the v0.8.0 is out, do you mind trying this again and see if you're still seeing the same issue? Given that I didn't fully understand what the problem last time was, at least a sanity check on whether we're still seeing the same thing will be helpful. 

If I might be forgetting something that I could have followed up from last time, please also feel free to remind me. Thanks!

**Comment by ekofman** [comment] 2019-04-12 15:24
Thanks! I haven't tried running with gvcf since we messaged last, but yes I
never got it to work. We'll let you know if we get a chance to get it
working with the newest version.

**Comment by pichuan** [comment] 2019-04-12 16:17
Thank you. I'll close this issue for now. When you have a chance to try, if you're still seeing the same issue (or different issues), feel free to open another one, or re-open this one as you see fit.

**Closed by pichuan** 2019-04-12 16:17 UTC
