### ISSUE TITLE
Abnormal behavior of model_eval

### ISSUE THREAD

**Issue by melkerdawy** [google/deepvariant#203] opened 2019-08-01 00:55 UTC
We are trying to customize the WES model to call variants on RNA-Seq reads. 

Regardless of how low we set the learning rate or the batch size or saving the intervals, the value of either the values of (TNs/All) and (FNs/All) is set to 0. or the values of (TPs/All) and (FPs/All) is set to zero. 

I am not sure I clarified the case enough so here is a sample of the first case:
 {'loss': 1.9104841, 'global_step': 0, 'TNs/All': 0.0, 'FNs/All': 0.0, 'F1/Class2': 0.0, 'Recall/Class1': 1.0, 'Recall/All': 1.0, 'Precision/All': 0.49536133, 'Precision/Class2': 0.0, 'Precision/Class1': 0.18457031, 'Accuracy/All': 0.18457031, 'F1/All': 0.6625306, 'FPs/All': 2067.0, 'Recall/Class2': 0.0, 'TPs/All': 2029.0, 'F1/Class1': 0.31162408}

 Here is an example of the second case 
{'loss': 1.0544469, 'global_step': 3252, 'TNs/All': 2067.0, 'FNs/All': 2029.0, 'F1/Class2': 0.0, 'Recall/Class1': 0.0, 'Recall/All': 0.0, 'Precision/All': 0.0, 'Precision/Class2': 0.0, 'Precision/Class1': 0.0, 'Accuracy/All': 0.5046387, 'F1/All': 0.0, 'FPs/All': 0.0, 'Recall/Class2': 0.0, 'TPs/All': 0.0, 'F1/Class1': 0.0}

One experiment the first case was the case for all the model from checkpoint-0 until checkpoint-1779 then the second case suddenly appeared till the end of the evaluation

We run shorter experiments and as I mentioned before, no matter how we change the parameters for the learning rate, batch size, or saving the interval, one of the two cases appears since checkpoint-0

Can you guess any reason for such a behavior?

**Comment by sidharthgoel** [comment] 2019-08-01 17:45
I'm not sure I see how the learning rate or batch_size would affect those metrics -- could you provide more information on your setup? And the two cases you are seeing -- are those randomly occurring or have you pinpointed why it flips one way or the other?

**Comment by melkerdawy** [comment] 2019-08-03 19:55
My setup is HPC with CentOS 7. I am using a singularity image of deepvariant 0.8.0. I did not pinpoint why it flips one way or the other. I was hoping that you can give me some insight or a guess about why such output might occur.

**Comment by pichuan** [comment] 2019-08-06 01:41
Hi @melkerdawy , thanks for reporting this issue.
In general it is difficult for us (as the developers of DeepVariant) to give advice on the training behavior of other people's data.

I can, however, from a perspective of a fellow ML researcher, ask a few more questions here to see if we can help you make progress:

(1) You said "Regardless of how low we set the learning rate or the batch size or saving the intervals, the value of either the values of (TNs/All) and (FNs/All) is set to 0. or the values of (TPs/All) and (FPs/All) is set to zero." --> The wording you have is confusing. I believe what you see here means that the `model_eval` code takes the checkpoints generated by `model_train`, and evaluated on the tuning data you've generated. And, based on the labeled tuning data, if the model thinks there are either no TNs(True Negatives) or FNs (False Negatives) --> this seems to indicate that it's likely at this point, the model might just don't call any negatives at all. But it's just my guess based on what you observe.

(2) Before we even dig deeper into the training behavior, can you check this:
What is the distribution of your labeled data? For example, in the regular DeepVariant formulation, we have 3 classes, "0" -- HOM_REF, "1" -- HET, "2" --HOM_ALT. HET and HOM_ALT are the ones that are consider germline variants, while HOM_REF calls will result in `RefCall` in the final DeepVariant VCF files.
To give you an example, in our [0.8 release](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-details-training-data.md#deepvariant-training-data), our total number of examples for WGS was 346,505,686. And the distribution was:
```
class 0, count: 101,679,899
class 1, count: 145,911,730
class 2, count: 98,914,057
```
There is no fixed recommendation of what the ratio should be. It depends on a lot of factors such as what is your BAM file like, what is the threshold you're using in the first round of very sensitive caller (which picks the candidates that feed into the classifier), and many many other details that are specific to your data.

Which is why I said our team cannot help debug the details of your case. But hopefully by examining your own distribution, you can first see if the training (and tuning) data makes sense or not. If the data has very skewed distribution, there are also other techniques that the ML community uses to improve the accuracy. But I won't be able to get into that. It's also not what DeepVariant designed for.
DeepVariant is wrapped around TensorFlow, which is a much more general purpose ML tool. If there are functionalities that we don't provide, please also look into TensorFlow to see if they have something useful for you.

I'm closing this issue now because this is not really a DeepVariant issue. But if you believe this actually reveals some bugs in our codebase, I'm happy to discuss further if you can show a reproducible example that demonstrate the error.
Closing this issue now. But happy to follow up on this issue if you have more thoughts/questions.

**Closed by pichuan** 2019-08-06 01:41 UTC
