### ISSUE TITLE
Unsupported allele call. 

### ISSUE THREAD

**Issue by marchoeppner** [google/deepvariant#470] opened 2021-07-08 10:42 UTC
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.1/docs/FAQ.md**:

**Describe the issue:**
I am debugging a set of false negative calls in a benchmarking set (NA12878, Agilent exome provided by a collaborator). 

In the process, I came across a call that makes no sense to me and was wondering what a plausible explanation might be:

Final VCF:
`chr1    109161996       rs678238        A       G       39      .       AC=1;AF=0.5;AN=2;AQ=39;DP=218   GT:AD:DP:GQ:PL:RNC      0/1:0,218:218:15:39,0,14:.
`

And the gVCF:
`chr1    109161996       .       A       G,<*>   39.6    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:15:218:0,218,0:1,0:39,0,14,990,990,990
`

The true gtenotype at this position should be G|G. 

However, note that the genotype is shown as 0|1  - even tho the ref allele as a depth of 0. This is supported by a manual inspection of the alignment. There really isn't an A there and it does not seem to be a "problematic" locus with long runs of A or G. The reads align perfectly without any gaps. 

Screenshot: https://www.dropbox.com/s/sp2n2gfy3li2rjl/dv_locus_error.JPG?dl=0  , Allele frequency as per alignment: G: 100%. 

So how come Deepvariant calls it like that? It really makes no sense to me :(

**Setup**
  - Operating system: Centos 7, Docker container
  - DeepVariant version: 1.1.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) Exome (Agilent V7, genome-in-a-bott reference)

**Steps to reproduce:**
  - Command: Not possible without the raw data...available upong request. 
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start? 

No. 

**Any additional context:**

**Comment by marchoeppner** [comment] 2021-07-08 10:46
BAM alignment at that locus: https://www.dropbox.com/s/qq5t53snaowiho0/debug.bam?dl=0
BAI: https://www.dropbox.com/s/e9aozinc0s6m0fw/debug.bam.bai?dl=0

**Comment by marchoeppner** [comment] 2021-07-12 12:03
Some information on the tool chain:
- Platform: NovaSeq 6000
- Trimming: fastP (auto-mode)
- Alignment (Bwa 0.7.17)
- Fixmate (samtools)
- Merging across lanes (samtools)
- Duplicate marking (samtools)
- Variant calling with DeepVariant

**Comment by akolesnikov** [comment] 2021-07-12 19:07
Hello Marc,

Thank you for attaching the BAM file. I will try to reproduce the issue here. Meanwhile, there is an option in DeepVariant to output a locally realigned BAM file which may be very different from the original BAM. See https://github.com/google/deepvariant/issues/280#issuecomment-593558131 for details on how to turn on the feature.

**Comment by akolesnikov** [comment] 2021-07-12 19:31
Would it be possible to also attach the reference? Also, I noticed that example in your first comment is for chr1 but attached BAM is  for chr3 different interval.

**Comment by marchoeppner** [comment] 2021-07-13 05:27
Apologies, not sure how that happened...
BAM: https://www.dropbox.com/s/qq5t53snaowiho0/debug.bam?dl=0
BAI: https://www.dropbox.com/s/e9aozinc0s6m0fw/debug.bam.bai?dl=0

Genome reference, as recommended by Heng Li: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz  (GRCh38 no ALT)

**Comment by marchoeppner** [comment] 2021-07-13 06:09
I should also note that we ran the same pipeline on data we produced in-house, and that worked perfectly fine (including the locus I picked out here). So I am wondering if there is something about the reads our collaborator provided that somehow conflicts with assumptions made by DeepVariant (?).

**Comment by akolesnikov** [comment] 2021-07-15 19:20
I ran make_examples and generated a realigned BAM for the region overlapping chr1:109161996. As a result some of the reads aligned differently. For example read "A00685:52:H2VF3DSXY:4:1352:12789:18818" is originally aligned at chr1:109,161,935 but after the realignment it is aligned at chr1:109,161,895. I also tried to align this read with BLAT (https://genome.ucsc.edu/cgi-bin/hgBlat) and the only alignment there is the one we have after the realignment.
Next, I generated a debug pileup image (using show_examples utility which is part of DeepVariant). The image allows to visualize what CNN would "see" when inference is done for this variant. In the image there are reads that do not support the variant which by design means that these reads support REF. 
It is obviously a bug which we will try to fix in the future releases. The problem occurs because we should only include reads that overlap our candidate. In this case we include reads that do not overlap a candidate. And it happens because in the original mapping these reads do overlap the candidate but after the local realignment these reads do not overlap the candidate.
This situation should be rare unless there is something wrong with the mapper which results in misaligned reads.

Pileup visualization. Take a look at "read supports variant" column. Reads marked white support variant, and reads marked gray support REF:
![show_examples__channels_chr1:109161995_A- G](https://user-images.githubusercontent.com/1168691/125844383-90091827-0bc1-41fd-9b04-dd315718cbd4.png)

IGV, original alignment is top, realigned reads are at the bottom. "A00685:52:H2VF3DSXY:4:1352:12789:18818" is marked red:
![Screenshot from 2021-07-15 12-15-03](https://user-images.githubusercontent.com/1168691/125844668-69037a66-e3f5-4750-88b5-e7c1ee488708.png)

**Comment by marchoeppner** [comment] 2021-07-16 05:50
Thanks for digging into this - yea I guess that makes sense. Will be waiting for a fix in future releases then , thanks!

**Comment by marchoeppner** [comment] 2021-08-03 13:57
Just to "update" this one more time (haven't seen any commits referencing this issue):

The problem seems a bit more pervasive than initially thought. I have now completed two benchmarking runs (NA12878) with hap.py - one using Deepvariant (1.1), and one with Strelka (2.9), input BAM file being the same for both:

Strelka - SNP Recall: 0.995 SNP Precision: 0.997 - FN: 88 FP: 56
Deepvariant - SNP Recall: 0.951 SNP Precision: 0.953 - FN: 936 FP: 904

I checked a bunch of these FN/FP calls and found that they are mostly the above described incorrect heterozygous calls. The read length for this data set is 100bp, which is shorter than our own in-house produced data (150bp) where we do not see this issue. Maybe that explains it (more uniq mappings). 

Anyway, hopefully this can be fixed soonish.

**Comment by pichuan** [comment] 2021-08-03 14:02
Hi, is this using WGS model?
You mentioned your reads are shorter. Can you try running DeepVariant v1.2.0 and see if it helps?
In this new release, we added some training data with shorter reads.

I can also ask Alexey to give you an update on his investigation of this problem. But please let us know which version you're using, and whether the new release helped.

**Comment by marchoeppner** [comment] 2021-08-04 10:43
This was exome data, so WES. 

And interestingly, yes, upgrading from 1.1 to 1.2 did solve this issue. Thanks!

**Comment by pichuan** [comment] 2021-08-04 16:47
Thanks @marchoeppner . Good to hear that 1.2 worked.
I believe @akolesnikov 's recent investigation showed that the accounting was actually correct. So, what he mentioned in https://github.com/google/deepvariant/issues/470#issuecomment-880951168 wasn't really a problem like he thought before. And he thinks the improvement needs to come from the classifier.

Given that this was WES, I suspect this improvement we mentioned in [v1.2.0 release notes](https://github.com/google/deepvariant/releases/tag/v1.2.0) might be relevant to why 1.2 WES model works better on this:

>   * In the "training" model for make_examples, we committed (https://github.com/google/deepvariant/commit/4a11046de0ad86e36d2514af9f035c9cb34414bf) that fixed an issue introduced in an earlier commit (https://github.com/google/deepvariant/commit/a4a654769f1454ea487ebf0a32d45a9f8779617b) where make_examples might generate fewer REF (class0) examples than expected.

I'll close this issue.

**Closed by pichuan** 2021-08-04 16:47 UTC
