### ISSUE TITLE
Error: validating pipeline: zones and regions cannot be specified together

### ISSUE THREAD

**Issue by ShrutiMarwaha** [google/deepvariant#96] opened 2018-09-20 21:15 UTC
Hi Developers,

I get the following error when I am trying to use the latest version (V0.7.0) of deepvariant for wes analysis. I encounter the same error even I used the example given [here](https://cloud.google.com/genomics/docs/tutorials/deepvariant). 
./deepvariant_v0.7.0_UDN644883_wes_09202018.sh
ERROR: (gcloud.alpha.genomics.pipelines.run) INVALID_ARGUMENT: Error: validating pipeline: zones and regions cannot be specified together

I have attached my script for the reference. 
[deepvariant_v0.7.0_UDN644883_wes_09202018.sh.txt](https://github.com/google/deepvariant/files/2403088/deepvariant_v0.7.0_UDN644883_wes_09202018.sh.txt)

I was able to run deepvariant for wes using V0.6.1 successfully however looking at the output vcf I 'think' the script is not restricting the variants to the bed file regions. 
[deepvariant_v0.6.1_UDN644883_wes_09132018.sh.txt](https://github.com/google/deepvariant/files/2403091/deepvariant_v0.6.1_UDN644883_wes_09132018.sh.txt)
[deepvariant_v0.6.1_UDN644883_wes_09132018.yaml.txt](https://github.com/google/deepvariant/files/2403092/deepvariant_v0.6.1_UDN644883_wes_09132018.yaml.txt)

Thanks,
Shruti

Shruti Marwaha, PhD.
Research Engineer,
Stanford Center for Undiagnosed Diseases
Stanford University

**Comment by pgrosu** [comment] 2018-09-21 12:31
Hi Shruti,

The issue is that computations have locality, and would prefer to stay within the same data center.  In your 0.6.1 scripts you specified zones for you pipeline runs (`--zones us-west1-b`) and for your gcp_deepvariant_runner (`--zones 'us-*'`), and not a region.  In your 0.7.0 script you included both a zone `--zones us-west1-*` for your gcp_deepvariant_runner, and a region in your pipelines run `--regions us-west1`.  Try to stick to one or the other, where a zone is more precise and a region contains a collection of zones.  For more information here a couple of useful links:

https://cloud.google.com/compute/docs/regions-zones/

https://cloud.google.com/compute/docs/regions-zones/global-regional-zonal-resources

Paul

**Comment by nmousavi** [comment] 2018-09-21 15:11
Check the result of  `gcloud config list`.  I suspect you have region set to some default there. If so, you should unset it by `gcloud config set compute/region ""`

**Comment by pichuan** [comment] 2018-09-25 19:03
Hi @ShrutiMarwaha , hopefully the answers above addressed your question. I'll close this issue, but feel free to re-open if you still have trouble running this.

**Closed by pichuan** 2018-09-25 19:03 UTC
