### ISSUE TITLE
I want to build deepvariant:1.5.0 from source code. My environment is Ubuntu20.04.Did I need to prebuilt the protobuf before I run the ./build-prereq.sh? If need, which version should I build.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#739] opened 2023-11-22 14:03 UTC
There are some problems while running the ./build-prereq.sh:
```
+ python3.8 -m pip install absl-py parameterized protobuf==3.13.0 pyparsing==2.2.0
Requirement already satisfied: absl-py in /usr/local/lib/python3.8/dist-packages (1.4.0)
Requirement already satisfied: parameterized in /usr/local/lib/python3.8/dist-packages (0.9.0)
Requirement already satisfied: protobuf==3.13.0 in /usr/local/lib/python3.8/dist-packages (3.13.0)
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from protobuf==3.13.0) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from protobuf==3.13.0) (69.0.2)
Installing collected packages: pyparsing
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.1
    Uninstalling pyparsing-3.1.1:
      Successfully uninstalled pyparsing-3.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
httplib2 0.21.0 requires pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2; python_version > "3.0", but you have pyparsing 2.2.0 which is incompatible.
matplotlib 3.7.3 requires pyparsing>=2.3.1, but you have pyparsing 2.2.0 which is incompatible.
Successfully installed pyparsing-2.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ DV_PLATFORM=ubuntu-20.04
+ ln -sf /usr/bin/python3.8 /usr/local/bin/python3
+ cd
+ rm -rf clif
+ proxychains git clone https://github.com/google/clif.git
ProxyChains-3.1 (http://proxychains.sf.net)
Cloning into 'clif'...
|S-chain|-<>-10.68.50.55:7890-<><>-20.205.243.166:443-<><>-OK
remote: Enumerating objects: 5846, done.
remote: Counting objects: 100% (700/700), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 5846 (delta 618), reused 625 (delta 585), pack-reused 5146
Receiving objects: 100% (5846/5846), 1.69 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (4683/4683), done.
+ cd clif
+ [[ ! -z 9ec44bde4f7f40de342a1286f84f5b608633a2d7 ]]
+ git checkout 9ec44bde4f7f40de342a1286f84f5b608633a2d7
Note: switching to '9ec44bde4f7f40de342a1286f84f5b608633a2d7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9ec44bd Replace C++ `#import <...>` with `#include <...>`
+ ./INSTALL.sh
+++ dirname ./INSTALL.sh
++ cd .
++ pwd
+ CLIFSRC_DIR=/root/clif
+ BUILD_DIR=/root/clif/build
+ declare -a CMAKE_G_FLAG
+ declare -a MAKE_PARALLELISM
+ which ninja
+ CMAKE_G_FLAGS=()
+ MAKE_OR_NINJA=make
+ MAKE_PARALLELISM=(-j 2)
+ [[ -r /proc/cpuinfo ]]
++ cat /proc/cpuinfo
++ grep -c '^processor'
+ N_CPUS=32
+ [[ 32 -gt 0 ]]
+ MAKE_PARALLELISM=(-j $N_CPUS)
+ MAKE_INSTALL_PARALLELISM=(${MAKE_PARALLELISM[@]})
+ echo 'Using make for the clif backend build.'
Using make for the clif backend build.
+ [[ '' =~ ^-?-h ]]
+ [[ -n '' ]]
++ which python3
+ PYTHON=/usr/local/bin/python3
+ echo -n 'Using Python interpreter: /usr/local/bin/python3'
Using Python interpreter: /usr/local/bin/python3+ [[ '' -eq 1 ]]
+ mkdir -p /root/clif/build
+ cd /root/clif/build
+ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'protobuf'
--   No package 'protobuf' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  clif/cmake/modules/CLIFUtils.cmake:31 (pkg_check_modules)
  clif/CMakeLists.txt:22 (include)
```

**Comment by pichuan** [comment] 2023-11-22 17:26
Hi @pioneer-pi ,
I'll try to reproduce on my side and paste my log.

**Comment by pichuan** [comment] 2023-11-22 18:34
Hi @pioneer-pi , 

Here is my attempt to reproduce the issue.

To build from source, the documentation to use is this: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md

Given that you want to build 1.5, let me use the r1.5 one (the doc is mostly the same , but I'll remember to use the 1.5 code): https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-build-test.md

To get a machine, I used a command here: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-details.md#command-for-a-cpu-only-machine-on-google-cloud-platform

```bash
gcloud compute instances create "${USER}-cpu"  \
  --scopes "compute-rw,storage-full,cloud-platform" \
  --image-family "ubuntu-2004-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "n1-standard-64" \
  --boot-disk-size "300" \
  --zone "us-west1-b" \
  --min-cpu-platform "Intel Skylake"
```

I sshed into the machine

```bash
gcloud compute ssh pichuan-cpu --zone us-west1-b
```

Then, on the machine, I get DeepVariant r1.5 source first:

```bash
git clone https://github.com/google/deepvariant.git
cd deepvariant/
git checkout r1.5
```

And I confirmed the version:

```
pichuan@pichuan-cpu:~/deepvariant$ git log | head
commit ab068c4588a02e2167051bd9e74c0c9579462b51
Author: pichuan <pichuan@google.com>
Date:   Mon Feb 27 23:03:48 2023 -0800

    Update README.md
    
    PiperOrigin-RevId: 512838102

```

From there, I followed the instructions on https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-build-test.md
So I ran:

```bash
sudo su
./build-prereq.sh
```

My run succeeded.

I looked at my log to see the section close to where your error occurred. And I see:

```
+ mkdir -p /root/clif/build
+ cd /root/clif/build
+ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'protobuf'
--   Found protobuf, version 3.13.0
-- Checking for module 'libglog'
--   Found libglog, version 0.4.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GTest: /usr/local/lib/cmake/GTest/GTestConfig.cmake (found version "1.10.0")  
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.8.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.10") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/clif/build
```
which succeeded (and then proceed to the next step)

@pioneer-pi , given that I can't reproduce this error, I'll need more information from you to understand why it failed.

This is the step where your setup failed , but mine worked:

```bash
root@pichuan-cpu:/home/pichuan/deepvariant# cd /root/clif/build
root@pichuan-cpu:~/clif/build# cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
```

It'll be good to understand how/why it failed on your side.

If you can provide more information there, I'm happy to see how I can help.

And @pioneer-pi , another question is : Can you consider using our Docker? If you're trying to install on a machine, you must already have root permission. (Our "build from source" option only works with root permission)

**Comment by pioneer-pi** [comment] 2023-11-23 02:44
@pichuan Thank you so much. I have no root in my local machine, so I start a deepvariant:1.5.0 docker container, and in this container, I git the source code and try to build it from source. The reason why I need to build it from source is that I want to change some source code of deepvariant(like pileup image code). 
I run the code:
```
cd /root/clif/build
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
```
and the problem is also:
```
-- Checking for module 'protobuf'
--   No package 'protobuf' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  clif/cmake/modules/CLIFUtils.cmake:31 (pkg_check_modules)
  clif/CMakeLists.txt:22 (include)
```
I guess if I don't prebuilt protobuf before that?  However, I found the build-prereq.sh have installed protobuf, I don't know the reason.

**Comment by pichuan** [comment] 2023-11-23 03:45
Hi @pioneer-pi ,
Got it. Unfortunately I don't know how to build if you're already inside docker. The issue you encounter there might be more relevant to the interaction between docker and cmake, which will be outside our support scope.

Right now, when I build new source code, I've always used a machine with root permissions. Then I either build from scratch, or I docker build from Dockerfile. But both will require certain permissions.

Sorry I can't be of more help here. This is outside what our team can support now, so I'll close this issue.
If you do find more workaround, please feel free to share and update!

**Closed** 2023-11-23 03:46 UTC
